# @generated by scripts/gen_sdk.py — DO NOT EDIT.

"""Typed, namespaced accessors for Keyhaven apps (generated).

Reach these via ``client.apps.<app>.<function>(owner_id=..., request=...)``.
The existing dynamic ``client.app(name)`` API is unaffected.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from keyhaven.sdk.apps.accredible import AccredibleNamespace
from keyhaven.sdk.apps.active_campaign import ActiveCampaignNamespace
from keyhaven.sdk.apps.aero_workflow import AeroWorkflowNamespace
from keyhaven.sdk.apps.agent_mail import AgentMailNamespace
from keyhaven.sdk.apps.aidbase import AidbaseNamespace
from keyhaven.sdk.apps.airtable import AirtableNamespace
from keyhaven.sdk.apps.akkio import AkkioNamespace
from keyhaven.sdk.apps.algolia import AlgoliaNamespace
from keyhaven.sdk.apps.all_images import AllImagesNamespace
from keyhaven.sdk.apps.amplitude import AmplitudeNamespace
from keyhaven.sdk.apps.anchor_browser import AnchorBrowserNamespace
from keyhaven.sdk.apps.apaleo import ApaleoNamespace
from keyhaven.sdk.apps.api_template import ApiTemplateNamespace
from keyhaven.sdk.apps.arxiv import ArxivNamespace
from keyhaven.sdk.apps.asana import AsanaNamespace
from keyhaven.sdk.apps.asana_scim import AsanaScimNamespace
from keyhaven.sdk.apps.ashby import AshbyNamespace
from keyhaven.sdk.apps.attio import AttioNamespace
from keyhaven.sdk.apps.autotask import AutotaskNamespace
from keyhaven.sdk.apps.baidu_map import BaiduMapNamespace
from keyhaven.sdk.apps.basecamp import BasecampNamespace
from keyhaven.sdk.apps.baserow import BaserowNamespace
from keyhaven.sdk.apps.beehiiv import BeehiivNamespace
from keyhaven.sdk.apps.bigcommerce import BigcommerceNamespace
from keyhaven.sdk.apps.bitbucket import BitbucketNamespace
from keyhaven.sdk.apps.bitly import BitlyNamespace
from keyhaven.sdk.apps.box import BoxNamespace
from keyhaven.sdk.apps.braintree import BraintreeNamespace
from keyhaven.sdk.apps.brave_search import BraveSearchNamespace
from keyhaven.sdk.apps.braze import BrazeNamespace
from keyhaven.sdk.apps.breezy import BreezyNamespace
from keyhaven.sdk.apps.browserbase import BrowserbaseNamespace
from keyhaven.sdk.apps.bullhorn import BullhornNamespace
from keyhaven.sdk.apps.cal import CalNamespace
from keyhaven.sdk.apps.calendly import CalendlyNamespace
from keyhaven.sdk.apps.callrail import CallrailNamespace
from keyhaven.sdk.apps.canva import CanvaNamespace
from keyhaven.sdk.apps.chargebee import ChargebeeNamespace
from keyhaven.sdk.apps.circle_so import CircleSoNamespace
from keyhaven.sdk.apps.clerk import ClerkNamespace
from keyhaven.sdk.apps.clicksend import ClicksendNamespace
from keyhaven.sdk.apps.clickup import ClickupNamespace
from keyhaven.sdk.apps.close import CloseNamespace
from keyhaven.sdk.apps.cloudbeds import CloudbedsNamespace
from keyhaven.sdk.apps.cloudflare import CloudflareNamespace
from keyhaven.sdk.apps.coda import CodaNamespace
from keyhaven.sdk.apps.cognito_forms import CognitoFormsNamespace
from keyhaven.sdk.apps.coin_gecko import CoinGeckoNamespace
from keyhaven.sdk.apps.coinmarketcap import CoinmarketcapNamespace
from keyhaven.sdk.apps.constant_contact import ConstantContactNamespace
from keyhaven.sdk.apps.contentful import ContentfulNamespace
from keyhaven.sdk.apps.copper import CopperNamespace
from keyhaven.sdk.apps.crunchbase import CrunchbaseNamespace
from keyhaven.sdk.apps.customer_io import CustomerIoNamespace
from keyhaven.sdk.apps.datadog import DatadogNamespace
from keyhaven.sdk.apps.daytona import DaytonaNamespace
from keyhaven.sdk.apps.deel import DeelNamespace
from keyhaven.sdk.apps.dexscreener import DexscreenerNamespace
from keyhaven.sdk.apps.dialpad import DialpadNamespace
from keyhaven.sdk.apps.dify import DifyNamespace
from keyhaven.sdk.apps.digitalocean import DigitaloceanNamespace
from keyhaven.sdk.apps.discord import DiscordNamespace
from keyhaven.sdk.apps.discourse import DiscourseNamespace
from keyhaven.sdk.apps.drata import DrataNamespace
from keyhaven.sdk.apps.dropbox import DropboxNamespace
from keyhaven.sdk.apps.dropbox_sign import DropboxSignNamespace
from keyhaven.sdk.apps.dynatrace import DynatraceNamespace
from keyhaven.sdk.apps.easypost import EasypostNamespace
from keyhaven.sdk.apps.ebay import EbayNamespace
from keyhaven.sdk.apps.eleven_labs import ElevenLabsNamespace
from keyhaven.sdk.apps.elevenlabs import ElevenlabsNamespace
from keyhaven.sdk.apps.envoy import EnvoyNamespace
from keyhaven.sdk.apps.etherscan import EtherscanNamespace
from keyhaven.sdk.apps.etsy import EtsyNamespace
from keyhaven.sdk.apps.eventbrite import EventbriteNamespace
from keyhaven.sdk.apps.exa_ai import ExaAiNamespace
from keyhaven.sdk.apps.factorial import FactorialNamespace
from keyhaven.sdk.apps.factorial_hr import FactorialHrNamespace
from keyhaven.sdk.apps.fathom import FathomNamespace
from keyhaven.sdk.apps.feishu import FeishuNamespace
from keyhaven.sdk.apps.figma import FigmaNamespace
from keyhaven.sdk.apps.fillout import FilloutNamespace
from keyhaven.sdk.apps.firecrawl import FirecrawlNamespace
from keyhaven.sdk.apps.fireflies import FirefliesNamespace
from keyhaven.sdk.apps.fitbit import FitbitNamespace
from keyhaven.sdk.apps.fortnox import FortnoxNamespace
from keyhaven.sdk.apps.freeagent import FreeagentNamespace
from keyhaven.sdk.apps.freshbooks import FreshbooksNamespace
from keyhaven.sdk.apps.freshdesk import FreshdeskNamespace
from keyhaven.sdk.apps.freshservice import FreshserviceNamespace
from keyhaven.sdk.apps.front import FrontNamespace
from keyhaven.sdk.apps.ghost_content import GhostContentNamespace
from keyhaven.sdk.apps.github import GithubNamespace
from keyhaven.sdk.apps.gitlab import GitlabNamespace
from keyhaven.sdk.apps.gitlab_pat import GitlabPatNamespace
from keyhaven.sdk.apps.gmail import GmailNamespace
from keyhaven.sdk.apps.goco import GocoNamespace
from keyhaven.sdk.apps.gong import GongNamespace
from keyhaven.sdk.apps.google_analytics_admin import GoogleAnalyticsAdminNamespace
from keyhaven.sdk.apps.google_calendar import GoogleCalendarNamespace
from keyhaven.sdk.apps.google_docs import GoogleDocsNamespace
from keyhaven.sdk.apps.google_drive import GoogleDriveNamespace
from keyhaven.sdk.apps.google_maps import GoogleMapsNamespace
from keyhaven.sdk.apps.google_meet import GoogleMeetNamespace
from keyhaven.sdk.apps.google_sheets import GoogleSheetsNamespace
from keyhaven.sdk.apps.google_tasks import GoogleTasksNamespace
from keyhaven.sdk.apps.grafana import GrafanaNamespace
from keyhaven.sdk.apps.grain import GrainNamespace
from keyhaven.sdk.apps.greenhouse import GreenhouseNamespace
from keyhaven.sdk.apps.gumroad import GumroadNamespace
from keyhaven.sdk.apps.gusto import GustoNamespace
from keyhaven.sdk.apps.hackernews import HackernewsNamespace
from keyhaven.sdk.apps.harvest import HarvestNamespace
from keyhaven.sdk.apps.helpscout_mailbox import HelpscoutMailboxNamespace
from keyhaven.sdk.apps.heygen import HeygenNamespace
from keyhaven.sdk.apps.highlevel import HighlevelNamespace
from keyhaven.sdk.apps.holded import HoldedNamespace
from keyhaven.sdk.apps.hover import HoverNamespace
from keyhaven.sdk.apps.hubspot import HubspotNamespace
from keyhaven.sdk.apps.insightly import InsightlyNamespace
from keyhaven.sdk.apps.instagram import InstagramNamespace
from keyhaven.sdk.apps.jira import JiraNamespace
from keyhaven.sdk.apps.jotform import JotformNamespace
from keyhaven.sdk.apps.keap import KeapNamespace
from keyhaven.sdk.apps.klaviyo import KlaviyoNamespace
from keyhaven.sdk.apps.knowbe4 import Knowbe4Namespace
from keyhaven.sdk.apps.kustomer import KustomerNamespace
from keyhaven.sdk.apps.lattice import LatticeNamespace
from keyhaven.sdk.apps.lemlist import LemlistNamespace
from keyhaven.sdk.apps.linkedin import LinkedinNamespace
from keyhaven.sdk.apps.linkup import LinkupNamespace
from keyhaven.sdk.apps.lmnt import LmntNamespace
from keyhaven.sdk.apps.lob import LobNamespace
from keyhaven.sdk.apps.lokalise import LokaliseNamespace
from keyhaven.sdk.apps.luma import LumaNamespace
from keyhaven.sdk.apps.mailchimp import MailchimpNamespace
from keyhaven.sdk.apps.mailgun import MailgunNamespace
from keyhaven.sdk.apps.mailjet import MailjetNamespace
from keyhaven.sdk.apps.manatal import ManatalNamespace
from keyhaven.sdk.apps.maxio import MaxioNamespace
from keyhaven.sdk.apps.mem0 import Mem0Namespace
from keyhaven.sdk.apps.metabase import MetabaseNamespace
from keyhaven.sdk.apps.microsoft_calendar import MicrosoftCalendarNamespace
from keyhaven.sdk.apps.microsoft_onedrive import MicrosoftOnedriveNamespace
from keyhaven.sdk.apps.microsoft_outlook import MicrosoftOutlookNamespace
from keyhaven.sdk.apps.microsoft_teams import MicrosoftTeamsNamespace
from keyhaven.sdk.apps.mindbody import MindbodyNamespace
from keyhaven.sdk.apps.miro import MiroNamespace
from keyhaven.sdk.apps.missive import MissiveNamespace
from keyhaven.sdk.apps.mixpanel import MixpanelNamespace
from keyhaven.sdk.apps.mollie import MollieNamespace
from keyhaven.sdk.apps.neon import NeonNamespace
from keyhaven.sdk.apps.netlify import NetlifyNamespace
from keyhaven.sdk.apps.notion import NotionNamespace
from keyhaven.sdk.apps.notion_scim import NotionScimNamespace
from keyhaven.sdk.apps.notte import NotteNamespace
from keyhaven.sdk.apps.one_page_crm import OnePageCrmNamespace
from keyhaven.sdk.apps.one_signal import OneSignalNamespace
from keyhaven.sdk.apps.open_weather_map import OpenWeatherMapNamespace
from keyhaven.sdk.apps.openai import OpenaiNamespace
from keyhaven.sdk.apps.oura import OuraNamespace
from keyhaven.sdk.apps.outreach import OutreachNamespace
from keyhaven.sdk.apps.paddle import PaddleNamespace
from keyhaven.sdk.apps.pagerduty import PagerdutyNamespace
from keyhaven.sdk.apps.pandadoc import PandadocNamespace
from keyhaven.sdk.apps.paypal import PaypalNamespace
from keyhaven.sdk.apps.pendo import PendoNamespace
from keyhaven.sdk.apps.perplexity import PerplexityNamespace
from keyhaven.sdk.apps.pinterest import PinterestNamespace
from keyhaven.sdk.apps.pipedrive import PipedriveNamespace
from keyhaven.sdk.apps.pivotaltracker import PivotaltrackerNamespace
from keyhaven.sdk.apps.podium import PodiumNamespace
from keyhaven.sdk.apps.posthog import PosthogNamespace
from keyhaven.sdk.apps.printful import PrintfulNamespace
from keyhaven.sdk.apps.procore import ProcoreNamespace
from keyhaven.sdk.apps.productboard import ProductboardNamespace
from keyhaven.sdk.apps.quickbase import QuickbaseNamespace
from keyhaven.sdk.apps.quickbooks import QuickbooksNamespace
from keyhaven.sdk.apps.ramp import RampNamespace
from keyhaven.sdk.apps.razorpay import RazorpayNamespace
from keyhaven.sdk.apps.readwise import ReadwiseNamespace
from keyhaven.sdk.apps.reapit import ReapitNamespace
from keyhaven.sdk.apps.recharge import RechargeNamespace
from keyhaven.sdk.apps.recruitee import RecruiteeNamespace
from keyhaven.sdk.apps.reddit import RedditNamespace
from keyhaven.sdk.apps.render import RenderNamespace
from keyhaven.sdk.apps.replicate import ReplicateNamespace
from keyhaven.sdk.apps.resend import ResendNamespace
from keyhaven.sdk.apps.ring_central import RingCentralNamespace
from keyhaven.sdk.apps.rocketlane import RocketlaneNamespace
from keyhaven.sdk.apps.rocketreach import RocketreachNamespace
from keyhaven.sdk.apps.rossum import RossumNamespace
from keyhaven.sdk.apps.sage import SageNamespace
from keyhaven.sdk.apps.salesloft import SalesloftNamespace
from keyhaven.sdk.apps.scrapybara import ScrapybaraNamespace
from keyhaven.sdk.apps.segment import SegmentNamespace
from keyhaven.sdk.apps.sellsy import SellsyNamespace
from keyhaven.sdk.apps.sendgrid import SendgridNamespace
from keyhaven.sdk.apps.sentry import SentryNamespace
from keyhaven.sdk.apps.serpapi import SerpapiNamespace
from keyhaven.sdk.apps.servicem8 import Servicem8Namespace
from keyhaven.sdk.apps.share_point import SharePointNamespace
from keyhaven.sdk.apps.shippo import ShippoNamespace
from keyhaven.sdk.apps.shortcut import ShortcutNamespace
from keyhaven.sdk.apps.signnow import SignnowNamespace
from keyhaven.sdk.apps.slack import SlackNamespace
from keyhaven.sdk.apps.solscan import SolscanNamespace
from keyhaven.sdk.apps.splitwise import SplitwiseNamespace
from keyhaven.sdk.apps.spotify import SpotifyNamespace
from keyhaven.sdk.apps.squarespace import SquarespaceNamespace
from keyhaven.sdk.apps.squareup import SquareupNamespace
from keyhaven.sdk.apps.stackexchange import StackexchangeNamespace
from keyhaven.sdk.apps.steel import SteelNamespace
from keyhaven.sdk.apps.strava import StravaNamespace
from keyhaven.sdk.apps.stripe import StripeNamespace
from keyhaven.sdk.apps.stripe_api_key import StripeApiKeyNamespace
from keyhaven.sdk.apps.supabase import SupabaseNamespace
from keyhaven.sdk.apps.survey_monkey import SurveyMonkeyNamespace
from keyhaven.sdk.apps.tally import TallyNamespace
from keyhaven.sdk.apps.tavily import TavilyNamespace
from keyhaven.sdk.apps.teamwork import TeamworkNamespace
from keyhaven.sdk.apps.tines import TinesNamespace
from keyhaven.sdk.apps.todoist import TodoistNamespace
from keyhaven.sdk.apps.toggl import TogglNamespace
from keyhaven.sdk.apps.trello_scim import TrelloScimNamespace
from keyhaven.sdk.apps.twenty_crm import TwentyCrmNamespace
from keyhaven.sdk.apps.twilio import TwilioNamespace
from keyhaven.sdk.apps.twitch import TwitchNamespace
from keyhaven.sdk.apps.twitter_v2 import TwitterV2Namespace
from keyhaven.sdk.apps.typeform import TypeformNamespace
from keyhaven.sdk.apps.typefully import TypefullyNamespace
from keyhaven.sdk.apps.uber import UberNamespace
from keyhaven.sdk.apps.ultra_msg import UltraMsgNamespace
from keyhaven.sdk.apps.vercel import VercelNamespace
from keyhaven.sdk.apps.vimeo import VimeoNamespace
from keyhaven.sdk.apps.wealthbox import WealthboxNamespace
from keyhaven.sdk.apps.webex import WebexNamespace
from keyhaven.sdk.apps.woocommerce import WoocommerceNamespace
from keyhaven.sdk.apps.wordpress import WordpressNamespace
from keyhaven.sdk.apps.workable import WorkableNamespace
from keyhaven.sdk.apps.wrike import WrikeNamespace
from keyhaven.sdk.apps.x import XNamespace
from keyhaven.sdk.apps.youtube import YoutubeNamespace
from keyhaven.sdk.apps.zendesk_sell import ZendeskSellNamespace
from keyhaven.sdk.apps.zenrows import ZenrowsNamespace
from keyhaven.sdk.apps.zoho_desk import ZohoDeskNamespace
from keyhaven.sdk.apps.zoom import ZoomNamespace

if TYPE_CHECKING:
    from keyhaven.sdk.client import Keyhaven

__all__ = [
    "AccredibleNamespace",
    "ActiveCampaignNamespace",
    "AeroWorkflowNamespace",
    "AgentMailNamespace",
    "AidbaseNamespace",
    "AirtableNamespace",
    "AkkioNamespace",
    "AlgoliaNamespace",
    "AllImagesNamespace",
    "AmplitudeNamespace",
    "AnchorBrowserNamespace",
    "ApaleoNamespace",
    "ApiTemplateNamespace",
    "Apps",
    "ArxivNamespace",
    "AsanaNamespace",
    "AsanaScimNamespace",
    "AshbyNamespace",
    "AttioNamespace",
    "AutotaskNamespace",
    "BaiduMapNamespace",
    "BasecampNamespace",
    "BaserowNamespace",
    "BeehiivNamespace",
    "BigcommerceNamespace",
    "BitbucketNamespace",
    "BitlyNamespace",
    "BoxNamespace",
    "BraintreeNamespace",
    "BraveSearchNamespace",
    "BrazeNamespace",
    "BreezyNamespace",
    "BrowserbaseNamespace",
    "BullhornNamespace",
    "CalNamespace",
    "CalendlyNamespace",
    "CallrailNamespace",
    "CanvaNamespace",
    "ChargebeeNamespace",
    "CircleSoNamespace",
    "ClerkNamespace",
    "ClicksendNamespace",
    "ClickupNamespace",
    "CloseNamespace",
    "CloudbedsNamespace",
    "CloudflareNamespace",
    "CodaNamespace",
    "CognitoFormsNamespace",
    "CoinGeckoNamespace",
    "CoinmarketcapNamespace",
    "ConstantContactNamespace",
    "ContentfulNamespace",
    "CopperNamespace",
    "CrunchbaseNamespace",
    "CustomerIoNamespace",
    "DatadogNamespace",
    "DaytonaNamespace",
    "DeelNamespace",
    "DexscreenerNamespace",
    "DialpadNamespace",
    "DifyNamespace",
    "DigitaloceanNamespace",
    "DiscordNamespace",
    "DiscourseNamespace",
    "DrataNamespace",
    "DropboxNamespace",
    "DropboxSignNamespace",
    "DynatraceNamespace",
    "EasypostNamespace",
    "EbayNamespace",
    "ElevenLabsNamespace",
    "ElevenlabsNamespace",
    "EnvoyNamespace",
    "EtherscanNamespace",
    "EtsyNamespace",
    "EventbriteNamespace",
    "ExaAiNamespace",
    "FactorialHrNamespace",
    "FactorialNamespace",
    "FathomNamespace",
    "FeishuNamespace",
    "FigmaNamespace",
    "FilloutNamespace",
    "FirecrawlNamespace",
    "FirefliesNamespace",
    "FitbitNamespace",
    "FortnoxNamespace",
    "FreeagentNamespace",
    "FreshbooksNamespace",
    "FreshdeskNamespace",
    "FreshserviceNamespace",
    "FrontNamespace",
    "GhostContentNamespace",
    "GithubNamespace",
    "GitlabNamespace",
    "GitlabPatNamespace",
    "GmailNamespace",
    "GocoNamespace",
    "GongNamespace",
    "GoogleAnalyticsAdminNamespace",
    "GoogleCalendarNamespace",
    "GoogleDocsNamespace",
    "GoogleDriveNamespace",
    "GoogleMapsNamespace",
    "GoogleMeetNamespace",
    "GoogleSheetsNamespace",
    "GoogleTasksNamespace",
    "GrafanaNamespace",
    "GrainNamespace",
    "GreenhouseNamespace",
    "GumroadNamespace",
    "GustoNamespace",
    "HackernewsNamespace",
    "HarvestNamespace",
    "HelpscoutMailboxNamespace",
    "HeygenNamespace",
    "HighlevelNamespace",
    "HoldedNamespace",
    "HoverNamespace",
    "HubspotNamespace",
    "InsightlyNamespace",
    "InstagramNamespace",
    "JiraNamespace",
    "JotformNamespace",
    "KeapNamespace",
    "KlaviyoNamespace",
    "Knowbe4Namespace",
    "KustomerNamespace",
    "LatticeNamespace",
    "LemlistNamespace",
    "LinkedinNamespace",
    "LinkupNamespace",
    "LmntNamespace",
    "LobNamespace",
    "LokaliseNamespace",
    "LumaNamespace",
    "MailchimpNamespace",
    "MailgunNamespace",
    "MailjetNamespace",
    "ManatalNamespace",
    "MaxioNamespace",
    "Mem0Namespace",
    "MetabaseNamespace",
    "MicrosoftCalendarNamespace",
    "MicrosoftOnedriveNamespace",
    "MicrosoftOutlookNamespace",
    "MicrosoftTeamsNamespace",
    "MindbodyNamespace",
    "MiroNamespace",
    "MissiveNamespace",
    "MixpanelNamespace",
    "MollieNamespace",
    "NeonNamespace",
    "NetlifyNamespace",
    "NotionNamespace",
    "NotionScimNamespace",
    "NotteNamespace",
    "OnePageCrmNamespace",
    "OneSignalNamespace",
    "OpenWeatherMapNamespace",
    "OpenaiNamespace",
    "OuraNamespace",
    "OutreachNamespace",
    "PaddleNamespace",
    "PagerdutyNamespace",
    "PandadocNamespace",
    "PaypalNamespace",
    "PendoNamespace",
    "PerplexityNamespace",
    "PinterestNamespace",
    "PipedriveNamespace",
    "PivotaltrackerNamespace",
    "PodiumNamespace",
    "PosthogNamespace",
    "PrintfulNamespace",
    "ProcoreNamespace",
    "ProductboardNamespace",
    "QuickbaseNamespace",
    "QuickbooksNamespace",
    "RampNamespace",
    "RazorpayNamespace",
    "ReadwiseNamespace",
    "ReapitNamespace",
    "RechargeNamespace",
    "RecruiteeNamespace",
    "RedditNamespace",
    "RenderNamespace",
    "ReplicateNamespace",
    "ResendNamespace",
    "RingCentralNamespace",
    "RocketlaneNamespace",
    "RocketreachNamespace",
    "RossumNamespace",
    "SageNamespace",
    "SalesloftNamespace",
    "ScrapybaraNamespace",
    "SegmentNamespace",
    "SellsyNamespace",
    "SendgridNamespace",
    "SentryNamespace",
    "SerpapiNamespace",
    "Servicem8Namespace",
    "SharePointNamespace",
    "ShippoNamespace",
    "ShortcutNamespace",
    "SignnowNamespace",
    "SlackNamespace",
    "SolscanNamespace",
    "SplitwiseNamespace",
    "SpotifyNamespace",
    "SquarespaceNamespace",
    "SquareupNamespace",
    "StackexchangeNamespace",
    "SteelNamespace",
    "StravaNamespace",
    "StripeApiKeyNamespace",
    "StripeNamespace",
    "SupabaseNamespace",
    "SurveyMonkeyNamespace",
    "TallyNamespace",
    "TavilyNamespace",
    "TeamworkNamespace",
    "TinesNamespace",
    "TodoistNamespace",
    "TogglNamespace",
    "TrelloScimNamespace",
    "TwentyCrmNamespace",
    "TwilioNamespace",
    "TwitchNamespace",
    "TwitterV2Namespace",
    "TypeformNamespace",
    "TypefullyNamespace",
    "UberNamespace",
    "UltraMsgNamespace",
    "VercelNamespace",
    "VimeoNamespace",
    "WealthboxNamespace",
    "WebexNamespace",
    "WoocommerceNamespace",
    "WordpressNamespace",
    "WorkableNamespace",
    "WrikeNamespace",
    "XNamespace",
    "YoutubeNamespace",
    "ZendeskSellNamespace",
    "ZenrowsNamespace",
    "ZohoDeskNamespace",
    "ZoomNamespace",
]


class Apps:
    """Typed, namespaced accessor for every app that exposes functions."""

    def __init__(self, client: Keyhaven) -> None:
        self.accredible = AccredibleNamespace(client)
        self.active_campaign = ActiveCampaignNamespace(client)
        self.aero_workflow = AeroWorkflowNamespace(client)
        self.agent_mail = AgentMailNamespace(client)
        self.aidbase = AidbaseNamespace(client)
        self.airtable = AirtableNamespace(client)
        self.akkio = AkkioNamespace(client)
        self.algolia = AlgoliaNamespace(client)
        self.all_images = AllImagesNamespace(client)
        self.amplitude = AmplitudeNamespace(client)
        self.anchor_browser = AnchorBrowserNamespace(client)
        self.apaleo = ApaleoNamespace(client)
        self.api_template = ApiTemplateNamespace(client)
        self.arxiv = ArxivNamespace(client)
        self.asana = AsanaNamespace(client)
        self.asana_scim = AsanaScimNamespace(client)
        self.ashby = AshbyNamespace(client)
        self.attio = AttioNamespace(client)
        self.autotask = AutotaskNamespace(client)
        self.baidu_map = BaiduMapNamespace(client)
        self.basecamp = BasecampNamespace(client)
        self.baserow = BaserowNamespace(client)
        self.beehiiv = BeehiivNamespace(client)
        self.bigcommerce = BigcommerceNamespace(client)
        self.bitbucket = BitbucketNamespace(client)
        self.bitly = BitlyNamespace(client)
        self.box = BoxNamespace(client)
        self.braintree = BraintreeNamespace(client)
        self.brave_search = BraveSearchNamespace(client)
        self.braze = BrazeNamespace(client)
        self.breezy = BreezyNamespace(client)
        self.browserbase = BrowserbaseNamespace(client)
        self.bullhorn = BullhornNamespace(client)
        self.cal = CalNamespace(client)
        self.calendly = CalendlyNamespace(client)
        self.callrail = CallrailNamespace(client)
        self.canva = CanvaNamespace(client)
        self.chargebee = ChargebeeNamespace(client)
        self.circle_so = CircleSoNamespace(client)
        self.clerk = ClerkNamespace(client)
        self.clicksend = ClicksendNamespace(client)
        self.clickup = ClickupNamespace(client)
        self.close = CloseNamespace(client)
        self.cloudbeds = CloudbedsNamespace(client)
        self.cloudflare = CloudflareNamespace(client)
        self.coda = CodaNamespace(client)
        self.cognito_forms = CognitoFormsNamespace(client)
        self.coin_gecko = CoinGeckoNamespace(client)
        self.coinmarketcap = CoinmarketcapNamespace(client)
        self.constant_contact = ConstantContactNamespace(client)
        self.contentful = ContentfulNamespace(client)
        self.copper = CopperNamespace(client)
        self.crunchbase = CrunchbaseNamespace(client)
        self.customer_io = CustomerIoNamespace(client)
        self.datadog = DatadogNamespace(client)
        self.daytona = DaytonaNamespace(client)
        self.deel = DeelNamespace(client)
        self.dexscreener = DexscreenerNamespace(client)
        self.dialpad = DialpadNamespace(client)
        self.dify = DifyNamespace(client)
        self.digitalocean = DigitaloceanNamespace(client)
        self.discord = DiscordNamespace(client)
        self.discourse = DiscourseNamespace(client)
        self.drata = DrataNamespace(client)
        self.dropbox = DropboxNamespace(client)
        self.dropbox_sign = DropboxSignNamespace(client)
        self.dynatrace = DynatraceNamespace(client)
        self.easypost = EasypostNamespace(client)
        self.ebay = EbayNamespace(client)
        self.eleven_labs = ElevenLabsNamespace(client)
        self.elevenlabs = ElevenlabsNamespace(client)
        self.envoy = EnvoyNamespace(client)
        self.etherscan = EtherscanNamespace(client)
        self.etsy = EtsyNamespace(client)
        self.eventbrite = EventbriteNamespace(client)
        self.exa_ai = ExaAiNamespace(client)
        self.factorial = FactorialNamespace(client)
        self.factorial_hr = FactorialHrNamespace(client)
        self.fathom = FathomNamespace(client)
        self.feishu = FeishuNamespace(client)
        self.figma = FigmaNamespace(client)
        self.fillout = FilloutNamespace(client)
        self.firecrawl = FirecrawlNamespace(client)
        self.fireflies = FirefliesNamespace(client)
        self.fitbit = FitbitNamespace(client)
        self.fortnox = FortnoxNamespace(client)
        self.freeagent = FreeagentNamespace(client)
        self.freshbooks = FreshbooksNamespace(client)
        self.freshdesk = FreshdeskNamespace(client)
        self.freshservice = FreshserviceNamespace(client)
        self.front = FrontNamespace(client)
        self.ghost_content = GhostContentNamespace(client)
        self.github = GithubNamespace(client)
        self.gitlab = GitlabNamespace(client)
        self.gitlab_pat = GitlabPatNamespace(client)
        self.gmail = GmailNamespace(client)
        self.goco = GocoNamespace(client)
        self.gong = GongNamespace(client)
        self.google_analytics_admin = GoogleAnalyticsAdminNamespace(client)
        self.google_calendar = GoogleCalendarNamespace(client)
        self.google_docs = GoogleDocsNamespace(client)
        self.google_drive = GoogleDriveNamespace(client)
        self.google_maps = GoogleMapsNamespace(client)
        self.google_meet = GoogleMeetNamespace(client)
        self.google_sheets = GoogleSheetsNamespace(client)
        self.google_tasks = GoogleTasksNamespace(client)
        self.grafana = GrafanaNamespace(client)
        self.grain = GrainNamespace(client)
        self.greenhouse = GreenhouseNamespace(client)
        self.gumroad = GumroadNamespace(client)
        self.gusto = GustoNamespace(client)
        self.hackernews = HackernewsNamespace(client)
        self.harvest = HarvestNamespace(client)
        self.helpscout_mailbox = HelpscoutMailboxNamespace(client)
        self.heygen = HeygenNamespace(client)
        self.highlevel = HighlevelNamespace(client)
        self.holded = HoldedNamespace(client)
        self.hover = HoverNamespace(client)
        self.hubspot = HubspotNamespace(client)
        self.insightly = InsightlyNamespace(client)
        self.instagram = InstagramNamespace(client)
        self.jira = JiraNamespace(client)
        self.jotform = JotformNamespace(client)
        self.keap = KeapNamespace(client)
        self.klaviyo = KlaviyoNamespace(client)
        self.knowbe4 = Knowbe4Namespace(client)
        self.kustomer = KustomerNamespace(client)
        self.lattice = LatticeNamespace(client)
        self.lemlist = LemlistNamespace(client)
        self.linkedin = LinkedinNamespace(client)
        self.linkup = LinkupNamespace(client)
        self.lmnt = LmntNamespace(client)
        self.lob = LobNamespace(client)
        self.lokalise = LokaliseNamespace(client)
        self.luma = LumaNamespace(client)
        self.mailchimp = MailchimpNamespace(client)
        self.mailgun = MailgunNamespace(client)
        self.mailjet = MailjetNamespace(client)
        self.manatal = ManatalNamespace(client)
        self.maxio = MaxioNamespace(client)
        self.mem0 = Mem0Namespace(client)
        self.metabase = MetabaseNamespace(client)
        self.microsoft_calendar = MicrosoftCalendarNamespace(client)
        self.microsoft_onedrive = MicrosoftOnedriveNamespace(client)
        self.microsoft_outlook = MicrosoftOutlookNamespace(client)
        self.microsoft_teams = MicrosoftTeamsNamespace(client)
        self.mindbody = MindbodyNamespace(client)
        self.miro = MiroNamespace(client)
        self.missive = MissiveNamespace(client)
        self.mixpanel = MixpanelNamespace(client)
        self.mollie = MollieNamespace(client)
        self.neon = NeonNamespace(client)
        self.netlify = NetlifyNamespace(client)
        self.notion = NotionNamespace(client)
        self.notion_scim = NotionScimNamespace(client)
        self.notte = NotteNamespace(client)
        self.one_page_crm = OnePageCrmNamespace(client)
        self.one_signal = OneSignalNamespace(client)
        self.open_weather_map = OpenWeatherMapNamespace(client)
        self.openai = OpenaiNamespace(client)
        self.oura = OuraNamespace(client)
        self.outreach = OutreachNamespace(client)
        self.paddle = PaddleNamespace(client)
        self.pagerduty = PagerdutyNamespace(client)
        self.pandadoc = PandadocNamespace(client)
        self.paypal = PaypalNamespace(client)
        self.pendo = PendoNamespace(client)
        self.perplexity = PerplexityNamespace(client)
        self.pinterest = PinterestNamespace(client)
        self.pipedrive = PipedriveNamespace(client)
        self.pivotaltracker = PivotaltrackerNamespace(client)
        self.podium = PodiumNamespace(client)
        self.posthog = PosthogNamespace(client)
        self.printful = PrintfulNamespace(client)
        self.procore = ProcoreNamespace(client)
        self.productboard = ProductboardNamespace(client)
        self.quickbase = QuickbaseNamespace(client)
        self.quickbooks = QuickbooksNamespace(client)
        self.ramp = RampNamespace(client)
        self.razorpay = RazorpayNamespace(client)
        self.readwise = ReadwiseNamespace(client)
        self.reapit = ReapitNamespace(client)
        self.recharge = RechargeNamespace(client)
        self.recruitee = RecruiteeNamespace(client)
        self.reddit = RedditNamespace(client)
        self.render = RenderNamespace(client)
        self.replicate = ReplicateNamespace(client)
        self.resend = ResendNamespace(client)
        self.ring_central = RingCentralNamespace(client)
        self.rocketlane = RocketlaneNamespace(client)
        self.rocketreach = RocketreachNamespace(client)
        self.rossum = RossumNamespace(client)
        self.sage = SageNamespace(client)
        self.salesloft = SalesloftNamespace(client)
        self.scrapybara = ScrapybaraNamespace(client)
        self.segment = SegmentNamespace(client)
        self.sellsy = SellsyNamespace(client)
        self.sendgrid = SendgridNamespace(client)
        self.sentry = SentryNamespace(client)
        self.serpapi = SerpapiNamespace(client)
        self.servicem8 = Servicem8Namespace(client)
        self.share_point = SharePointNamespace(client)
        self.shippo = ShippoNamespace(client)
        self.shortcut = ShortcutNamespace(client)
        self.signnow = SignnowNamespace(client)
        self.slack = SlackNamespace(client)
        self.solscan = SolscanNamespace(client)
        self.splitwise = SplitwiseNamespace(client)
        self.spotify = SpotifyNamespace(client)
        self.squarespace = SquarespaceNamespace(client)
        self.squareup = SquareupNamespace(client)
        self.stackexchange = StackexchangeNamespace(client)
        self.steel = SteelNamespace(client)
        self.strava = StravaNamespace(client)
        self.stripe = StripeNamespace(client)
        self.stripe_api_key = StripeApiKeyNamespace(client)
        self.supabase = SupabaseNamespace(client)
        self.survey_monkey = SurveyMonkeyNamespace(client)
        self.tally = TallyNamespace(client)
        self.tavily = TavilyNamespace(client)
        self.teamwork = TeamworkNamespace(client)
        self.tines = TinesNamespace(client)
        self.todoist = TodoistNamespace(client)
        self.toggl = TogglNamespace(client)
        self.trello_scim = TrelloScimNamespace(client)
        self.twenty_crm = TwentyCrmNamespace(client)
        self.twilio = TwilioNamespace(client)
        self.twitch = TwitchNamespace(client)
        self.twitter_v2 = TwitterV2Namespace(client)
        self.typeform = TypeformNamespace(client)
        self.typefully = TypefullyNamespace(client)
        self.uber = UberNamespace(client)
        self.ultra_msg = UltraMsgNamespace(client)
        self.vercel = VercelNamespace(client)
        self.vimeo = VimeoNamespace(client)
        self.wealthbox = WealthboxNamespace(client)
        self.webex = WebexNamespace(client)
        self.woocommerce = WoocommerceNamespace(client)
        self.wordpress = WordpressNamespace(client)
        self.workable = WorkableNamespace(client)
        self.wrike = WrikeNamespace(client)
        self.x = XNamespace(client)
        self.youtube = YoutubeNamespace(client)
        self.zendesk_sell = ZendeskSellNamespace(client)
        self.zenrows = ZenrowsNamespace(client)
        self.zoho_desk = ZohoDeskNamespace(client)
        self.zoom = ZoomNamespace(client)
