# @generated by scripts/gen_sdk.py — DO NOT EDIT.

"""Typed SDK namespace for the `baidu_map` app (generated)."""

from __future__ import annotations

from typing import TYPE_CHECKING, Any, Literal

from pydantic import BaseModel, ConfigDict

from keyhaven.sdk._constants import DEFAULT_ACCOUNT_ID

if TYPE_CHECKING:
    from keyhaven.sdk.client import Keyhaven


class BaiduMapDrivingDirectionsQuery(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    origin: str
    destination: str
    timestamp: int | None = None
    origin_uid: str | None = None
    destination_uid: str | None = None
    waypoints: str | None = None
    coord_type: Literal["bd09ll", "bd09mc", "gcj02", "wgs84"] = "bd09ll"
    ret_coordtype: Literal["bd09ll", "gcj02"] = "bd09ll"
    tactics: Literal["0", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13"] = "0"
    alternatives: Literal["0", "1"] = "0"
    cartype: str = "0"
    plate_number: str | None = None
    gps_direction: str | None = None
    radius: str | None = None
    speed: str | None = None
    walkinfo: Literal["0", "1"] = "0"
    steps_info: Literal["0", "1"] = "0"
    origin_bind_strategy: Literal["0", "1"] = "0"
    dest_bind_strategy: Literal["0", "1"] = "0"
    origin_road_type: Literal["0", "1", "2", "3", "4"] = "0"
    output: Literal["json", "xml"] = "json"
    sn: str | None = None


class BaiduMapDrivingDirectionsRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    query: BaiduMapDrivingDirectionsQuery


class BaiduMapRidingDirectionsQuery(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    origin: str
    destination: str
    timestamp: int | None = None
    origin_uid: str | None = None
    destination_uid: str | None = None
    coord_type: Literal["bd09ll", "bd09mc", "gcj02", "wgs84"] = "bd09ll"
    ret_coordtype: Literal["bd09ll", "gcj02"] = "bd09ll"
    riding_type: Literal["0", "1"] = "0"
    road_prefer: Literal["0", "3"] = "0"
    output: Literal["json", "xml"] = "json"
    sn: str | None = None


class BaiduMapRidingDirectionsRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    query: BaiduMapRidingDirectionsQuery


class BaiduMapRouteMatrixQuery(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    origins: str
    destinations: str
    timestamp: int | None = None
    tactics: Literal["10", "11", "12", "13"] = "13"
    riding_type: Literal["0", "1"] = "0"
    coord_type: Literal["bd09ll", "bd09mc", "gcj02", "wgs84"] = "bd09ll"
    ret_straight_dist: Literal["0", "1"] = "0"
    output: Literal["json", "xml"] = "json"
    sn: str | None = None


class BaiduMapRouteMatrixRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    query: BaiduMapRouteMatrixQuery


class BaiduMapTransitDirectionsQuery(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    origin: str
    destination: str
    timestamp: int | None = None
    origin_uid: str | None = None
    destination_uid: str | None = None
    coord_type: Literal["bd09ll", "bd09mc", "gcj02", "wgs84"] = "bd09ll"
    ret_coordtype: Literal["bd09ll", "gcj02"] = "bd09ll"
    departure_date: str | None = None
    departure_time: str | None = None
    tactics_incity: Literal["0", "1", "2", "3", "4", "5"] = "0"
    tactics_intercity: Literal["0", "1", "2"] = "0"
    trans_type_intercity: Literal["0", "1", "2"] = "0"
    steps_info: Literal["0", "1"] = "0"
    output: Literal["json", "xml"] = "json"
    page_size: str = "10"
    page_index: str = "1"
    callback: str | None = None
    sn: str | None = None


class BaiduMapTransitDirectionsRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    query: BaiduMapTransitDirectionsQuery


class BaiduMapWalkingDirectionsQuery(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    origin: str
    destination: str
    timestamp: int | None = None
    origin_uid: str | None = None
    destination_uid: str | None = None
    coord_type: Literal["bd09ll", "bd09mc", "gcj02", "wgs84"] = "bd09ll"
    ret_coordtype: Literal["bd09ll", "gcj02"] = "bd09ll"
    steps_info: Literal["0", "1"] = "0"
    output: Literal["json", "xml"] = "json"
    sn: str | None = None


class BaiduMapWalkingDirectionsRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    query: BaiduMapWalkingDirectionsQuery


class BaiduMapNamespace:
    """Typed accessor for the `baidu_map` app. Reach it via `client.apps.baidu_map`."""

    def __init__(self, client: Keyhaven) -> None:
        self._client = client

    async def driving_directions(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: BaiduMapDrivingDirectionsRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Retrieves driving route plans between an origin and destination, with configurable strategies, waypoints, and vehicle types. Returns distance, duration, toll information, and step-by-step directions for the recommended or alternative routes. Use when an agent needs driving directions, estimated travel time, or route details between two locations.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "baidu_map.driving_directions", owner_id, args, account_id=account_id
        )

    async def riding_directions(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: BaiduMapRidingDirectionsRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Retrieves cycling routes between two coordinates, supporting both regular bike and electric bike modes. Returns distance, duration, and turn-by-turn directions optimized for cyclists. Use when an agent needs bike route information between two points.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "baidu_map.riding_directions", owner_id, args, account_id=account_id
        )

    async def route_matrix(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: BaiduMapRouteMatrixRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Calculates driving distance and estimated travel time between multiple origins and destinations in bulk, returning a matrix of results. Supports various driving strategies and optional straight-line distance. Use when an agent needs to compare distances or times across many origin-destination pairs, typically for logistics or delivery route optimization.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "baidu_map.route_matrix", owner_id, args, account_id=account_id
        )

    async def transit_directions(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: BaiduMapTransitDirectionsRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Retrieves public transit routes between two locations, supporting intra-city and inter-city travel with configurable departure dates, times, and route strategies. Returns multiple route options with transfers, walking segments, and estimated duration. Use when an agent needs bus, subway, or train directions between two points.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "baidu_map.transit_directions", owner_id, args, account_id=account_id
        )

    async def walking_directions(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: BaiduMapWalkingDirectionsRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Retrieves walking routes between an origin and destination, with optional step-by-step walking directions. Returns distance, estimated walking time, and turn-by-turn instructions. Use when an agent needs pedestrian route information between two locations.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "baidu_map.walking_directions", owner_id, args, account_id=account_id
        )
