# @generated by scripts/gen_sdk.py — DO NOT EDIT.

"""Typed SDK namespace for the `bigcommerce` app (generated)."""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

from pydantic import BaseModel, ConfigDict, Field

from keyhaven.sdk._constants import DEFAULT_ACCOUNT_ID

if TYPE_CHECKING:
    from keyhaven.sdk.client import Keyhaven


class BigcommerceCustomersListPath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    store_hash: str


class BigcommerceCustomersListQuery(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    page: int | None = None
    limit: int | None = None
    id_in: str | None = Field(default=None, alias="id:in")
    email_in: str | None = Field(default=None, alias="email:in")
    company_in: str | None = Field(default=None, alias="company:in")
    name_like: str | None = Field(default=None, alias="name:like")
    include: str | None = None
    sort: str | None = None


class BigcommerceCustomersListRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: BigcommerceCustomersListPath
    query: BigcommerceCustomersListQuery | None = None


class BigcommerceOrdersListPath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    store_hash: str


class BigcommerceOrdersListQuery(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    page: int | None = None
    limit: int | None = None
    status_id: int | None = None
    customer_id: int | None = None
    email: str | None = None
    min_date_created: str | None = None
    max_date_created: str | None = None
    sort: str | None = None


class BigcommerceOrdersListRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: BigcommerceOrdersListPath
    query: BigcommerceOrdersListQuery | None = None


class BigcommerceProductCreatePath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    store_hash: str


class BigcommerceProductCreateBody(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    name: str
    type_: str = Field(alias="type")
    weight: float
    price: float
    sku: str | None = None
    description: str | None = None
    categories: list[Any] | None = None
    brand_id: int | None = None
    inventory_level: int | None = None
    is_visible: bool | None = None


class BigcommerceProductCreateRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: BigcommerceProductCreatePath
    body: BigcommerceProductCreateBody


class BigcommerceProductGetPath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    store_hash: str
    product_id: int


class BigcommerceProductGetQuery(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    include: str | None = None


class BigcommerceProductGetRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: BigcommerceProductGetPath
    query: BigcommerceProductGetQuery | None = None


class BigcommerceProductUpdatePath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    store_hash: str
    product_id: int


class BigcommerceProductUpdateBody(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    name: str | None = None
    price: float | None = None
    sale_price: float | None = None
    sku: str | None = None
    description: str | None = None
    inventory_level: int | None = None
    is_visible: bool | None = None
    categories: list[Any] | None = None


class BigcommerceProductUpdateRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: BigcommerceProductUpdatePath
    body: BigcommerceProductUpdateBody = Field(default_factory=BigcommerceProductUpdateBody)


class BigcommerceProductsListPath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    store_hash: str


class BigcommerceProductsListQuery(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    page: int | None = None
    limit: int | None = None
    id: int | None = None
    sku: str | None = None
    name: str | None = None
    categories: str | None = None
    brand_id: int | None = None
    is_visible: bool | None = None
    include: str | None = None
    sort: str | None = None


class BigcommerceProductsListRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: BigcommerceProductsListPath
    query: BigcommerceProductsListQuery | None = None


class BigcommerceNamespace:
    """Typed accessor for the `bigcommerce` app. Reach it via `client.apps.bigcommerce`."""

    def __init__(self, client: Keyhaven) -> None:
        self._client = client

    async def customers_list(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: BigcommerceCustomersListRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Retrieves a paginated list of customers with filtering by ID, email, company, and name, with support for including related resources like addresses and custom attributes. Customer records contain personal identifiable information (PII) such as names, emails, and contact details. This is a read-only operation with no side effects. Use this function to find customers for marketing, support, or account management workflows.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "bigcommerce.customers_list", owner_id, args, account_id=account_id
        )

    async def orders_list(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: BigcommerceOrdersListRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Returns a paginated list of orders from the BigCommerce store with filtering by status, customer ID, customer email, and date range. Order data includes line items, totals, shipping details, and customer information including PII. This is a read-only operation with no side effects. Use this function to review order history, track fulfillment, analyze sales trends, or find specific orders for processing.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "bigcommerce.orders_list", owner_id, args, account_id=account_id
        )

    async def product_create(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: BigcommerceProductCreateRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Creates a new catalog product in the BigCommerce store with required fields (name, type, weight, price) and optional fields (SKU, description, categories, brand, inventory level, visibility). The product will appear on the storefront immediately if visibility is enabled, making it purchasable by customers. Use this function to add new inventory items to the online store from bulk imports, supplier feeds, or manual additions.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "bigcommerce.product_create", owner_id, args, account_id=account_id
        )

    async def product_get(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: BigcommerceProductGetRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Fetches detailed information about a single catalog product by its store hash and product ID, including price, inventory level, description, and optionally related resources like variants, images, and custom fields. This is a read-only operation with no side effects. Use this function to inspect a specific product's full data before making updates or for reporting purposes.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "bigcommerce.product_get", owner_id, args, account_id=account_id
        )

    async def product_update(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: BigcommerceProductUpdateRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Updates the fields of an existing catalog product, including price, sale price, SKU, description, inventory level, categories, and storefront visibility. Changes take effect immediately and affect what customers see and can purchase. Use this function to adjust pricing, correct product details, update stock levels, or change visibility settings in response to business needs.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "bigcommerce.product_update", owner_id, args, account_id=account_id
        )

    async def products_list(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: BigcommerceProductsListRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Retrieves a paginated list of catalog products from the BigCommerce store with extensive filtering by ID, SKU, name, category, brand, and storefront visibility. Supports sorting and inclusion of related resources such as variants, images, and custom fields. This is a read-only operation with no side effects. Use this function to browse the product catalog for inventory checks, pricing audits, or as a precursor to creating or updating products.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "bigcommerce.products_list", owner_id, args, account_id=account_id
        )
