# @generated by scripts/gen_sdk.py — DO NOT EDIT.

"""Typed SDK namespace for the `circle_so` app (generated)."""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

from pydantic import BaseModel, ConfigDict

from keyhaven.sdk._constants import DEFAULT_ACCOUNT_ID

if TYPE_CHECKING:
    from keyhaven.sdk.client import Keyhaven


class CircleSoCommunityMembersSearchBody(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    search_text: str | None = None
    per_page: int = 20
    status: str | None = None
    order: str | None = None
    exclude_empty_profiles: bool | None = None


class CircleSoCommunityMembersSearchRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    body: CircleSoCommunityMembersSearchBody | None = None


class CircleSoPostsListQuery(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    page: int = 1
    per_page: int = 30


class CircleSoPostsListRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    query: CircleSoPostsListQuery | None = None


class CircleSoPostsListBySpaceQuery(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    space_id: str
    page: int = 1
    per_page: int = 20
    status: str | None = None


class CircleSoPostsListBySpaceRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    query: CircleSoPostsListBySpaceQuery


class CircleSoNamespace:
    """Typed accessor for the `circle_so` app. Reach it via `client.apps.circle_so`."""

    def __init__(self, client: Keyhaven) -> None:
        self._client = client

    async def community_members_search(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: CircleSoCommunityMembersSearchRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Searches the community member directory by free text and optional filters (status, sort order, exclusion of empty profiles), returning matching member profiles with their details. Use this for member discovery, eligibility checks, or building member lists for targeted outreach. This is a query-only operation — it searches, reads, and returns data without creating or modifying any records.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "circle_so.community_members_search", owner_id, args, account_id=account_id
        )

    async def posts_list(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: CircleSoPostsListRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Retrieves a paginated list of all posts across every space in the Circle community, ordered by most recent first. Use this to get a cross-community overview of recent activity, support content audits, or seed moderation workflows. This is a read-only operation with no side effects on the data.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "circle_so.posts_list", owner_id, args, account_id=account_id
        )

    async def posts_list_by_space(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: CircleSoPostsListBySpaceRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Retrieves a paginated list of posts within a single specified space, with optional status filtering (published, draft, etc.). Use this when you need to scope operations to one space, such as reviewing draft content before publishing or auditing posts for a specific topic area. This is a read-only operation with no side effects on the data.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "circle_so.posts_list_by_space", owner_id, args, account_id=account_id
        )
