# @generated by scripts/gen_sdk.py — DO NOT EDIT.

"""Typed SDK namespace for the `datadog` app (generated)."""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

from pydantic import BaseModel, ConfigDict, Field

from keyhaven.sdk._constants import DEFAULT_ACCOUNT_ID

if TYPE_CHECKING:
    from keyhaven.sdk.client import Keyhaven


class DatadogDashboardsListQuery(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    filter_stale: bool | None = None
    count: int | None = None


class DatadogDashboardsListRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    query: DatadogDashboardsListQuery | None = None


class DatadogEventsListQuery(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    start: int
    end: int
    priority: str | None = None
    sources: str | None = None
    tags: str | None = None


class DatadogEventsListRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    query: DatadogEventsListQuery


class DatadogMetricsQueryQuery(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    from_: int = Field(alias="from")
    to: int
    query: str


class DatadogMetricsQueryRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    query: DatadogMetricsQueryQuery


class DatadogMetricsSubmitBody(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    series: list[Any]


class DatadogMetricsSubmitRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    body: DatadogMetricsSubmitBody


class DatadogMonitorCreateBody(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    type_: str = Field(alias="type")
    query: str
    name: str
    message: str
    tags: list[Any] | None = None
    options: dict[str, Any] | None = None


class DatadogMonitorCreateRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    body: DatadogMonitorCreateBody


class DatadogMonitorsListQuery(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    name: str | None = None
    tags: str | None = None
    monitor_tags: str | None = None
    group_states: str | None = None


class DatadogMonitorsListRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    query: DatadogMonitorsListQuery | None = None


class DatadogNamespace:
    """Typed accessor for the `datadog` app. Reach it via `client.apps.datadog`."""

    def __init__(self, client: Keyhaven) -> None:
        self._client = client

    async def dashboards_list(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: DatadogDashboardsListRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        List all dashboards in the Datadog account, with optional filtering for stale dashboards and count limits. Returns dashboard metadata including titles, authors, creation and modification timestamps, dashboard URLs, and dashboard types (custom/timeboard/screenboard). Use to discover existing dashboards, identify stale ones for cleanup, or find a specific dashboard by its attributes before viewing or modifying it.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "datadog.dashboards_list", owner_id, args, account_id=account_id
        )

    async def events_list(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: DatadogEventsListRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        List Datadog events within a specified time range, filterable by priority (normal/low), event sources, and tags. Events include deployments, monitor alerts, state changes, annotations, and API-tracked activities across your infrastructure. Use to review recent operational activity, correlate events with metric anomalies during incident investigation, or audit deployment and configuration change history.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "datadog.events_list", owner_id, args, account_id=account_id
        )

    async def metrics_query(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: DatadogMetricsQueryRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Query Datadog time series data over a specified time range using the Datadog metric query language, such as avg:system.cpu.user{*} by {host}. Returns aggregated data points, optionally grouped by tags or hosts, suitable for analysis, visualization, or alert evaluation. Use when you need to retrieve historical metrics for troubleshooting, build custom reports, or fetch data to feed into external analysis tools.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "datadog.metrics_query", owner_id, args, account_id=account_id
        )

    async def metrics_submit(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: DatadogMetricsSubmitRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Submit custom time series data points to Datadog with metric names, numeric values, timestamps, metric types (gauge/count/rate), and associated tags. Submitted data appears in Datadog dashboards, monitors, and alerts within seconds, enabling real-time observability. Use when you need to instrument custom application metrics, track business KPIs, or report infrastructure telemetry that is not captured by Datadog's built-in integrations.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "datadog.metrics_submit", owner_id, args, account_id=account_id
        )

    async def monitor_create(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: DatadogMonitorCreateRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Create a new monitor in Datadog with an alert condition query, notification message, monitor type (metric alert, service check, etc.), tags, and threshold options. The monitor immediately begins evaluating the defined condition and can trigger notifications, page on-call teams via PagerDuty, or notify Slack channels when breached. Use when you need to set up automated alerting for a specific metric, service health check, or anomaly detection scenario.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "datadog.monitor_create", owner_id, args, account_id=account_id
        )

    async def monitors_list(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: DatadogMonitorsListRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Retrieve all monitors configured in the Datadog account, filterable by name, tags, monitor tags, and group states such as alert, warn, or no data. Returns each monitor's definition, current status, notification settings, and configuration. Use to audit existing alerting rules, check which monitors are currently in alert or warning state, or find a specific monitor's ID for modification.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "datadog.monitors_list", owner_id, args, account_id=account_id
        )
