# @generated by scripts/gen_sdk.py — DO NOT EDIT.

"""Typed SDK namespace for the `drata` app (generated)."""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

from pydantic import BaseModel, ConfigDict

from keyhaven.sdk._constants import DEFAULT_ACCOUNT_ID

if TYPE_CHECKING:
    from keyhaven.sdk.client import Keyhaven


class DrataControlGetPath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    id: str


class DrataControlGetRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: DrataControlGetPath


class DrataControlsListQuery(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    page: int | None = None
    limit: int | None = None
    sort: str | None = None
    sortDir: str | None = None
    search: str | None = None


class DrataControlsListRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    query: DrataControlsListQuery | None = None


class DrataEventsListQuery(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    page: int | None = None
    limit: int | None = None
    sort: str | None = None
    sortDir: str | None = None
    search: str | None = None


class DrataEventsListRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    query: DrataEventsListQuery | None = None


class DrataEvidenceListQuery(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    page: int | None = None
    limit: int | None = None
    search: str | None = None


class DrataEvidenceListRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    query: DrataEvidenceListQuery | None = None


class DrataUsersListQuery(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    page: int | None = None
    limit: int | None = None
    sort: str | None = None
    sortDir: str | None = None


class DrataUsersListRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    query: DrataUsersListQuery | None = None


class DrataVendorsListQuery(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    page: int | None = None
    limit: int | None = None
    sort: str | None = None
    sortDir: str | None = None


class DrataVendorsListRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    query: DrataVendorsListQuery | None = None


class DrataNamespace:
    """Typed accessor for the `drata` app. Reach it via `client.apps.drata`."""

    def __init__(self, client: Keyhaven) -> None:
        self._client = client

    async def control_get(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: DrataControlGetRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Retrieve a single compliance control by its unique identifier, including its description, requirements, and current implementation status. Use this to inspect a specific control's details before mapping evidence or checking compliance posture.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "drata.control_get", owner_id, args, account_id=account_id
        )

    async def controls_list(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: DrataControlsListRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Find compliance controls by search terms and filters with pagination and sorting. Controls are the security and compliance requirements defined in the Drata framework. Use this to discover which controls exist before retrieving their full details or associated evidence.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "drata.controls_list", owner_id, args, account_id=account_id
        )

    async def events_list(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: DrataEventsListRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Find compliance and audit events with pagination, sorting, and search filtering. Events track changes, activities, and alerts within the Drata platform (e.g. control status changes, evidence uploads, test failures). Use this to review the audit trail or investigate recent compliance activity.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "drata.events_list", owner_id, args, account_id=account_id
        )

    async def evidence_list(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: DrataEvidenceListRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        List evidence items in the evidence library with pagination and search filtering. Evidence items are files and documentation used to prove compliance with controls (e.g. screenshots, policies, test results). Use this to browse available evidence before associating it with a control or identifying gaps for an audit.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "drata.evidence_list", owner_id, args, account_id=account_id
        )

    async def users_list(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: DrataUsersListRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        List all users and their roles in the Drata organisation with pagination and sorting. Returns user names, email addresses, and assigned roles that define access to the compliance platform. Use this to find a user's ID or verify their role before performing administrative actions.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute("drata.users_list", owner_id, args, account_id=account_id)

    async def vendors_list(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: DrataVendorsListRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        List all third-party vendors tracked in the Drata organisation with pagination and sorting. Vendors are external service providers being monitored for compliance risk. Use this to review the vendor roster or find a specific vendor before inspecting their risk assessment or evidence.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "drata.vendors_list", owner_id, args, account_id=account_id
        )
