# @generated by scripts/gen_sdk.py — DO NOT EDIT.

"""Typed SDK namespace for the `eventbrite` app (generated)."""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

from pydantic import BaseModel, ConfigDict

from keyhaven.sdk._constants import DEFAULT_ACCOUNT_ID

if TYPE_CHECKING:
    from keyhaven.sdk.client import Keyhaven


class EventbriteEventAttendeesListPath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    event_id: str


class EventbriteEventAttendeesListQuery(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    status: str | None = None
    page: int = 1


class EventbriteEventAttendeesListRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: EventbriteEventAttendeesListPath
    query: EventbriteEventAttendeesListQuery | None = None


class EventbriteEventCreateBody(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    event: dict[str, Any]


class EventbriteEventCreateRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    body: EventbriteEventCreateBody


class EventbriteEventGetPath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    event_id: str


class EventbriteEventGetRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: EventbriteEventGetPath


class EventbriteEventOrdersListPath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    event_id: str


class EventbriteEventOrdersListQuery(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    status: str | None = None
    expand: str | None = None
    page: int = 1


class EventbriteEventOrdersListRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: EventbriteEventOrdersListPath
    query: EventbriteEventOrdersListQuery | None = None


class EventbriteOrganizationEventsListPath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    organization_id: str


class EventbriteOrganizationEventsListQuery(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    status: str | None = None
    order_by: str | None = None
    page: int = 1


class EventbriteOrganizationEventsListRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: EventbriteOrganizationEventsListPath
    query: EventbriteOrganizationEventsListQuery | None = None


class EventbriteUsersMeEventsListQuery(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    status: str | None = None
    order_by: str | None = None
    page: int = 1


class EventbriteUsersMeEventsListRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    query: EventbriteUsersMeEventsListQuery | None = None


class EventbriteNamespace:
    """Typed accessor for the `eventbrite` app. Reach it via `client.apps.eventbrite`."""

    def __init__(self, client: Keyhaven) -> None:
        self._client = client

    async def event_attendees_list(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: EventbriteEventAttendeesListRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Lists attendees registered for a specific Eventbrite event, filterable by status (attending, checked_in, not_attending, unanswered) with pagination. This returns attendee personal information such as names and email addresses. Use it when an agent needs to export attendee data or check registration numbers, but note it exposes PII.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "eventbrite.event_attendees_list", owner_id, args, account_id=account_id
        )

    async def event_create(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: EventbriteEventCreateRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Creates a new draft event on behalf of the authenticated Eventbrite user, with specified name, description, start/end times, currency, capacity, and listing preference. The event starts as a draft and is not visible to the public until explicitly published. Use it when an agent needs to set up an event structure that a human can later review and publish.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "eventbrite.event_create", owner_id, args, account_id=account_id
        )

    async def event_get(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: EventbriteEventGetRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Retrieves the complete details of a single Eventbrite event by its numeric ID, including name, description, dates, venue, ticket classes, and organizer settings. This read-only operation provides everything needed to display or analyze an event. Use it when an agent needs to inspect an event's full configuration or preview its data.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "eventbrite.event_get", owner_id, args, account_id=account_id
        )

    async def event_orders_list(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: EventbriteEventOrdersListRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Returns orders placed against a specific Eventbrite event, filterable by status (placed, completed, canceled, etc.) with optional attendee expansion. This includes financial details such as order totals, fees, and purchaser information. Use it when an agent needs to review sales performance or reconcile event transactions.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "eventbrite.event_orders_list", owner_id, args, account_id=account_id
        )

    async def organization_events_list(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: EventbriteOrganizationEventsListRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Fetches all events managed by a specific Eventbrite organization, with optional status filter, sorting, and pagination. This returns event metadata such as titles, dates, statuses, and ticket availability for organizational planning. Use it when an agent needs to audit or analyze events across an organization.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "eventbrite.organization_events_list", owner_id, args, account_id=account_id
        )

    async def users_me_events_list(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: EventbriteUsersMeEventsListRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Returns a paginated list of events owned by the authenticated Eventbrite user, filterable by status (live, draft, canceled, etc.) and sortable by start date or creation date. This provides event summaries including names, dates, statuses, and URLs. Use it when an agent needs to browse the user's personal event portfolio.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "eventbrite.users_me_events_list", owner_id, args, account_id=account_id
        )
