# @generated by scripts/gen_sdk.py — DO NOT EDIT.

"""Typed SDK namespace for the `figma` app (generated)."""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

from pydantic import BaseModel, ConfigDict

from keyhaven.sdk._constants import DEFAULT_ACCOUNT_ID

if TYPE_CHECKING:
    from keyhaven.sdk.client import Keyhaven


class FigmaGetCommentsPath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    file_key: str


class FigmaGetCommentsRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: FigmaGetCommentsPath


class FigmaGetComponentPath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    file_key: str


class FigmaGetComponentQuery(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    ids: str


class FigmaGetComponentRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: FigmaGetComponentPath
    query: FigmaGetComponentQuery


class FigmaGetFilePath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    file_key: str


class FigmaGetFileQuery(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    version: str | None = None
    ids: str | None = None
    depth: int | None = None
    geometry: str | None = None
    plugin_data: str | None = None
    branch_data: bool | None = None


class FigmaGetFileRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: FigmaGetFilePath
    query: FigmaGetFileQuery | None = None


class FigmaGetFileComponentSetsPath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    file_key: str


class FigmaGetFileComponentSetsRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: FigmaGetFileComponentSetsPath


class FigmaGetFileNodesPath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    file_key: str


class FigmaGetFileNodesQuery(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    ids: str


class FigmaGetFileNodesRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: FigmaGetFileNodesPath
    query: FigmaGetFileNodesQuery


class FigmaGetFileVersionsPath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    file_key: str


class FigmaGetFileVersionsRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: FigmaGetFileVersionsPath


class FigmaGetImagePath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    file_key: str


class FigmaGetImageQuery(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    ids: str
    scale: float | None = None
    format: str | None = None


class FigmaGetImageRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: FigmaGetImagePath
    query: FigmaGetImageQuery


class FigmaGetImageFillsPath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    file_key: str


class FigmaGetImageFillsRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: FigmaGetImageFillsPath


class FigmaGetProjectFilesPath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    project_id: str


class FigmaGetProjectFilesRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: FigmaGetProjectFilesPath


class FigmaGetStylePath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    file_key: str


class FigmaGetStyleQuery(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    ids: str


class FigmaGetStyleRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: FigmaGetStylePath
    query: FigmaGetStyleQuery


class FigmaGetTeamProjectsPath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    team_id: str


class FigmaGetTeamProjectsRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: FigmaGetTeamProjectsPath


class FigmaNamespace:
    """Typed accessor for the `figma` app. Reach it via `client.apps.figma`."""

    def __init__(self, client: Keyhaven) -> None:
        self._client = client

    async def get_comments(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: FigmaGetCommentsRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Retrieves all comments on a Figma file, including the comment text, author name, and the node the comment is attached to. Comments are read-only visible on the file. Use this to review design feedback or to extract discussion context before making design changes.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "figma.get_comments", owner_id, args, account_id=account_id
        )

    async def get_component(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: FigmaGetComponentRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Retrieves a specific reusable component node from a Figma file by its node ID. Components are reusable design elements that can be instantiated multiple times across a file or library. Returns the component's properties, overrides, and metadata. Use this to inspect reusable UI elements from a design system.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "figma.get_component", owner_id, args, account_id=account_id
        )

    async def get_file(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: FigmaGetFileRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Retrieves the full JSON document tree of a Figma file by its file key, including all frames, layers, and their properties. Optionally filter by version, node IDs, or depth. Use this to inspect the design structure, extract metadata, or feed design data into downstream tools.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute("figma.get_file", owner_id, args, account_id=account_id)

    async def get_file_component_sets(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: FigmaGetFileComponentSetsRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Lists all component sets (groups of related component variants) in a Figma file. Component sets are the source of truth for design system components with multiple states or variants. Use this to understand the design system structure or to locate specific component sets for export or inspection.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "figma.get_file_component_sets", owner_id, args, account_id=account_id
        )

    async def get_file_nodes(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: FigmaGetFileNodesRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Retrieves specific nodes from a Figma file by their node IDs, returning their full document subtrees. More efficient than GET_FILE when you only need a few specific frames or components. Use this to inspect selected parts of a design without fetching the entire document.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "figma.get_file_nodes", owner_id, args, account_id=account_id
        )

    async def get_file_versions(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: FigmaGetFileVersionsRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Returns the version history of a Figma file, including who saved each version, when, and the version label. Use this to track changes over time or to identify a specific version ID for use with GET_FILE's version parameter.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "figma.get_file_versions", owner_id, args, account_id=account_id
        )

    async def get_image(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: FigmaGetImageRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Renders specified nodes from a Figma file as image files (PNG, JPG, or SVG) at a chosen scale factor. Returns a mapping of node IDs to image download URLs. Use this to export design assets for use in presentations, documentation, or front-end development.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute("figma.get_image", owner_id, args, account_id=account_id)

    async def get_image_fills(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: FigmaGetImageFillsRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Returns download links for all images used as fills (background, pattern fills) in a Figma document. Does not include strokes or exportable assets. Use this to extract reference images and embedded graphics from a design file for reuse or archival.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "figma.get_image_fills", owner_id, args, account_id=account_id
        )

    async def get_project_files(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: FigmaGetProjectFilesRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Lists all Figma files within a specific project, returning each file's name, key, and last modified date. Use this to discover available design files in a project and obtain their file keys for subsequent GET_FILE or GET_IMAGE calls.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "figma.get_project_files", owner_id, args, account_id=account_id
        )

    async def get_style(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: FigmaGetStyleRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Retrieves a specific style node (e.g., text style, colour style, effect style, or grid style) from a Figma file by its node ID. Returns the full style definition including all properties and values. Use this to inspect or extract design tokens from a design system or component library.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute("figma.get_style", owner_id, args, account_id=account_id)

    async def get_team_projects(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: FigmaGetTeamProjectsRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Lists all projects within a Figma team, returning each project's ID, name, and metadata. Use this to navigate the team's project hierarchy and find a project_id for the GET_PROJECT_FILES call.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "figma.get_team_projects", owner_id, args, account_id=account_id
        )
