# @generated by scripts/gen_sdk.py — DO NOT EDIT.

"""Typed SDK namespace for the `front` app (generated)."""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

from pydantic import BaseModel, ConfigDict, Field

from keyhaven.sdk._constants import DEFAULT_ACCOUNT_ID

if TYPE_CHECKING:
    from keyhaven.sdk.client import Keyhaven


class FrontContactCreateBody(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    name: str | None = None
    description: str | None = None
    handles: list[Any]
    group_names: list[Any] | None = None
    links: list[Any] | None = None


class FrontContactCreateRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    body: FrontContactCreateBody


class FrontContactsListQuery(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    q: str | None = None
    limit: int = 50
    page_token: str | None = None


class FrontContactsListRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    query: FrontContactsListQuery | None = None


class FrontConversationGetPath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    conversation_id: str


class FrontConversationGetRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: FrontConversationGetPath


class FrontConversationReplyPath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    conversation_id: str


class FrontConversationReplyBody(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    to: list[Any] | None = None
    cc: list[Any] | None = None
    body: str
    subject: str | None = None
    channel_id: str | None = None
    author_id: str | None = None
    options: dict[str, Any] | None = None


class FrontConversationReplyRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: FrontConversationReplyPath
    body: FrontConversationReplyBody


class FrontConversationUpdatePath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    conversation_id: str


class FrontConversationUpdateBody(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    assignee_id: str | None = None
    status: str | None = None
    tags: list[Any] | None = None
    inbox_id: str | None = None


class FrontConversationUpdateRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: FrontConversationUpdatePath
    body: FrontConversationUpdateBody = Field(default_factory=FrontConversationUpdateBody)


class FrontConversationsListQuery(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    q: dict[str, Any] | None = None
    limit: int = 50
    page_token: str | None = None
    sort_by: str | None = None
    sort_order: str = "desc"


class FrontConversationsListRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    query: FrontConversationsListQuery | None = None


class FrontNamespace:
    """Typed accessor for the `front` app. Reach it via `client.apps.front`."""

    def __init__(self, client: Keyhaven) -> None:
        self._client = client

    async def contact_create(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: FrontContactCreateRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Creates a new contact in Front with one or more channel handles (email, phone, etc.), an optional display name, description, group memberships, and external links. If the specified group names do not exist, they are created automatically. Use this to register new external contacts discovered through other channels or imports. The contact becomes immediately available for conversation routing.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "front.contact_create", owner_id, args, account_id=account_id
        )

    async def contacts_list(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: FrontContactsListRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Lists all contacts known to Front with an optional free-text search query that matches name, description, handles, and group names. Results are paginated and each contact includes its ID, name, handles, groups, and associated links. Use this to find a contact by name or handle before creating a conversation or adding them to a contact group.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "front.contacts_list", owner_id, args, account_id=account_id
        )

    async def conversation_get(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: FrontConversationGetRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Retrieves a single conversation by its unique Front ID (e.g. cnv_abc123), including its full metadata: status, assignee, inbox, tags, participants, message count, and custom fields. Does not return the full message body. Use this when the agent needs context about a specific conversation before replying or updating it.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "front.conversation_get", owner_id, args, account_id=account_id
        )

    async def conversation_reply(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: FrontConversationReplyRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Sends an outbound reply message to an existing conversation, with support for CC recipients, Markdown body, file attachments, and optional post-reply actions such as archiving or marking as read. The message is sent via the conversation's assigned channel (email, chat, etc.) and reaches all external recipients. Use this to respond to customer inquiries from automated workflows. This action is immediately visible to all conversation participants.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "front.conversation_reply", owner_id, args, account_id=account_id
        )

    async def conversation_update(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: FrontConversationUpdateRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Updates the properties of an existing conversation: assign or unassign a teammate, change status (archive, trash, spam, open), replace tags, or move to a different inbox. Archiving removes the conversation from the main inbox view but keeps it searchable; trashing moves it to the trash. Use this to triage conversations at scale. Some status changes (e.g. archive, trash) are reversible but affect team workflow.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "front.conversation_update", owner_id, args, account_id=account_id
        )

    async def conversations_list(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: FrontConversationsListRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Lists conversations in Front in reverse chronological order (most recently updated first), with optional search query filtering by status, assignee, inbox, or tag. Results are paginated and each conversation includes its ID, subject, status, assignee, and last message preview. Use this to discover which conversations need attention before replying, reassigning, or archiving.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "front.conversations_list", owner_id, args, account_id=account_id
        )
