# @generated by scripts/gen_sdk.py — DO NOT EDIT.

"""Typed SDK namespace for the `goco` app (generated)."""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

from pydantic import BaseModel, ConfigDict, Field

from keyhaven.sdk._constants import DEFAULT_ACCOUNT_ID

if TYPE_CHECKING:
    from keyhaven.sdk.client import Keyhaven


class GocoGetCompaniesHeader(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    Content_Type: str = Field(default="application/json", alias="Content-Type")


class GocoGetCompaniesRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    header: GocoGetCompaniesHeader = Field(default_factory=GocoGetCompaniesHeader)


class GocoGetCustomFieldsPath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    companyUrlName: str


class GocoGetCustomFieldsHeader(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    Content_Type: str = Field(default="application/json", alias="Content-Type")


class GocoGetCustomFieldsRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: GocoGetCustomFieldsPath
    header: GocoGetCustomFieldsHeader = Field(default_factory=GocoGetCustomFieldsHeader)


class GocoGetDepartmentsPath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    companyUrlName: str


class GocoGetDepartmentsHeader(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    Content_Type: str = Field(default="application/json", alias="Content-Type")


class GocoGetDepartmentsRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: GocoGetDepartmentsPath
    header: GocoGetDepartmentsHeader = Field(default_factory=GocoGetDepartmentsHeader)


class GocoGetJobTitlesPath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    companyUrlName: str


class GocoGetJobTitlesHeader(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    Content_Type: str = Field(default="application/json", alias="Content-Type")


class GocoGetJobTitlesRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: GocoGetJobTitlesPath
    header: GocoGetJobTitlesHeader = Field(default_factory=GocoGetJobTitlesHeader)


class GocoGetLocationsPath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    companyUrlName: str


class GocoGetLocationsHeader(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    Content_Type: str = Field(default="application/json", alias="Content-Type")


class GocoGetLocationsRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: GocoGetLocationsPath
    header: GocoGetLocationsHeader = Field(default_factory=GocoGetLocationsHeader)


class GocoNamespace:
    """Typed accessor for the `goco` app. Reach it via `client.apps.goco`."""

    def __init__(self, client: Keyhaven) -> None:
        self._client = client

    async def get_companies(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: GocoGetCompaniesRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Fetches all companies within the GoCo HR platform that are accessible with the provided API credentials, including each company's name, URL identifier, and configuration details. Use this to discover company IDs and URL names before querying company-specific resources like departments, locations, or job titles. This is the top-level entry point for navigating the GoCo API.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "goco.get_companies", owner_id, args, account_id=account_id
        )

    async def get_custom_fields(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: GocoGetCustomFieldsRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Retrieves the custom field definitions configured for a specific company in GoCo. Custom fields store additional HR data beyond the standard fields, such as employee-specific attributes or company metadata. Use this to understand what extra data points are tracked before retrieving employee records or updating custom field values.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "goco.get_custom_fields", owner_id, args, account_id=account_id
        )

    async def get_departments(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: GocoGetDepartmentsRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Fetches all departments defined within a specific company in GoCo. Departments organize employees by functional area (e.g. Engineering, Sales, HR). Use this to get department names and identifiers for filtering employee data, generating organizational charts, or assigning new hires to the correct department.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "goco.get_departments", owner_id, args, account_id=account_id
        )

    async def get_job_titles(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: GocoGetJobTitlesRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Retrieves all job titles configured for a specific company in GoCo. Job titles define the standardized roles and positions within the organization. Use this to get the list of available titles before assigning roles to employees or filtering workforce data by position.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "goco.get_job_titles", owner_id, args, account_id=account_id
        )

    async def get_locations(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: GocoGetLocationsRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Fetches all physical office or work locations configured for a specific company in GoCo. Locations include address, contact information, and metadata for each site. Use this to discover where employees are based, filter workforce data by location, or manage location-specific HR policies and compliance requirements.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "goco.get_locations", owner_id, args, account_id=account_id
        )
