# @generated by scripts/gen_sdk.py — DO NOT EDIT.

"""Typed SDK namespace for the `gong` app (generated)."""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

from pydantic import BaseModel, ConfigDict

from keyhaven.sdk._constants import DEFAULT_ACCOUNT_ID

if TYPE_CHECKING:
    from keyhaven.sdk.client import Keyhaven


class GongCallGetBody(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    filter: dict[str, Any]


class GongCallGetRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    body: GongCallGetBody


class GongCallTranscriptBody(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    filter: dict[str, Any]


class GongCallTranscriptRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    body: GongCallTranscriptBody


class GongCallsListBody(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    filter: dict[str, Any]
    contentSelector: dict[str, Any] | None = None


class GongCallsListRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    body: GongCallsListBody


class GongDealsListBody(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    filter: dict[str, Any]


class GongDealsListRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    body: GongDealsListBody


class GongLibraryFoldersListQuery(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    parentFolderId: str | None = None


class GongLibraryFoldersListRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    query: GongLibraryFoldersListQuery | None = None


class GongUsersListQuery(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    fields: str | None = None


class GongUsersListRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    query: GongUsersListQuery | None = None


class GongNamespace:
    """Typed accessor for the `gong` app. Reach it via `client.apps.gong`."""

    def __init__(self, client: Keyhaven) -> None:
        self._client = client

    async def call_get(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: GongCallGetRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Retrieves full metadata for a single Gong call by its call ID, including participants, duration, topics, trackers, and key moments. Does not return the transcript or recording. Use this when the agent already knows the call ID (e.g. from a search result) and needs the structured metadata for analysis or reporting.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute("gong.call_get", owner_id, args, account_id=account_id)

    async def call_transcript(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: GongCallTranscriptRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Fetches the full conversation transcript of one or more Gong calls, with speaker turns, timestamps, and per-speaker attribution. Transcripts contain the verbatim spoken words and can reveal customer sentiment, objections, and competitive mentions. Use this when deep analysis of a call's content is needed. Transcripts may contain sensitive business information and should be handled with care.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "gong.call_transcript", owner_id, args, account_id=account_id
        )

    async def calls_list(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: GongCallsListRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Searches for recorded Gong calls within a date range using extensive filters: time window, specific call IDs, participants, related deals, or accounts. Returns metadata for each matching call including parties, topics, and tracker results (depending on the content selector). The agent should use this before fetching a specific transcript or when building a report of sales activity.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute("gong.calls_list", owner_id, args, account_id=account_id)

    async def deals_list(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: GongDealsListRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Returns CRM deal data visible to Gong, filtered by update date, deal IDs, account IDs, owner, stage, or status (open/won/lost). Each deal includes its pipeline stage, deal amount, owner, and custom fields. Use this to analyze sales pipeline health, correlate deal progress with call activity, or identify deals that need attention.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute("gong.deals_list", owner_id, args, account_id=account_id)

    async def library_folders_list(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: GongLibraryFoldersListRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Lists the top-level or nested library folders that organize recorded Gong calls. Each folder has an ID, name, and parent reference. Use this to browse the call library structure, for example before navigating to a specific folder to list its calls.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "gong.library_folders_list", owner_id, args, account_id=account_id
        )

    async def users_list(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: GongUsersListRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Returns the list of all Gong users in the company with their user ID, email, first/last name, role, and account settings. Use this to discover who has access to Gong, resolve user IDs for other API calls (such as filtering calls by participant), and map Gong users to your internal directory.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute("gong.users_list", owner_id, args, account_id=account_id)
