# @generated by scripts/gen_sdk.py — DO NOT EDIT.

"""Typed SDK namespace for the `google_docs` app (generated)."""

from __future__ import annotations

from typing import TYPE_CHECKING, Any, Literal

from pydantic import BaseModel, ConfigDict, Field

from keyhaven.sdk._constants import DEFAULT_ACCOUNT_ID

if TYPE_CHECKING:
    from keyhaven.sdk.client import Keyhaven


class GoogleDocsDocumentsCreateBody(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    title: str


class GoogleDocsDocumentsCreateRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    body: GoogleDocsDocumentsCreateBody


class GoogleDocsDocumentsGetPath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    documentId: str


class GoogleDocsDocumentsGetQuery(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    suggestionsViewMode: Literal[
        "DEFAULT_FOR_CURRENT_ACCESS",
        "SUGGESTIONS_INLINE",
        "PREVIEW_SUGGESTIONS_ACCEPTED",
        "PREVIEW_WITHOUT_SUGGESTIONS",
    ] = "DEFAULT_FOR_CURRENT_ACCESS"
    includeTabsContent: bool = False


class GoogleDocsDocumentsGetRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: GoogleDocsDocumentsGetPath
    query: GoogleDocsDocumentsGetQuery = Field(default_factory=GoogleDocsDocumentsGetQuery)


class GoogleDocsDocumentsUpdatePath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    documentId: str


class GoogleDocsDocumentsUpdateBody(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    requests: list[Any]


class GoogleDocsDocumentsUpdateRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: GoogleDocsDocumentsUpdatePath
    body: GoogleDocsDocumentsUpdateBody


class GoogleDocsNamespace:
    """Typed accessor for the `google_docs` app. Reach it via `client.apps.google_docs`."""

    def __init__(self, client: Keyhaven) -> None:
        self._client = client

    async def documents_create(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: GoogleDocsDocumentsCreateRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Creates a new blank Google Doc with the specified title via the Google Docs API. The document is created in the authenticated user's Google Drive and is initially empty with no content. Use this as the first step when you need to generate a document from scratch, then populate it with content using the batchUpdate endpoint.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "google_docs.documents_create", owner_id, args, account_id=account_id
        )

    async def documents_get(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: GoogleDocsDocumentsGetRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Retrieves the full content and structure of a Google Doc by its documentId, including body text, headers, footers, and suggestions. Supports different suggestion view modes (inline, accepted preview, or without suggestions) and optional tab content inclusion. No data is modified — this is a pure read operation. Use this to read a document's content for summarization, analysis, or as context before making targeted updates.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "google_docs.documents_get", owner_id, args, account_id=account_id
        )

    async def documents_update(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: GoogleDocsDocumentsUpdateRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Applies a batch of modification requests to an existing Google Doc, identified by its documentId. Currently supports inserting text at a specified location (index) within the document body, headers, footers, or tabs. The changes are applied immediately and persist in the document, visible to all collaborators. Use this to write content into a document after creating it, or to modify an existing document that the user has provided access to.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "google_docs.documents_update", owner_id, args, account_id=account_id
        )
