# @generated by scripts/gen_sdk.py — DO NOT EDIT.

"""Typed SDK namespace for the `grafana` app (generated)."""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

from pydantic import BaseModel, ConfigDict, Field

from keyhaven.sdk._constants import DEFAULT_ACCOUNT_ID

if TYPE_CHECKING:
    from keyhaven.sdk.client import Keyhaven


class GrafanaAnnotationsListQuery(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    from_: int | None = Field(default=None, alias="from")
    to: int | None = None
    limit: int | None = None
    alertId: str | None = None
    dashboardId: int | None = None
    panelId: int | None = None
    tags: str | None = None
    type_: str | None = Field(default=None, alias="type")


class GrafanaAnnotationsListRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    query: GrafanaAnnotationsListQuery | None = None


class GrafanaDashboardCreateUpdateBody(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    dashboard: dict[str, Any]
    folderId: int | None = None
    folderUid: str | None = None
    overwrite: bool | None = None
    message: str | None = None


class GrafanaDashboardCreateUpdateRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    body: GrafanaDashboardCreateUpdateBody


class GrafanaDashboardGetPath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    uid: str


class GrafanaDashboardGetRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: GrafanaDashboardGetPath


class GrafanaDashboardsListQuery(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    query: str | None = None
    folderIds: str | None = None
    tag: str | None = None
    type_: str | None = Field(default=None, alias="type")
    limit: int | None = None
    page: int | None = None


class GrafanaDashboardsListRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    query: GrafanaDashboardsListQuery | None = None


class GrafanaDatasourceCreateBody(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    name: str
    type_: str = Field(alias="type")
    url: str
    access: str | None = None
    isDefault: bool | None = None
    jsonData: dict[str, Any] | None = None
    secureJsonData: dict[str, Any] | None = None


class GrafanaDatasourceCreateRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    body: GrafanaDatasourceCreateBody


class GrafanaDatasourcesListRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)
    pass


class GrafanaNamespace:
    """Typed accessor for the `grafana` app. Reach it via `client.apps.grafana`."""

    def __init__(self, client: Keyhaven) -> None:
        self._client = client

    async def annotations_list(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: GrafanaAnnotationsListRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Returns Grafana annotations (events overlaid on graphs) within an optional time range, with filters by alert ID, dashboard ID, panel ID, tags, and type (alert or annotation). Use this to audit triggered alerts, correlate annotation events with dashboard data, or fetch event history for post-mortem analysis.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "grafana.annotations_list", owner_id, args, account_id=account_id
        )

    async def dashboard_create_update(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: GrafanaDashboardCreateUpdateRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Creates a new dashboard or overwrites an existing one if the same UID is provided. Accepts a full dashboard model with panels, datasource queries, variables, and time settings. Set overwrite to true to replace an existing dashboard with the same UID. Changes are versioned in Grafana's dashboard history. Use this to provision dashboards programmatically, sync from external tools, or update panel configurations.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "grafana.dashboard_create_update", owner_id, args, account_id=account_id
        )

    async def dashboard_get(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: GrafanaDashboardGetRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Retrieves the full dashboard definition by its unique UID, including panels, layout, queries, datasource references, and templating configuration. Use this when the agent needs to inspect, duplicate, or report on a specific dashboard's structure. Does not include live data from the datasources.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "grafana.dashboard_get", owner_id, args, account_id=account_id
        )

    async def dashboards_list(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: GrafanaDashboardsListRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Searches and lists Grafana dashboards and folders, with optional filters by title search term, folder IDs, tags, and resource type (dashboard or folder). Results are paginated and include each item's UID, title, folder, tags, and URL. Use this to discover dashboards by topic or tag before reading or editing one.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "grafana.dashboards_list", owner_id, args, account_id=account_id
        )

    async def datasource_create(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: GrafanaDatasourceCreateRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Adds a new data source configuration to Grafana with a name, type plugin ID, backend URL, access method, and optional additional configuration (JSON data) and secure credentials (access keys, passwords, TLS certs). The new datasource becomes immediately available for queries. Use this to connect Grafana to new monitoring backends. Secure credentials are stored encrypted.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "grafana.datasource_create", owner_id, args, account_id=account_id
        )

    async def datasources_list(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: GrafanaDatasourcesListRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Returns a list of all configured data sources in Grafana, including their type (Prometheus, InfluxDB, etc.), URL, access mode, and whether they are the default. Does not expose sensitive credentials. Use this to discover available backends before creating dashboards or queries.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "grafana.datasources_list", owner_id, args, account_id=account_id
        )
