# @generated by scripts/gen_sdk.py — DO NOT EDIT.

"""Typed SDK namespace for the `gusto` app (generated)."""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

from pydantic import BaseModel, ConfigDict, Field

from keyhaven.sdk._constants import DEFAULT_ACCOUNT_ID

if TYPE_CHECKING:
    from keyhaven.sdk.client import Keyhaven


class GustoCompaniesListHeader(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    X_Gusto_API_Version: str = Field(default="2024-04-01", alias="X-Gusto-API-Version")


class GustoCompaniesListRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    header: GustoCompaniesListHeader | None = None


class GustoCompanyGetPath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    company_id: str


class GustoCompanyGetHeader(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    X_Gusto_API_Version: str = Field(default="2024-04-01", alias="X-Gusto-API-Version")


class GustoCompanyGetRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: GustoCompanyGetPath
    header: GustoCompanyGetHeader | None = None


class GustoEmployeeCreatePath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    company_id: str


class GustoEmployeeCreateHeader(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    X_Gusto_API_Version: str = Field(default="2024-04-01", alias="X-Gusto-API-Version")


class GustoEmployeeCreateBody(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    first_name: str
    last_name: str
    middle_initial: str | None = None
    email: str | None = None
    work_email: str | None = None
    date_of_birth: str | None = None
    ssn: str | None = None
    preferred_first_name: str | None = None
    self_onboarding: bool | None = None


class GustoEmployeeCreateRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: GustoEmployeeCreatePath
    header: GustoEmployeeCreateHeader | None = None
    body: GustoEmployeeCreateBody


class GustoEmployeeGetPath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    employee_id: str


class GustoEmployeeGetHeader(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    X_Gusto_API_Version: str = Field(default="2024-04-01", alias="X-Gusto-API-Version")


class GustoEmployeeGetRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: GustoEmployeeGetPath
    header: GustoEmployeeGetHeader | None = None


class GustoEmployeesListPath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    company_id: str


class GustoEmployeesListQuery(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    page: int | None = None
    per: int | None = None
    terminated: bool | None = None


class GustoEmployeesListHeader(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    X_Gusto_API_Version: str = Field(default="2024-04-01", alias="X-Gusto-API-Version")


class GustoEmployeesListRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: GustoEmployeesListPath
    query: GustoEmployeesListQuery | None = None
    header: GustoEmployeesListHeader | None = None


class GustoPayrollsListPath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    company_id: str


class GustoPayrollsListQuery(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    start_date: str | None = None
    end_date: str | None = None
    processing_types: str | None = None


class GustoPayrollsListHeader(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    X_Gusto_API_Version: str = Field(default="2024-04-01", alias="X-Gusto-API-Version")


class GustoPayrollsListRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: GustoPayrollsListPath
    query: GustoPayrollsListQuery | None = None
    header: GustoPayrollsListHeader | None = None


class GustoNamespace:
    """Typed accessor for the `gusto` app. Reach it via `client.apps.gusto`."""

    def __init__(self, client: Keyhaven) -> None:
        self._client = client

    async def companies_list(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: GustoCompaniesListRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Returns a list of all Gusto companies that the authenticated user has access to, including details such as company name, legal name, and onboarding status. Use this to discover which company accounts are available before operating on a specific company.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "gusto.companies_list", owner_id, args, account_id=account_id
        )

    async def company_get(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: GustoCompanyGetRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Retrieves detailed information about a single Gusto company identified by its UUID, including legal name, address, pay schedule, and account settings. Use this when you need specific company-level configuration data.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "gusto.company_get", owner_id, args, account_id=account_id
        )

    async def employee_create(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: GustoEmployeeCreateRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Adds a new employee record to a Gusto company with legal name, contact information, Social Security Number, and date of birth. Can optionally trigger a self-onboarding email to the employee. This creates a formal employment record tied to payroll and tax compliance. Use this to onboard new hires.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "gusto.employee_create", owner_id, args, account_id=account_id
        )

    async def employee_get(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: GustoEmployeeGetRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Fetches the full profile of a single employee by their UUID, including personal details, job title, department, and compensation information. This accesses sensitive HR and payroll data. Use this to review or verify a specific employee's records.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "gusto.employee_get", owner_id, args, account_id=account_id
        )

    async def employees_list(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: GustoEmployeesListRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Lists all employees for a specified company across onboarding, active, and terminated statuses, with optional pagination and a terminated-only filter. This returns personally identifiable information including names and emails. Use this to find employees or verify headcount data.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "gusto.employees_list", owner_id, args, account_id=account_id
        )

    async def payrolls_list(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: GustoPayrollsListRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Lists payroll runs for a company with optional date range and processing type filters. Returns payroll status, pay period dates, and processing type. Use this to review payroll history or check the status of upcoming payroll runs.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "gusto.payrolls_list", owner_id, args, account_id=account_id
        )
