# @generated by scripts/gen_sdk.py — DO NOT EDIT.

"""Typed SDK namespace for the `hubspot` app (generated)."""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

from pydantic import BaseModel, ConfigDict, Field

from keyhaven.sdk._constants import DEFAULT_ACCOUNT_ID

if TYPE_CHECKING:
    from keyhaven.sdk.client import Keyhaven


class HubspotContactCreateBody(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    properties: dict[str, Any]
    associations: list[Any] | None = None


class HubspotContactCreateRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    body: HubspotContactCreateBody


class HubspotContactGetPath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    contactId: str


class HubspotContactGetQuery(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    properties: str | None = None
    propertiesWithHistory: str | None = None
    associations: str | None = None
    archived: bool | None = None
    idProperty: str | None = None


class HubspotContactGetRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: HubspotContactGetPath
    query: HubspotContactGetQuery | None = None


class HubspotContactUpdatePath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    contactId: str


class HubspotContactUpdateQuery(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    idProperty: str | None = None


class HubspotContactUpdateBody(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    properties: dict[str, Any]


class HubspotContactUpdateRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: HubspotContactUpdatePath
    query: HubspotContactUpdateQuery | None = None
    body: HubspotContactUpdateBody


class HubspotContactsListQuery(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    limit: int | None = None
    after: str | None = None
    properties: str | None = None
    propertiesWithHistory: str | None = None
    associations: str | None = None
    archived: bool | None = None


class HubspotContactsListRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    query: HubspotContactsListQuery | None = None


class HubspotContactsSearchBody(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    filterGroups: list[Any] | None = None
    sorts: list[Any] | None = None
    query: str | None = None
    properties: list[Any] | None = None
    limit: int | None = None
    after: str | None = None


class HubspotContactsSearchRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    body: HubspotContactsSearchBody = Field(default_factory=HubspotContactsSearchBody)


class HubspotDealCreateBody(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    properties: dict[str, Any]
    associations: list[Any] | None = None


class HubspotDealCreateRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    body: HubspotDealCreateBody


class HubspotNamespace:
    """Typed accessor for the `hubspot` app. Reach it via `client.apps.hubspot`."""

    def __init__(self, client: Keyhaven) -> None:
        self._client = client

    async def contact_create(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: HubspotContactCreateRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Creates a new contact in the CRM with specified property values and optional associations to companies, deals, or other objects. The contact becomes immediately searchable and available for lists, workflows, and sales activities. Use this to register a new lead from external sources, forms, or manual data entry.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "hubspot.contact_create", owner_id, args, account_id=account_id
        )

    async def contact_get(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: HubspotContactGetRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Fetches a single contact record by its HubSpot ID, with optional detailed property values, property change history, and associated records. Use this when you need the complete picture of a specific contact before engaging further with emails, deal creation, or list assignment.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "hubspot.contact_get", owner_id, args, account_id=account_id
        )

    async def contact_update(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: HubspotContactUpdateRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Modifies property values on an existing HubSpot contact record using a PATCH request, which only changes the specified fields while leaving others unchanged. The update is reflected across the CRM, active lists, and enrolled workflows. Use this to enrich, correct, or refresh contact data from external systems or user input.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "hubspot.contact_update", owner_id, args, account_id=account_id
        )

    async def contacts_list(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: HubspotContactsListRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Retrieves a paginated list of CRM contact records with optional property selection, association inclusion, and archived filter. Returns standard contact data plus requested custom properties from your HubSpot account. Use this to browse or export contacts for analysis, sync, or bulk operations without making any changes.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "hubspot.contacts_list", owner_id, args, account_id=account_id
        )

    async def contacts_search(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: HubspotContactsSearchRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Searches contacts using a flexible query engine with filter groups (AND/OR logic), sorting, and free-text search across default fields. Returns only matching results with the specified properties. Use this for complex lookups when simple listing or ID-based retrieval is insufficient, such as finding contacts by a combination of lifecycle stage, date, and custom property values.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "hubspot.contacts_search", owner_id, args, account_id=account_id
        )

    async def deal_create(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: HubspotDealCreateRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Creates a new deal (sales opportunity) in a specified pipeline and stage with property values and optional associations to contacts, companies, or other CRM objects. The deal becomes visible in the sales pipeline and can trigger automation rules, notifications, and forecasting updates. Use this to log a qualified sales opportunity when a contact shows buying intent or reaches a key milestone.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "hubspot.deal_create", owner_id, args, account_id=account_id
        )
