# @generated by scripts/gen_sdk.py — DO NOT EDIT.

"""Typed SDK namespace for the `lemlist` app (generated)."""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

from pydantic import BaseModel, ConfigDict, Field

from keyhaven.sdk._constants import DEFAULT_ACCOUNT_ID

if TYPE_CHECKING:
    from keyhaven.sdk.client import Keyhaven


class LemlistActivitiesListQuery(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    version: str = "v2"
    type_: str | None = Field(default=None, alias="type")
    campaignId: str | None = None
    leadId: str | None = None
    offset: int | None = None
    limit: int | None = None


class LemlistActivitiesListRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    query: LemlistActivitiesListQuery = Field(default_factory=LemlistActivitiesListQuery)


class LemlistCampaignCreateBody(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    name: str
    timezone: str | None = None
    autoReview: bool | None = None
    autoReviewConditions: list[Any] | None = None


class LemlistCampaignCreateRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    body: LemlistCampaignCreateBody


class LemlistCampaignGetPath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    id: str


class LemlistCampaignGetRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: LemlistCampaignGetPath


class LemlistCampaignsListQuery(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    version: str = "v2"
    status: str | None = None
    createdBy: str | None = None
    sortBy: str | None = None
    sortOrder: str | None = None
    offset: int | None = None
    limit: int | None = None
    page: int | None = None


class LemlistCampaignsListRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    query: LemlistCampaignsListQuery = Field(default_factory=LemlistCampaignsListQuery)


class LemlistLeadCreatePath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    campaignId: str


class LemlistLeadCreateQuery(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    deduplicate: bool | None = None
    findEmail: bool | None = None
    verifyEmail: bool | None = None
    findPhone: bool | None = None
    linkedinEnrichment: bool | None = None


class LemlistLeadCreateBody(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    email: str | None = None
    firstName: str | None = None
    lastName: str | None = None
    companyName: str | None = None
    companyDomain: str | None = None
    jobTitle: str | None = None
    linkedinUrl: str | None = None
    phone: str | None = None
    picture: str | None = None
    icebreaker: str | None = None
    timezone: str | None = None
    contactOwner: str | None = None


class LemlistLeadCreateRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: LemlistLeadCreatePath
    query: LemlistLeadCreateQuery | None = None
    body: LemlistLeadCreateBody = Field(default_factory=LemlistLeadCreateBody)


class LemlistNamespace:
    """Typed accessor for the `lemlist` app. Reach it via `client.apps.lemlist`."""

    def __init__(self, client: Keyhaven) -> None:
        self._client = client

    async def activities_list(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: LemlistActivitiesListRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Retrieves the chronological activity feed across all Lemlist campaigns, filterable by activity type (email sent, opened, replied, bounced, LinkedIn action, manual call) and scoped to a specific campaign or lead. Each entry includes timestamps, participant details, and step context from the campaign sequence. This operation is read-only and does not modify any data. Use this to monitor outreach engagement, track response rates, and diagnose delivery issues in real time.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "lemlist.activities_list", owner_id, args, account_id=account_id
        )

    async def campaign_create(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: LemlistCampaignCreateRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Creates a new empty outreach campaign in Lemlist with a name and timezone, automatically generating a default sequence and schedule. When autoReview is enabled, leads added to this campaign will be automatically launched through the sequence without requiring manual approval. This action creates a persistent campaign container that can later be paused or archived but represents the start of an outreach initiative. Use this to set up the structure for a new outreach effort before populating it with leads.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "lemlist.campaign_create", owner_id, args, account_id=account_id
        )

    async def campaign_get(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: LemlistCampaignGetRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Retrieves the complete configuration and performance statistics of a single Lemlist campaign by its ID, including sequence steps, schedule settings, lead count, and engagement metrics (opens, clicks, replies). This provides the full setup and effectiveness view of an outreach campaign beyond what the list endpoint offers. This operation is read-only and does not modify any data. Use this to audit a specific campaign's structure and performance before making adjustments.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "lemlist.campaign_get", owner_id, args, account_id=account_id
        )

    async def campaigns_list(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: LemlistCampaignsListRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Lists all outreach campaigns in your Lemlist team, filterable by status (running, draft, archived, ended, paused, errors), creator, and with full pagination support. Each campaign object includes its name, status, statistics (leads count, sent count, open rate, reply rate), and creation metadata. This operation is read-only and does not modify any data. Use this to review active campaigns, find a campaign ID for lead management, or monitor overall outreach performance.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "lemlist.campaigns_list", owner_id, args, account_id=account_id
        )

    async def lead_create(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: LemlistLeadCreateRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Adds a new person (lead) to a specific Lemlist campaign with their contact details and optional automatic enrichment such as email finding, phone finding, and LinkedIn data enrichment. If deduplication is enabled, an existing lead with the same email across other campaigns is silently skipped. This is the core action for populating a campaign with prospects; once added, the lead may begin receiving the campaign's outreach sequence if auto-launch is configured. Use this to grow a campaign's prospect list from imported data or manual entry.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "lemlist.lead_create", owner_id, args, account_id=account_id
        )
