# @generated by scripts/gen_sdk.py — DO NOT EDIT.

"""Typed SDK namespace for the `mem0` app (generated)."""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

from pydantic import BaseModel, ConfigDict, Field

from keyhaven.sdk._constants import DEFAULT_ACCOUNT_ID

if TYPE_CHECKING:
    from keyhaven.sdk.client import Keyhaven


class Mem0AddMemoryHeader(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    Content_Type: str = Field(default="application/json", alias="Content-Type")


class Mem0AddMemoryBody(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    messages: list[Any]
    user_id: str
    agent_id: str | None = None
    run_id: str | None = None
    metadata: dict[str, Any] | None = None


class Mem0AddMemoryRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    header: Mem0AddMemoryHeader = Field(default_factory=Mem0AddMemoryHeader)
    body: Mem0AddMemoryBody


class Mem0DeleteMemoryPath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    memory_id: str


class Mem0DeleteMemoryRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: Mem0DeleteMemoryPath


class Mem0GetMemoriesHeader(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    Content_Type: str = Field(default="application/json", alias="Content-Type")


class Mem0GetMemoriesBody(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    filters: dict[str, Any]
    page: int = 1
    page_size: int = 50


class Mem0GetMemoriesRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    header: Mem0GetMemoriesHeader = Field(default_factory=Mem0GetMemoriesHeader)
    body: Mem0GetMemoriesBody


class Mem0GetMemoryPath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    memory_id: str


class Mem0GetMemoryRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: Mem0GetMemoryPath


class Mem0SearchMemoriesHeader(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    Content_Type: str = Field(default="application/json", alias="Content-Type")


class Mem0SearchMemoriesBody(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    query: str
    filters: dict[str, Any]
    limit: int = 10


class Mem0SearchMemoriesRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    header: Mem0SearchMemoriesHeader = Field(default_factory=Mem0SearchMemoriesHeader)
    body: Mem0SearchMemoriesBody


class Mem0UpdateMemoryPath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    memory_id: str


class Mem0UpdateMemoryHeader(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    Content_Type: str = Field(default="application/json", alias="Content-Type")


class Mem0UpdateMemoryBody(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    text: str


class Mem0UpdateMemoryRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: Mem0UpdateMemoryPath
    header: Mem0UpdateMemoryHeader = Field(default_factory=Mem0UpdateMemoryHeader)
    body: Mem0UpdateMemoryBody


class Mem0Namespace:
    """Typed accessor for the `mem0` app. Reach it via `client.apps.mem0`."""

    def __init__(self, client: Keyhaven) -> None:
        self._client = client

    async def add_memory(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: Mem0AddMemoryRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Stores one or more conversation messages as persistent memories extracted by the Mem0 AI engine, associated with a user_id and optionally an agent_id or run_id. The messages are processed to create structured memory entries that can be semantically retrieved later. Use this after a conversation turn to persist what the agent learned about the user, so future interactions can recall preferences, facts, or context across sessions.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute("mem0.add_memory", owner_id, args, account_id=account_id)

    async def delete_memory(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: Mem0DeleteMemoryRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Permanently removes a memory entry identified by its memory_id from the memory store. This action is irreversible — the deleted memory and its text content cannot be recovered. Use this when a memory is incorrect, outdated, or should no longer influence future agent responses, but exercise caution as data loss is permanent.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "mem0.delete_memory", owner_id, args, account_id=account_id
        )

    async def get_memories(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: Mem0GetMemoriesRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Retrieves a paginated list of memories using advanced filters (e.g. by user_id) without requiring a search query. Supports AND/OR filter logic, comparison operators, and pagination. Use this to browse all stored memories for a user or agent, inspect the full memory store, or export memories — it is purely read-only and does not alter any data.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "mem0.get_memories", owner_id, args, account_id=account_id
        )

    async def get_memory(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: Mem0GetMemoryRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Retrieves a single memory entry by its unique memory_id, returning its full text content and associated metadata. Use this when you already know the specific memory ID (e.g. from a search or list result) and need to inspect its full content before deciding whether to update or delete it.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute("mem0.get_memory", owner_id, args, account_id=account_id)

    async def search_memories(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: Mem0SearchMemoriesRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Performs a semantic search across stored memories using a natural language query, filtered by user_id and other optional filters. Returns ranked memory results with relevance scores, limited by the specified count. Use this when the agent needs to recall what it knows about a user or topic before generating a response — it does not modify any data.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "mem0.search_memories", owner_id, args, account_id=account_id
        )

    async def update_memory(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: Mem0UpdateMemoryRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Updates the text content of an existing memory identified by its memory_id. The old content is replaced entirely with the new text. Use this to correct or refine a previously stored memory — for example, when a user corrects a preference or when the agent needs to consolidate outdated information.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "mem0.update_memory", owner_id, args, account_id=account_id
        )
