# @generated by scripts/gen_sdk.py — DO NOT EDIT.

"""Typed SDK namespace for the `microsoft_onedrive` app (generated)."""

from __future__ import annotations

from typing import TYPE_CHECKING, Any, Literal

from pydantic import BaseModel, ConfigDict, Field

from keyhaven.sdk._constants import DEFAULT_ACCOUNT_ID

if TYPE_CHECKING:
    from keyhaven.sdk.client import Keyhaven


class MicrosoftOnedriveCopyDriveItemPath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    itemId: str


class MicrosoftOnedriveCopyDriveItemQuery(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    microsoft_graph_conflictBehavior: Literal["fail", "replace", "rename"] | None = Field(
        default=None, alias="@microsoft.graph.conflictBehavior"
    )


class MicrosoftOnedriveCopyDriveItemBody(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    parentReference: dict[str, Any] | None = None
    name: str | None = None
    childrenOnly: bool | None = None
    includeAllVersionHistory: bool | None = None


class MicrosoftOnedriveCopyDriveItemRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: MicrosoftOnedriveCopyDriveItemPath
    query: MicrosoftOnedriveCopyDriveItemQuery | None = None
    body: MicrosoftOnedriveCopyDriveItemBody | None = None


class MicrosoftOnedriveCreateFolderPath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    parentItemId: str


class MicrosoftOnedriveCreateFolderBody(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    name: str
    folder: dict[str, Any]
    microsoft_graph_conflictBehavior: Literal["rename", "replace", "fail"] | None = Field(
        default=None, alias="@microsoft.graph.conflictBehavior"
    )


class MicrosoftOnedriveCreateFolderRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: MicrosoftOnedriveCreateFolderPath
    body: MicrosoftOnedriveCreateFolderBody


class MicrosoftOnedriveCreateTextFileRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: dict[str, Any]
    header: dict[str, Any]
    body: str


class MicrosoftOnedriveDeleteDriveItemPath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    itemId: str


class MicrosoftOnedriveDeleteDriveItemRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: MicrosoftOnedriveDeleteDriveItemPath


class MicrosoftOnedriveDeltaDriveItemsQuery(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    token: str | None = None
    select: str | None = Field(default=None, alias="$select")
    expand: str | None = Field(default=None, alias="$expand")
    top: int | None = Field(default=None, alias="$top")


class MicrosoftOnedriveDeltaDriveItemsRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    query: MicrosoftOnedriveDeltaDriveItemsQuery | None = None


class MicrosoftOnedriveGetDownloadLinkPath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    itemId: str


class MicrosoftOnedriveGetDownloadLinkQuery(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    select: str = Field(default="id,@microsoft.graph.downloadUrl", alias="$select")


class MicrosoftOnedriveGetDownloadLinkRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: MicrosoftOnedriveGetDownloadLinkPath
    query: MicrosoftOnedriveGetDownloadLinkQuery = Field(
        default_factory=MicrosoftOnedriveGetDownloadLinkQuery
    )


class MicrosoftOnedriveGetDrivePath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    driveId: str


class MicrosoftOnedriveGetDriveQuery(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    select: str | None = Field(default=None, alias="$select")


class MicrosoftOnedriveGetDriveRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: MicrosoftOnedriveGetDrivePath
    query: MicrosoftOnedriveGetDriveQuery | None = None


class MicrosoftOnedriveGetDriveItemByIdPath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    itemId: str


class MicrosoftOnedriveGetDriveItemByIdQuery(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    select: str | None = Field(default=None, alias="$select")
    expand: str | None = Field(default=None, alias="$expand")
    includeDeletedItems: bool | None = None


class MicrosoftOnedriveGetDriveItemByIdRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: MicrosoftOnedriveGetDriveItemByIdPath
    query: MicrosoftOnedriveGetDriveItemByIdQuery | None = None


class MicrosoftOnedriveGetDriveItemByPathPath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    itemPath: str


class MicrosoftOnedriveGetDriveItemByPathQuery(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    select: str | None = Field(default=None, alias="$select")
    expand: str | None = Field(default=None, alias="$expand")
    includeDeletedItems: bool | None = None


class MicrosoftOnedriveGetDriveItemByPathRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: MicrosoftOnedriveGetDriveItemByPathPath
    query: MicrosoftOnedriveGetDriveItemByPathQuery | None = None


class MicrosoftOnedriveGetMyDriveQuery(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    select: str | None = Field(default=None, alias="$select")


class MicrosoftOnedriveGetMyDriveRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    query: MicrosoftOnedriveGetMyDriveQuery | None = None


class MicrosoftOnedriveGetRootFolderQuery(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    select: str | None = Field(default=None, alias="$select")
    expand: str | None = Field(default=None, alias="$expand")
    includeDeletedItems: bool | None = None


class MicrosoftOnedriveGetRootFolderRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    query: MicrosoftOnedriveGetRootFolderQuery | None = None


class MicrosoftOnedriveListDriveItemChildrenPath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    itemId: str


class MicrosoftOnedriveListDriveItemChildrenQuery(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    select: str | None = Field(default=None, alias="$select")
    expand: str | None = Field(default=None, alias="$expand")
    skipToken: str | None = Field(default=None, alias="$skipToken")
    top: int | None = Field(default=None, alias="$top")
    orderby: str | None = Field(default=None, alias="$orderby")


class MicrosoftOnedriveListDriveItemChildrenRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: MicrosoftOnedriveListDriveItemChildrenPath
    query: MicrosoftOnedriveListDriveItemChildrenQuery | None = None


class MicrosoftOnedriveListDriveItemVersionsPath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    itemId: str


class MicrosoftOnedriveListDriveItemVersionsQuery(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    select: str | None = Field(default=None, alias="$select")
    top: int | None = Field(default=None, alias="$top")
    skipToken: str | None = Field(default=None, alias="$skipToken")


class MicrosoftOnedriveListDriveItemVersionsRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: MicrosoftOnedriveListDriveItemVersionsPath
    query: MicrosoftOnedriveListDriveItemVersionsQuery | None = None


class MicrosoftOnedriveListDrivesQuery(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    expand: str | None = Field(default=None, alias="$expand")
    select: str | None = Field(default=None, alias="$select")
    skipToken: str | None = Field(default=None, alias="$skipToken")
    top: int | None = Field(default=None, alias="$top")
    orderby: str | None = Field(default=None, alias="$orderby")


class MicrosoftOnedriveListDrivesRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    query: MicrosoftOnedriveListDrivesQuery | None = None


class MicrosoftOnedriveMoveDriveItemPath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    itemId: str


class MicrosoftOnedriveMoveDriveItemBody(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    parentReference: dict[str, Any]
    name: str | None = None
    description: str | None = None


class MicrosoftOnedriveMoveDriveItemRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: MicrosoftOnedriveMoveDriveItemPath
    body: MicrosoftOnedriveMoveDriveItemBody


class MicrosoftOnedrivePermanentDeleteDriveItemPath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    itemId: str


class MicrosoftOnedrivePermanentDeleteDriveItemRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: MicrosoftOnedrivePermanentDeleteDriveItemPath


class MicrosoftOnedriveSearchAllAccessibleItemsPath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    q: str


class MicrosoftOnedriveSearchAllAccessibleItemsQuery(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    select: str | None = Field(default=None, alias="$select")
    expand: str | None = Field(default=None, alias="$expand")
    skipToken: str | None = Field(default=None, alias="$skipToken")
    top: int | None = Field(default=None, alias="$top")
    orderby: str | None = Field(default=None, alias="$orderby")


class MicrosoftOnedriveSearchAllAccessibleItemsRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: MicrosoftOnedriveSearchAllAccessibleItemsPath
    query: MicrosoftOnedriveSearchAllAccessibleItemsQuery | None = None


class MicrosoftOnedriveSearchDriveItemsPath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    q: str


class MicrosoftOnedriveSearchDriveItemsQuery(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    select: str | None = Field(default=None, alias="$select")
    expand: str | None = Field(default=None, alias="$expand")
    skipToken: str | None = Field(default=None, alias="$skipToken")
    top: int | None = Field(default=None, alias="$top")
    orderby: str | None = Field(default=None, alias="$orderby")


class MicrosoftOnedriveSearchDriveItemsRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: MicrosoftOnedriveSearchDriveItemsPath
    query: MicrosoftOnedriveSearchDriveItemsQuery | None = None


class MicrosoftOnedriveUpdateDriveItemPath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    itemId: str


class MicrosoftOnedriveUpdateDriveItemBody(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    name: str | None = None
    parentReference: dict[str, Any] | None = None
    description: str | None = None


class MicrosoftOnedriveUpdateDriveItemRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: MicrosoftOnedriveUpdateDriveItemPath
    body: MicrosoftOnedriveUpdateDriveItemBody = Field(
        default_factory=MicrosoftOnedriveUpdateDriveItemBody
    )


class MicrosoftOnedriveUpdateTextFileContentRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: dict[str, Any]
    header: dict[str, Any]
    body: str


class MicrosoftOnedriveNamespace:
    """Typed accessor for the `microsoft_onedrive` app. Reach it via `client.apps.microsoft_onedrive`."""

    def __init__(self, client: Keyhaven) -> None:
        self._client = client

    async def copy_drive_item(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: MicrosoftOnedriveCopyDriveItemRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Creates a copy of a file or folder asynchronously, optionally to a different parent folder with a new name. The operation is queued and processed asynchronously — monitor the returned URL for completion. Can copy children only (for folders) and optionally include full version history. Duplicates data but does not affect the original.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "microsoft_onedrive.copy_drive_item", owner_id, args, account_id=account_id
        )

    async def create_folder(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: MicrosoftOnedriveCreateFolderRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Creates a new folder at a specified parent location in OneDrive. Requires a folder name and the parent folder ID. Supports conflict behavior options: rename, replace, or fail if a folder with the same name exists. Returns the newly created folder metadata. Use this to organize files into directories. Easily reversible (delete or rename).
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "microsoft_onedrive.create_folder", owner_id, args, account_id=account_id
        )

    async def create_text_file(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: MicrosoftOnedriveCreateTextFileRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Uploads or creates a new text-based file (txt, md, csv, json, etc.) in OneDrive at a specified parent location. Supports files up to 250 MB. The file is immediately visible and accessible to anyone with drive permissions. Use this to save generated documents, reports, logs, or exported data to OneDrive. Creates new files without affecting existing ones.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "microsoft_onedrive.create_text_file", owner_id, args, account_id=account_id
        )

    async def delete_drive_item(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: MicrosoftOnedriveDeleteDriveItemRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Moves a file or folder to the OneDrive recycle bin. The item can be restored from the recycle bin by the user. This is the standard deletion method and is reversible. Returns 204 No Content on success. Use this for routine file/folder removal. Safer than permanent delete.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "microsoft_onedrive.delete_drive_item", owner_id, args, account_id=account_id
        )

    async def delta_drive_items(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: MicrosoftOnedriveDeltaDriveItemsRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Tracks incremental changes (additions, modifications, deletions) across OneDrive items since a previous sync state. Returns a delta link for continued change tracking and next links for pagination of large result sets. Use this for efficient synchronization without re-fetching the entire drive. Read-only.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "microsoft_onedrive.delta_drive_items", owner_id, args, account_id=account_id
        )

    async def get_download_link(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: MicrosoftOnedriveGetDownloadLinkRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Retrieves a pre-authenticated, time-limited download URL for a file in OneDrive. The URL can be used directly to download the file content without additional authentication. Use this when you need to share a temporary download link or pass a file URL to another service. The link is sensitive as it bypasses auth — treat it as a temporary secret.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "microsoft_onedrive.get_download_link", owner_id, args, account_id=account_id
        )

    async def get_drive(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: MicrosoftOnedriveGetDriveRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Retrieves detailed properties and metadata of a specific drive by its unique identifier. Returns information including drive name, type, owner, total/quota/remaining storage, and drive state. Use this when you need to inspect a drive's capacity or configuration. Read-only.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "microsoft_onedrive.get_drive", owner_id, args, account_id=account_id
        )

    async def get_drive_item_by_id(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: MicrosoftOnedriveGetDriveItemByIdRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Retrieves metadata about a specific file or folder in OneDrive by its unique item ID. Returns name, size, created/modified dates, parent reference, and file/folder facets. Use this when you have an item ID (e.g., from a search or children listing) and need its details. Read-only.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "microsoft_onedrive.get_drive_item_by_id", owner_id, args, account_id=account_id
        )

    async def get_drive_item_by_path(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: MicrosoftOnedriveGetDriveItemByPathRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Retrieves metadata for a file or folder in OneDrive using its file-system path relative to the root. Alternative to GET_DRIVE_ITEM_BY_ID when you know the path but not the item ID. Returns the same metadata including name, size, dates, and type. Read-only.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "microsoft_onedrive.get_drive_item_by_path", owner_id, args, account_id=account_id
        )

    async def get_my_drive(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: MicrosoftOnedriveGetMyDriveRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Retrieves the signed-in user's primary OneDrive, provisioning it automatically if it does not yet exist. This is the simplest way to access the user's personal drive without needing a drive ID. Use this as the entry point for most OneDrive file operations. The provisioning side-effect is automatic and expected.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "microsoft_onedrive.get_my_drive", owner_id, args, account_id=account_id
        )

    async def get_root_folder(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: MicrosoftOnedriveGetRootFolderRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Retrieves the root folder of the user's OneDrive, which is the top-level container for all files. Returns folder metadata and optionally expands child items in the same response. Use this as a starting point for traversing the file hierarchy. Read-only.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "microsoft_onedrive.get_root_folder", owner_id, args, account_id=account_id
        )

    async def list_drive_item_children(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: MicrosoftOnedriveListDriveItemChildrenRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Lists the immediate child items (files and folders) within a specified folder in OneDrive. Returns metadata for each child including name, size, type, and IDs. Supports pagination and filtering. Use this to navigate the folder hierarchy or enumerate directory contents. Read-only.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "microsoft_onedrive.list_drive_item_children", owner_id, args, account_id=account_id
        )

    async def list_drive_item_versions(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: MicrosoftOnedriveListDriveItemVersionsRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Retrieves the version history of a specific file in OneDrive, including version ID, who modified it, and when. Versions are returned from newest to oldest. Not all files or configurations retain full version history. Use this to review change history or identify the version to restore. Read-only.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "microsoft_onedrive.list_drive_item_versions", owner_id, args, account_id=account_id
        )

    async def list_drives(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: MicrosoftOnedriveListDrivesRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Lists all drives available to the signed-in user, including personal OneDrive, shared drives, and SharePoint document libraries. Returns drive metadata such as name, type, owner, and quota information. Use this to discover which drives are accessible before performing file operations. Read-only.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "microsoft_onedrive.list_drives", owner_id, args, account_id=account_id
        )

    async def move_drive_item(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: MicrosoftOnedriveMoveDriveItemRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Moves a file or folder to a different parent folder within the same drive, optionally renaming it. The item's path changes, which affects all users, links, and applications that reference the old location. Use this for reorganizing drive content. Reversible by moving back but may disrupt active references.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "microsoft_onedrive.move_drive_item", owner_id, args, account_id=account_id
        )

    async def permanent_delete_drive_item(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: MicrosoftOnedrivePermanentDeleteDriveItemRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Permanently and irreversibly deletes a file or folder from OneDrive. Items are NOT sent to the recycle bin. Once deleted, the data cannot be recovered by any standard means. Only use this when you are absolutely certain the item must be completely destroyed. Irreversible.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "microsoft_onedrive.permanent_delete_drive_item", owner_id, args, account_id=account_id
        )

    async def search_all_accessible_items(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: MicrosoftOnedriveSearchAllAccessibleItemsRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Performs a broad search across the user's own drive AND items shared with them from other drives. Returns matching files and folders from all accessible locations. Use this to find shared documents and files that may not be in the user's own drive. Read-only.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "microsoft_onedrive.search_all_accessible_items", owner_id, args, account_id=account_id
        )

    async def search_drive_items(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: MicrosoftOnedriveSearchDriveItemsRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Searches the user's OneDrive for items matching a text query across filenames, metadata, and file content. Returns matching files and folders with their metadata. Use this when you need to locate items by name or content. Search scope is limited to the user's own drive. Read-only.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "microsoft_onedrive.search_drive_items", owner_id, args, account_id=account_id
        )

    async def update_drive_item(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: MicrosoftOnedriveUpdateDriveItemRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Updates the metadata of a file or folder in OneDrive, including renaming, moving to a different parent folder, or changing the description. Use this to organize and maintain files. Moving changes the item's location which affects users who access it by path. Renaming is cosmetic and reversible; moving is more impactful but can be reversed by moving back.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "microsoft_onedrive.update_drive_item", owner_id, args, account_id=account_id
        )

    async def update_text_file_content(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: MicrosoftOnedriveUpdateTextFileContentRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Completely replaces the content of an existing text-based file in OneDrive with new text content. The existing content is overwritten and lost unless version history is enabled for the drive. Use this to update configuration files, edit documents, or refresh data files. Impacts users who access the file.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "microsoft_onedrive.update_text_file_content", owner_id, args, account_id=account_id
        )
