# @generated by scripts/gen_sdk.py — DO NOT EDIT.

"""Typed SDK namespace for the `microsoft_calendar` app (generated)."""

from __future__ import annotations

from typing import TYPE_CHECKING, Any, Literal

from pydantic import BaseModel, ConfigDict, Field

from keyhaven.sdk._constants import DEFAULT_ACCOUNT_ID

if TYPE_CHECKING:
    from keyhaven.sdk.client import Keyhaven


class MicrosoftCalendarAcceptEventPath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    eventId: str


class MicrosoftCalendarAcceptEventBody(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    comment: str | None = None
    sendResponse: bool | None = None


class MicrosoftCalendarAcceptEventRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: MicrosoftCalendarAcceptEventPath
    body: MicrosoftCalendarAcceptEventBody | None = None


class MicrosoftCalendarCreateCalendarBody(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    name: str
    color: (
        Literal[
            "lightBlue",
            "lightGreen",
            "lightOrange",
            "lightGray",
            "lightYellow",
            "lightTeal",
            "lightPink",
            "lightBrown",
            "lightRed",
            "maxColor",
        ]
        | None
    ) = None
    hexColor: str | None = None


class MicrosoftCalendarCreateCalendarRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    body: MicrosoftCalendarCreateCalendarBody


class MicrosoftCalendarCreateEventPath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    calendar_id: str


class MicrosoftCalendarCreateEventBody(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    subject: str
    body: dict[str, Any] | None = None
    start: dict[str, Any]
    end: dict[str, Any]
    location: dict[str, Any] | None = None
    attendees: list[Any] | None = None
    isAllDay: bool | None = None
    showAs: Literal["free", "tentative", "busy", "oof", "workingElsewhere"] | None = None
    sensitivity: Literal["normal", "personal", "private", "confidential"] | None = None
    importance: Literal["low", "normal", "high"] | None = None
    reminderMinutesBeforeStart: int | None = None
    isReminderOn: bool | None = None
    categories: list[Any] | None = None
    isOnlineMeeting: bool | None = None
    onlineMeetingProvider: (
        Literal["unknown", "skypeForBusiness", "skypeForConsumer", "teamsForBusiness"] | None
    ) = None
    allowNewTimeProposals: bool | None = None
    responseRequested: bool | None = None
    recurrence: dict[str, Any] | None = None


class MicrosoftCalendarCreateEventRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: MicrosoftCalendarCreateEventPath
    body: MicrosoftCalendarCreateEventBody


class MicrosoftCalendarCreateEventDefaultBody(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    subject: str
    body: dict[str, Any] | None = None
    start: dict[str, Any]
    end: dict[str, Any]
    location: dict[str, Any] | None = None
    attendees: list[Any] | None = None
    isAllDay: bool | None = None
    showAs: Literal["free", "tentative", "busy", "oof", "workingElsewhere"] | None = None
    sensitivity: Literal["normal", "personal", "private", "confidential"] | None = None
    importance: Literal["low", "normal", "high"] | None = None
    reminderMinutesBeforeStart: int | None = None
    isReminderOn: bool | None = None
    categories: list[Any] | None = None
    isOnlineMeeting: bool | None = None
    onlineMeetingProvider: (
        Literal["unknown", "skypeForBusiness", "skypeForConsumer", "teamsForBusiness"] | None
    ) = None
    allowNewTimeProposals: bool | None = None
    responseRequested: bool | None = None
    recurrence: dict[str, Any] | None = None


class MicrosoftCalendarCreateEventDefaultRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    body: MicrosoftCalendarCreateEventDefaultBody


class MicrosoftCalendarDeleteCalendarPath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    calendar_id: str


class MicrosoftCalendarDeleteCalendarRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: MicrosoftCalendarDeleteCalendarPath


class MicrosoftCalendarDeleteEventPath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    eventId: str


class MicrosoftCalendarDeleteEventRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: MicrosoftCalendarDeleteEventPath


class MicrosoftCalendarDeltaEventsQuery(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    startDateTime: str | None = None
    endDateTime: str | None = None
    deltatoken: str | None = Field(default=None, alias="$deltatoken")
    skiptoken: str | None = Field(default=None, alias="$skiptoken")


class MicrosoftCalendarDeltaEventsHeader(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    Prefer: str | None = None


class MicrosoftCalendarDeltaEventsRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    query: MicrosoftCalendarDeltaEventsQuery | None = None
    header: MicrosoftCalendarDeltaEventsHeader | None = None


class MicrosoftCalendarDismissReminderPath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    eventId: str


class MicrosoftCalendarDismissReminderRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: MicrosoftCalendarDismissReminderPath


class MicrosoftCalendarForwardEventPath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    eventId: str


class MicrosoftCalendarForwardEventBody(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    Comment: str | None = None
    ToRecipients: list[Any]


class MicrosoftCalendarForwardEventRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: MicrosoftCalendarForwardEventPath
    body: MicrosoftCalendarForwardEventBody


class MicrosoftCalendarGetCalendarPath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    calendar_id: str


class MicrosoftCalendarGetCalendarQuery(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    select: str | None = Field(default=None, alias="$select")
    expand: str | None = Field(default=None, alias="$expand")


class MicrosoftCalendarGetCalendarRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: MicrosoftCalendarGetCalendarPath
    query: MicrosoftCalendarGetCalendarQuery | None = None


class MicrosoftCalendarGetEventPath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    eventId: str


class MicrosoftCalendarGetEventQuery(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    select: str | None = Field(default=None, alias="$select")
    expand: str | None = Field(default=None, alias="$expand")


class MicrosoftCalendarGetEventHeader(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    Prefer: str | None = None


class MicrosoftCalendarGetEventRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: MicrosoftCalendarGetEventPath
    query: MicrosoftCalendarGetEventQuery | None = None
    header: MicrosoftCalendarGetEventHeader | None = None


class MicrosoftCalendarGetScheduleHeader(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    Prefer: str | None = None


class MicrosoftCalendarGetScheduleBody(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    schedules: list[Any]
    startTime: dict[str, Any]
    endTime: dict[str, Any]
    availabilityViewInterval: int | None = None


class MicrosoftCalendarGetScheduleRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    header: MicrosoftCalendarGetScheduleHeader | None = None
    body: MicrosoftCalendarGetScheduleBody


class MicrosoftCalendarListAllEventsQuery(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    select: str | None = Field(default=None, alias="$select")
    filter: str | None = Field(default=None, alias="$filter")
    orderby: str | None = Field(default=None, alias="$orderby")
    top: int | None = Field(default=None, alias="$top")
    skip: int | None = Field(default=None, alias="$skip")
    expand: str | None = Field(default=None, alias="$expand")


class MicrosoftCalendarListAllEventsHeader(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    Prefer: str | None = None


class MicrosoftCalendarListAllEventsRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    query: MicrosoftCalendarListAllEventsQuery | None = None
    header: MicrosoftCalendarListAllEventsHeader | None = None


class MicrosoftCalendarListCalendarViewPath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    calendar_id: str


class MicrosoftCalendarListCalendarViewQuery(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    startDateTime: str
    endDateTime: str
    select: str | None = Field(default=None, alias="$select")
    filter: str | None = Field(default=None, alias="$filter")
    orderby: str | None = Field(default=None, alias="$orderby")
    top: int | None = Field(default=None, alias="$top")
    skip: int | None = Field(default=None, alias="$skip")


class MicrosoftCalendarListCalendarViewHeader(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    Prefer: str | None = None


class MicrosoftCalendarListCalendarViewRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: MicrosoftCalendarListCalendarViewPath
    query: MicrosoftCalendarListCalendarViewQuery
    header: MicrosoftCalendarListCalendarViewHeader | None = None


class MicrosoftCalendarListCalendarsQuery(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    select: str | None = Field(default=None, alias="$select")
    filter: str | None = Field(default=None, alias="$filter")
    orderby: str | None = Field(default=None, alias="$orderby")
    top: int | None = Field(default=None, alias="$top")
    skip: int | None = Field(default=None, alias="$skip")
    expand: str | None = Field(default=None, alias="$expand")


class MicrosoftCalendarListCalendarsRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    query: MicrosoftCalendarListCalendarsQuery | None = None


class MicrosoftCalendarListEventsPath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    calendar_id: str


class MicrosoftCalendarListEventsQuery(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    select: str | None = Field(default=None, alias="$select")
    filter: str | None = Field(default=None, alias="$filter")
    orderby: str | None = Field(default=None, alias="$orderby")
    top: int | None = Field(default=None, alias="$top")
    skip: int | None = Field(default=None, alias="$skip")
    expand: str | None = Field(default=None, alias="$expand")


class MicrosoftCalendarListEventsHeader(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    Prefer: str | None = None


class MicrosoftCalendarListEventsRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: MicrosoftCalendarListEventsPath
    query: MicrosoftCalendarListEventsQuery | None = None
    header: MicrosoftCalendarListEventsHeader | None = None


class MicrosoftCalendarListInstancesPath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    eventId: str


class MicrosoftCalendarListInstancesQuery(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    startDateTime: str
    endDateTime: str
    select: str | None = Field(default=None, alias="$select")
    top: int | None = Field(default=None, alias="$top")
    skip: int | None = Field(default=None, alias="$skip")
    orderby: str | None = Field(default=None, alias="$orderby")


class MicrosoftCalendarListInstancesRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: MicrosoftCalendarListInstancesPath
    query: MicrosoftCalendarListInstancesQuery


class MicrosoftCalendarPermanentDeleteEventPath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    eventId: str


class MicrosoftCalendarPermanentDeleteEventRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: MicrosoftCalendarPermanentDeleteEventPath


class MicrosoftCalendarSnoozeReminderPath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    eventId: str


class MicrosoftCalendarSnoozeReminderBody(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    newReminderTime: dict[str, Any]


class MicrosoftCalendarSnoozeReminderRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: MicrosoftCalendarSnoozeReminderPath
    body: MicrosoftCalendarSnoozeReminderBody


class MicrosoftCalendarTentativelyAcceptEventPath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    eventId: str


class MicrosoftCalendarTentativelyAcceptEventBody(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    comment: str | None = None
    sendResponse: bool | None = None
    proposedNewTime: dict[str, Any] | None = None


class MicrosoftCalendarTentativelyAcceptEventRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: MicrosoftCalendarTentativelyAcceptEventPath
    body: MicrosoftCalendarTentativelyAcceptEventBody | None = None


class MicrosoftCalendarUpdateCalendarPath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    calendar_id: str


class MicrosoftCalendarUpdateCalendarBody(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    name: str | None = None
    color: (
        Literal[
            "lightBlue",
            "lightGreen",
            "lightOrange",
            "lightGray",
            "lightYellow",
            "lightTeal",
            "lightPink",
            "lightBrown",
            "lightRed",
            "maxColor",
            "auto",
        ]
        | None
    ) = None
    hexColor: str | None = None
    isDefaultCalendar: bool | None = None


class MicrosoftCalendarUpdateCalendarRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: MicrosoftCalendarUpdateCalendarPath
    body: MicrosoftCalendarUpdateCalendarBody = Field(
        default_factory=MicrosoftCalendarUpdateCalendarBody
    )


class MicrosoftCalendarUpdateEventPath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    eventId: str


class MicrosoftCalendarUpdateEventBody(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    subject: str | None = None
    body: dict[str, Any] | None = None
    start: dict[str, Any] | None = None
    end: dict[str, Any] | None = None
    location: dict[str, Any] | None = None
    attendees: list[Any] | None = None
    importance: Literal["low", "normal", "high"] | None = None
    sensitivity: Literal["normal", "personal", "private", "confidential"] | None = None
    showAs: Literal["free", "tentative", "busy", "oof", "workingElsewhere", "unknown"] | None = None
    isAllDay: bool | None = None
    isReminderOn: bool | None = None
    reminderMinutesBeforeStart: int | None = None
    isOnlineMeeting: bool | None = None
    onlineMeetingProvider: (
        Literal["teamsForBusiness", "skypeForBusiness", "skypeForConsumer"] | None
    ) = None
    responseRequested: bool | None = None
    hideAttendees: bool | None = None
    categories: list[Any] | None = None
    recurrence: dict[str, Any] | None = None


class MicrosoftCalendarUpdateEventRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: MicrosoftCalendarUpdateEventPath
    body: MicrosoftCalendarUpdateEventBody | None = None


class MicrosoftCalendarNamespace:
    """Typed accessor for the `microsoft_calendar` app. Reach it via `client.apps.microsoft_calendar`."""

    def __init__(self, client: Keyhaven) -> None:
        self._client = client

    async def accept_event(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: MicrosoftCalendarAcceptEventRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Accepts a meeting event on behalf of the user, confirming attendance. Optionally includes a comment and controls whether a response is sent to the organizer. The event is added to the user's calendar if not already present. Use this to accept meeting invitations programmatically. Impactful because it communicates attendance status to the organizer and blocks the time slot.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "microsoft_calendar.accept_event", owner_id, args, account_id=account_id
        )

    async def create_calendar(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: MicrosoftCalendarCreateCalendarRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Creates a new calendar in the user's default calendar group with a specified name and optional color properties. The new calendar immediately appears in the user's calendar list and can hold events. Use this when you need a dedicated calendar for a specific project, category, or purpose. This action is visible to the user and reversible by deleting the calendar.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "microsoft_calendar.create_calendar", owner_id, args, account_id=account_id
        )

    async def create_event(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: MicrosoftCalendarCreateEventRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Creates a new event in a specified calendar with full details including subject, start/end times, location, attendees, and recurrence. Attendees receive meeting invitations if their email is included. The event appears on all invitees' calendars. Use this to schedule meetings, appointments, or events programmatically. Impactful because it sends notifications and occupies time slots visible to others.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "microsoft_calendar.create_event", owner_id, args, account_id=account_id
        )

    async def create_event_default(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: MicrosoftCalendarCreateEventDefaultRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Creates a new event directly in the user's default calendar without needing to specify a calendar ID. Supports the same full feature set as CREATE_EVENT including attendees, location, and recurrence. Use this as a convenient shortcut when you know the event should go in the primary calendar. Impactful because it sends invitations.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "microsoft_calendar.create_event_default", owner_id, args, account_id=account_id
        )

    async def delete_calendar(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: MicrosoftCalendarDeleteCalendarRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Permanently removes a non-default calendar and all events it contains. The default calendar cannot be deleted. This action is irreversible — all events in the calendar are lost. A cancellation notice is NOT sent to attendees. Only use this when you are certain the calendar and its contents are no longer needed.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "microsoft_calendar.delete_calendar", owner_id, args, account_id=account_id
        )

    async def delete_event(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: MicrosoftCalendarDeleteEventRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Permanently removes an event from the calendar. If the event is a meeting and the user is the organizer, a cancellation notice is sent to all attendees and the event is removed from their calendars. This action cannot be undone. Use with caution — prefer cancelling or declining if appropriate.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "microsoft_calendar.delete_event", owner_id, args, account_id=account_id
        )

    async def delta_events(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: MicrosoftCalendarDeltaEventsRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Retrieves a set of events that have been added, deleted, or updated in a calendar view since the last delta query. Use this for incremental synchronization to avoid fetching the entire calendar on every sync. Returns delta tokens for pagination and subsequent change tracking rounds. Read-only.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "microsoft_calendar.delta_events", owner_id, args, account_id=account_id
        )

    async def dismiss_reminder(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: MicrosoftCalendarDismissReminderRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Dismisses a triggered reminder for a specific calendar event, suppressing the alert notification. The event itself is unchanged; only the reminder notification is cleared. Use this to programmatically manage notification state. Internal UX action with no lasting data changes.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "microsoft_calendar.dismiss_reminder", owner_id, args, account_id=account_id
        )

    async def forward_event(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: MicrosoftCalendarForwardEventRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Forwards an existing calendar event to new recipients, optionally with a comment. The forwarded event with its details is sent to the specified recipients as a meeting request. Use this to share meeting details with people who were not originally invited. Impactful because it sends invitations.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "microsoft_calendar.forward_event", owner_id, args, account_id=account_id
        )

    async def get_calendar(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: MicrosoftCalendarGetCalendarRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Retrieves detailed properties and metadata of a specific calendar by its unique identifier. Returns information including the calendar name, color, owner, permissions, and settings. Use this to inspect a calendar's configuration before making changes or to verify a calendar's identity. Read-only operation with no side effects.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "microsoft_calendar.get_calendar", owner_id, args, account_id=account_id
        )

    async def get_event(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: MicrosoftCalendarGetEventRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Retrieves the full details of a specific event by its unique identifier. Returns subject, body, attendees, location, times, and all other properties. Use this to inspect an event's complete data before deciding to update, forward, or respond to it. Supports timezone preferences via Prefer header and property selection via $select. Read-only.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "microsoft_calendar.get_event", owner_id, args, account_id=account_id
        )

    async def get_schedule(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: MicrosoftCalendarGetScheduleRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Retrieves free/busy availability information for a collection of users, distribution lists, or resources over a specified time period. Returns time slots marked as free, tentative, busy, or out-of-office for each requested entity. Use this to find optimal meeting times when scheduling with multiple people or booking rooms. Read-only — it only queries availability data.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "microsoft_calendar.get_schedule", owner_id, args, account_id=account_id
        )

    async def list_all_events(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: MicrosoftCalendarListAllEventsRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Returns a comprehensive list of all events across every calendar in the user's mailbox in a single unified response. This provides a mailbox-wide view without needing to query each calendar individually. Use this for dashboard-style overviews or when you need to search broadly across all calendars. Read-only.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "microsoft_calendar.list_all_events", owner_id, args, account_id=account_id
        )

    async def list_calendar_view(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: MicrosoftCalendarListCalendarViewRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Retrieves all calendar events, occurrences, exceptions, and single instances within a specified time range for a given calendar. This is the recommended way to view scheduled events between two dates, including recurring series expansions. Use this to check availability, find existing appointments, or get details of events in a specific window. Requires start and end date-time. Read-only.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "microsoft_calendar.list_calendar_view", owner_id, args, account_id=account_id
        )

    async def list_calendars(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: MicrosoftCalendarListCalendarsRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Retrieves all calendars belonging to the signed-in user from the default calendar group. Use this to discover available calendars, their names, colors, and ownership before selecting one for further operations like viewing or creating events. Supports OData query parameters for filtering, sorting, and property selection. Read-only, no data is changed.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "microsoft_calendar.list_calendars", owner_id, args, account_id=account_id
        )

    async def list_events(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: MicrosoftCalendarListEventsRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Returns a list of all event objects in a specific calendar without date constraints, including single instances and series masters. Unlike calendarView, this does not expand recurring events into individual occurrences. Use this for broad queries like finding all events with certain properties or getting a complete event inventory. Read-only.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "microsoft_calendar.list_events", owner_id, args, account_id=account_id
        )

    async def list_instances(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: MicrosoftCalendarListInstancesRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Retrieves all occurrences (instances) of a recurring event within a specified time range. If the event is a series master, this expands and returns each individual occurrence including exceptions (modified instances). Use this to see exactly when a recurring event falls within a date window. Read-only.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "microsoft_calendar.list_instances", owner_id, args, account_id=account_id
        )

    async def permanent_delete_event(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: MicrosoftCalendarPermanentDeleteEventRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Performs a deep permanent deletion of an event, moving it to the purges folder in the dumpster. Unlike regular delete, standard email clients and recovery tools cannot access or restore these items. Only use this for sensitive data that must be irrecoverably removed. NOT reversible by normal means.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "microsoft_calendar.permanent_delete_event", owner_id, args, account_id=account_id
        )

    async def snooze_reminder(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: MicrosoftCalendarSnoozeReminderRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Postpones a triggered reminder for a calendar event until a specified future time. The reminder will re-fire at the new time unless dismissed again or the event passes. Use this to defer a reminder to a more convenient moment. Internal UX action affecting notification timing only.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "microsoft_calendar.snooze_reminder", owner_id, args, account_id=account_id
        )

    async def tentatively_accept_event(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: MicrosoftCalendarTentativelyAcceptEventRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Tentatively accepts a meeting event, indicating possible attendance with uncertainty. Supports proposing an alternative time slot. The event is marked as tentative on the calendar and the organizer is optionally notified. Use this when you may attend but need to confirm later, or want to suggest a different time. Less committal than full accept.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "microsoft_calendar.tentatively_accept_event", owner_id, args, account_id=account_id
        )

    async def update_calendar(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: MicrosoftCalendarUpdateCalendarRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Modifies the properties of an existing calendar, such as its display name, color theme, or default calendar status. Changes are immediately reflected in the user's calendar list. Use PATCH semantics — only include fields to change. Use this to rename a calendar, recolor it, or promote/demote it as the default calendar. Reversible by updating again.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "microsoft_calendar.update_calendar", owner_id, args, account_id=account_id
        )

    async def update_event(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: MicrosoftCalendarUpdateEventRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Modifies properties of an existing event including subject, time, location, attendees, and settings. Changes are visible to all attendees and may trigger update notifications. Use PATCH to update only specific fields. Use this to reschedule meetings, change locations, update agendas, or adjust attendee lists. Impactful because updates reach all participants.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "microsoft_calendar.update_event", owner_id, args, account_id=account_id
        )
