# @generated by scripts/gen_sdk.py — DO NOT EDIT.

"""Typed SDK namespace for the `microsoft_outlook` app (generated)."""

from __future__ import annotations

from typing import TYPE_CHECKING, Any, Literal

from pydantic import BaseModel, ConfigDict, Field

from keyhaven.sdk._constants import DEFAULT_ACCOUNT_ID

if TYPE_CHECKING:
    from keyhaven.sdk.client import Keyhaven


class MicrosoftOutlookCopyMailFolderPath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    folder_id: str


class MicrosoftOutlookCopyMailFolderBody(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    destinationId: str


class MicrosoftOutlookCopyMailFolderRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: MicrosoftOutlookCopyMailFolderPath
    body: MicrosoftOutlookCopyMailFolderBody


class MicrosoftOutlookCopyMessagePath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    message_id: str


class MicrosoftOutlookCopyMessageBody(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    destinationId: str


class MicrosoftOutlookCopyMessageRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: MicrosoftOutlookCopyMessagePath
    body: MicrosoftOutlookCopyMessageBody


class MicrosoftOutlookCreateChildFolderPath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    folder_id: str


class MicrosoftOutlookCreateChildFolderBody(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    displayName: str
    isHidden: bool | None = None


class MicrosoftOutlookCreateChildFolderRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: MicrosoftOutlookCreateChildFolderPath
    body: MicrosoftOutlookCreateChildFolderBody


class MicrosoftOutlookCreateDraftMessageBody(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    subject: str | None = None
    importance: Literal["low", "normal", "high"] | None = None
    body: dict[str, Any] | None = None
    toRecipients: list[Any] | None = None
    ccRecipients: list[Any] | None = None
    bccRecipients: list[Any] | None = None


class MicrosoftOutlookCreateDraftMessageRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    body: MicrosoftOutlookCreateDraftMessageBody = Field(
        default_factory=MicrosoftOutlookCreateDraftMessageBody
    )


class MicrosoftOutlookCreateForwardPath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    message_id: str


class MicrosoftOutlookCreateForwardBody(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    comment: str | None = None
    toRecipients: list[Any] | None = None
    message: dict[str, Any] | None = None


class MicrosoftOutlookCreateForwardRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: MicrosoftOutlookCreateForwardPath
    body: MicrosoftOutlookCreateForwardBody | None = None


class MicrosoftOutlookCreateMailFolderBody(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    displayName: str
    isHidden: bool | None = None


class MicrosoftOutlookCreateMailFolderRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    body: MicrosoftOutlookCreateMailFolderBody


class MicrosoftOutlookCreateMessageInFolderPath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    folder_id: str


class MicrosoftOutlookCreateMessageInFolderBody(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    subject: str
    body: dict[str, Any]
    toRecipients: list[Any] | None = None
    ccRecipients: list[Any] | None = None
    bccRecipients: list[Any] | None = None
    importance: Literal["low", "normal", "high"] | None = None
    isRead: bool | None = None


class MicrosoftOutlookCreateMessageInFolderRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: MicrosoftOutlookCreateMessageInFolderPath
    body: MicrosoftOutlookCreateMessageInFolderBody


class MicrosoftOutlookCreateReplyPath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    message_id: str


class MicrosoftOutlookCreateReplyRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: MicrosoftOutlookCreateReplyPath


class MicrosoftOutlookCreateReplyAllPath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    message_id: str


class MicrosoftOutlookCreateReplyAllRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: MicrosoftOutlookCreateReplyAllPath


class MicrosoftOutlookDeleteMailFolderPath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    folder_id: str


class MicrosoftOutlookDeleteMailFolderRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: MicrosoftOutlookDeleteMailFolderPath


class MicrosoftOutlookDeleteMessagePath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    message_id: str


class MicrosoftOutlookDeleteMessageRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: MicrosoftOutlookDeleteMessagePath


class MicrosoftOutlookDeltaMailFoldersQuery(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    deltatoken: str | None = Field(default=None, alias="$deltatoken")
    skiptoken: str | None = Field(default=None, alias="$skiptoken")
    select: str | None = Field(default=None, alias="$select")


class MicrosoftOutlookDeltaMailFoldersRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    query: MicrosoftOutlookDeltaMailFoldersQuery | None = None


class MicrosoftOutlookForwardPath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    message_id: str


class MicrosoftOutlookForwardBody(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    comment: str | None = None
    toRecipients: list[Any] | None = None
    message: dict[str, Any] | None = None


class MicrosoftOutlookForwardRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: MicrosoftOutlookForwardPath
    body: MicrosoftOutlookForwardBody = Field(default_factory=MicrosoftOutlookForwardBody)


class MicrosoftOutlookGetMailFolderPath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    folder_id: str


class MicrosoftOutlookGetMailFolderQuery(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    select: str | None = Field(default=None, alias="$select")
    expand: str | None = Field(default=None, alias="$expand")


class MicrosoftOutlookGetMailFolderRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: MicrosoftOutlookGetMailFolderPath
    query: MicrosoftOutlookGetMailFolderQuery | None = None


class MicrosoftOutlookGetMessagePath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    message_id: str


class MicrosoftOutlookGetMessageQuery(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    select: str | None = Field(default=None, alias="$select")
    expand: str | None = Field(default=None, alias="$expand")


class MicrosoftOutlookGetMessageRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: MicrosoftOutlookGetMessagePath
    query: MicrosoftOutlookGetMessageQuery | None = None


class MicrosoftOutlookListChildFoldersPath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    folder_id: str


class MicrosoftOutlookListChildFoldersQuery(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    includeHiddenFolders: bool | None = None
    select: str | None = Field(default=None, alias="$select")
    filter: str | None = Field(default=None, alias="$filter")
    orderby: str | None = Field(default=None, alias="$orderby")
    top: int | None = Field(default=None, alias="$top")
    skip: int | None = Field(default=None, alias="$skip")


class MicrosoftOutlookListChildFoldersRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: MicrosoftOutlookListChildFoldersPath
    query: MicrosoftOutlookListChildFoldersQuery | None = None


class MicrosoftOutlookListMailFoldersQuery(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    includeHiddenFolders: bool | None = None
    top: int | None = Field(default=None, alias="$top")
    skip: int | None = Field(default=None, alias="$skip")
    filter: str | None = Field(default=None, alias="$filter")
    orderby: str | None = Field(default=None, alias="$orderby")
    select: str | None = Field(default=None, alias="$select")


class MicrosoftOutlookListMailFoldersRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    query: MicrosoftOutlookListMailFoldersQuery | None = None


class MicrosoftOutlookListMessagesQuery(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    top: int | None = Field(default=None, alias="$top")
    skip: int | None = Field(default=None, alias="$skip")
    filter: str | None = Field(default=None, alias="$filter")
    orderby: str | None = Field(default=None, alias="$orderby")


class MicrosoftOutlookListMessagesRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    query: MicrosoftOutlookListMessagesQuery | None = None


class MicrosoftOutlookListMessagesInFolderPath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    folder_id: str


class MicrosoftOutlookListMessagesInFolderQuery(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    select: str | None = Field(default=None, alias="$select")
    filter: str | None = Field(default=None, alias="$filter")
    orderby: str | None = Field(default=None, alias="$orderby")
    top: int | None = Field(default=None, alias="$top")
    skip: int | None = Field(default=None, alias="$skip")
    search: str | None = Field(default=None, alias="$search")
    expand: str | None = Field(default=None, alias="$expand")


class MicrosoftOutlookListMessagesInFolderRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: MicrosoftOutlookListMessagesInFolderPath
    query: MicrosoftOutlookListMessagesInFolderQuery | None = None


class MicrosoftOutlookPermanentDeletePath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    message_id: str


class MicrosoftOutlookPermanentDeleteRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: MicrosoftOutlookPermanentDeletePath


class MicrosoftOutlookReplyPath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    message_id: str


class MicrosoftOutlookReplyBody(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    comment: str | None = None
    message: dict[str, Any] | None = None


class MicrosoftOutlookReplyRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: MicrosoftOutlookReplyPath
    body: MicrosoftOutlookReplyBody = Field(default_factory=MicrosoftOutlookReplyBody)


class MicrosoftOutlookReplyAllPath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    message_id: str


class MicrosoftOutlookReplyAllBody(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    comment: str | None = None
    message: dict[str, Any] | None = None


class MicrosoftOutlookReplyAllRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: MicrosoftOutlookReplyAllPath
    body: MicrosoftOutlookReplyAllBody = Field(default_factory=MicrosoftOutlookReplyAllBody)


class MicrosoftOutlookSendPath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    message_id: str


class MicrosoftOutlookSendRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: MicrosoftOutlookSendPath


class MicrosoftOutlookUpdateMailFolderPath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    folder_id: str


class MicrosoftOutlookUpdateMailFolderBody(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    displayName: str


class MicrosoftOutlookUpdateMailFolderRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: MicrosoftOutlookUpdateMailFolderPath
    body: MicrosoftOutlookUpdateMailFolderBody


class MicrosoftOutlookNamespace:
    """Typed accessor for the `microsoft_outlook` app. Reach it via `client.apps.microsoft_outlook`."""

    def __init__(self, client: Keyhaven) -> None:
        self._client = client

    async def copy_mail_folder(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: MicrosoftOutlookCopyMailFolderRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Copies an entire mail folder and all its contents to a specified destination folder. The folder structure and all messages are duplicated. Use this to backup or reorganize folder hierarchies. Original folder is unchanged. Reversible by deleting the copy.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "microsoft_outlook.copy_mail_folder", owner_id, args, account_id=account_id
        )

    async def copy_message(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: MicrosoftOutlookCopyMessageRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Creates a copy of an email message in a specified destination folder within the same mailbox. Use this to duplicate messages for filing or organization. The original message is unchanged. Supports well-known folder names (inbox, drafts, sentitems, etc.). Reversible by deleting the copy.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "microsoft_outlook.copy_message", owner_id, args, account_id=account_id
        )

    async def create_child_folder(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: MicrosoftOutlookCreateChildFolderRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Creates a new child mail folder under a specified parent folder with a given display name. Optionally marks it as hidden (cannot be unhidden later). Use this to build hierarchical folder structures for email organization. Reversible by deleting.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "microsoft_outlook.create_child_folder", owner_id, args, account_id=account_id
        )

    async def create_draft_message(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: MicrosoftOutlookCreateDraftMessageRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Creates a new draft email message in JSON format with subject, body, recipients, and importance. The draft is saved in the Drafts folder and must be explicitly sent via the SEND action later. Use this to compose emails programmatically for later review and approval. No email is transmitted.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "microsoft_outlook.create_draft_message", owner_id, args, account_id=account_id
        )

    async def create_forward(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: MicrosoftOutlookCreateForwardRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Creates a draft that forwards an existing message to specified recipients, optionally including a comment. The draft is saved in the Drafts folder and can be updated or sent later. Use this to prepare a message forward for review before sending. No email is transmitted yet.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "microsoft_outlook.create_forward", owner_id, args, account_id=account_id
        )

    async def create_mail_folder(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: MicrosoftOutlookCreateMailFolderRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Creates a new mail folder at the root level of the user's mailbox with a specified display name and optional hidden status. Hidden folders cannot be unhidden later. Use this to organize emails into custom categories. Visible in the user's mailbox immediately. Reversible by deleting the folder.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "microsoft_outlook.create_mail_folder", owner_id, args, account_id=account_id
        )

    async def create_message_in_folder(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: MicrosoftOutlookCreateMessageInFolderRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Creates a new message directly in a specified mail folder. Unlike drafts, this message exists as a standalone item in the folder. Supports setting subject, body, recipients, importance, and read status. Use this to programmatically inject messages into a folder (e.g., for archiving or auto-generation). Does not send the message — it only creates it as a stored item.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "microsoft_outlook.create_message_in_folder", owner_id, args, account_id=account_id
        )

    async def create_reply(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: MicrosoftOutlookCreateReplyRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Creates a draft reply to an existing message, automatically addressing it to the original sender. The draft is saved in the Drafts folder and can be updated or sent later. Use this to prepare a reply for review before sending. No email is transmitted yet.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "microsoft_outlook.create_reply", owner_id, args, account_id=account_id
        )

    async def create_reply_all(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: MicrosoftOutlookCreateReplyAllRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Creates a draft reply addressed to the sender and all original recipients (To and CC) of a message. The draft is saved in the Drafts folder for later review or sending. Use this to prepare a group reply for review. No email is transmitted yet.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "microsoft_outlook.create_reply_all", owner_id, args, account_id=account_id
        )

    async def delete_mail_folder(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: MicrosoftOutlookDeleteMailFolderRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Deletes a mail folder by its ID or well-known name. The folder and its contents are removed. Well-known folders (inbox, sentitems, etc.) may have restrictions. Deleted folders typically move to the recoverable items area but may not be restorable via standard UI.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "microsoft_outlook.delete_mail_folder", owner_id, args, account_id=account_id
        )

    async def delete_message(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: MicrosoftOutlookDeleteMessageRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Deletes a specific email message, moving it to the Deleted Items folder. The message is not permanently removed. Use this to clean up unwanted messages. Recoverable from the Deleted Items folder.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "microsoft_outlook.delete_message", owner_id, args, account_id=account_id
        )

    async def delta_mail_folders(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: MicrosoftOutlookDeltaMailFoldersRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Tracks incremental changes to mail folders (additions, deletions, modifications) since the last delta query. Use this for efficient synchronization of folder structure across sessions. Returns delta tokens for continued tracking and skip tokens for pagination. Read-only.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "microsoft_outlook.delta_mail_folders", owner_id, args, account_id=account_id
        )

    async def forward(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: MicrosoftOutlookForwardRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Immediately forwards an existing message to specified recipients with an optional comment. The forwarded message is sent right away and saved in the Sent Items folder. Unlike CREATE_FORWARD, this sends immediately without a draft stage. Impactful because it delivers a message to real recipients on behalf of the user.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "microsoft_outlook.forward", owner_id, args, account_id=account_id
        )

    async def get_mail_folder(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: MicrosoftOutlookGetMailFolderRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Retrieves detailed properties of a specific mail folder including its display name, parent folder, child folder count, and total item count. Use this to inspect a folder's configuration and statistics. Read-only.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "microsoft_outlook.get_mail_folder", owner_id, args, account_id=account_id
        )

    async def get_message(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: MicrosoftOutlookGetMessageRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Retrieves the full content of a specific email message by its ID, including body, sender, recipients, and attachments. Use this to read the complete content of a message identified from a list operation. Supports property selection and expanding attachments. Message content may be personal or sensitive.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "microsoft_outlook.get_message", owner_id, args, account_id=account_id
        )

    async def list_child_folders(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: MicrosoftOutlookListChildFoldersRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Retrieves the child folders nested under a specific mail folder, showing the folder hierarchy. Optionally includes hidden folders. Use this to explore sub-folder structure before navigating deeper. Read-only.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "microsoft_outlook.list_child_folders", owner_id, args, account_id=account_id
        )

    async def list_mail_folders(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: MicrosoftOutlookListMailFoldersRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Retrieves the collection of mail folders directly under the root of the user's mailbox. Includes standard folders (Inbox, Drafts, Sent Items) and custom folders. Optionally includes hidden folders. Use this to discover the folder structure before navigating or organizing. Read-only.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "microsoft_outlook.list_mail_folders", owner_id, args, account_id=account_id
        )

    async def list_messages(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: MicrosoftOutlookListMessagesRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Retrieves a list of email messages from the signed-in user's mailbox. Supports OData filtering, sorting, and pagination. Returns message metadata including subject, sender, received time, and flags but not full body by default. Use this to browse the inbox or find messages matching broad criteria. Read-only.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "microsoft_outlook.list_messages", owner_id, args, account_id=account_id
        )

    async def list_messages_in_folder(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: MicrosoftOutlookListMessagesInFolderRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Retrieves all email messages within a specific mail folder, identified by ID or well-known name (inbox, drafts, sentitems). Supports filtering, searching, sorting, and pagination via OData parameters. Use this to inspect the contents of a particular folder rather than the entire mailbox. Read-only.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "microsoft_outlook.list_messages_in_folder", owner_id, args, account_id=account_id
        )

    async def permanent_delete(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: MicrosoftOutlookPermanentDeleteRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Permanently deletes a message, placing it in the purges folder of the dumpster. Unlike regular delete, this moves the item to a deeper deletion state that standard email clients cannot recover. Items are eventually purged permanently after a set retention period. Use with extreme caution.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "microsoft_outlook.permanent_delete", owner_id, args, account_id=account_id
        )

    async def reply(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: MicrosoftOutlookReplyRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Immediately sends a reply to the sender of an existing message with an optional comment or custom body. The reply is delivered right away and saved in the Sent Items folder. Use this for quick replies without a draft stage. The reply communicates directly to the recipient.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "microsoft_outlook.reply", owner_id, args, account_id=account_id
        )

    async def reply_all(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: MicrosoftOutlookReplyAllRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Immediately sends a reply to the sender and all original recipients of a message. The reply is delivered to everyone on the original thread and saved in Sent Items. Use this for group replies. Impactful because it reaches multiple people.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "microsoft_outlook.reply_all", owner_id, args, account_id=account_id
        )

    async def send(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: MicrosoftOutlookSendRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Sends a draft message that was previously created. The draft can be a new message, reply, reply-all, or forward. Once sent, the message is delivered to all specified recipients and saved in the Sent Items folder. This action finalizes any draft — it is irreversible once transmitted.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "microsoft_outlook.send", owner_id, args, account_id=account_id
        )

    async def update_mail_folder(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: MicrosoftOutlookUpdateMailFolderRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Updates the properties of a mail folder, currently supporting renaming by changing the displayName. Use this to reorganize mailbox structure by renaming folders. Changes are immediately visible in the user's mailbox. Reversible by setting the name back.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "microsoft_outlook.update_mail_folder", owner_id, args, account_id=account_id
        )
