# @generated by scripts/gen_sdk.py — DO NOT EDIT.

"""Typed SDK namespace for the `missive` app (generated)."""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

from pydantic import BaseModel, ConfigDict

from keyhaven.sdk._constants import DEFAULT_ACCOUNT_ID

if TYPE_CHECKING:
    from keyhaven.sdk.client import Keyhaven


class MissiveContactsCreateBody(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    contacts: list[Any]


class MissiveContactsCreateRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    body: MissiveContactsCreateBody


class MissiveConversationsListQuery(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    limit: int | None = None
    until: int | None = None
    inbox: bool | None = None
    all: bool | None = None
    assigned: bool | None = None
    closed: bool | None = None
    snoozed: bool | None = None
    flagged: bool | None = None
    trashed: bool | None = None
    shared_label: str | None = None
    organization: str | None = None
    email: str | None = None


class MissiveConversationsListRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    query: MissiveConversationsListQuery | None = None


class MissiveTaskCreateBody(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    tasks: dict[str, Any]


class MissiveTaskCreateRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    body: MissiveTaskCreateBody


class MissiveTaskUpdatePath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    id: str


class MissiveTaskUpdateBody(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    tasks: dict[str, Any]


class MissiveTaskUpdateRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: MissiveTaskUpdatePath
    body: MissiveTaskUpdateBody


class MissiveNamespace:
    """Typed accessor for the `missive` app. Reach it via `client.apps.missive`."""

    def __init__(self, client: Keyhaven) -> None:
        self._client = client

    async def contacts_create(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: MissiveContactsCreateRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Creates one or more contacts in the shared Missive address book with names, phone numbers, email addresses, and group memberships. New contacts become immediately available to all team members for auto-complete and contact lookup. Use this when onboarding external contacts or importing a list into the organization's directory.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "missive.contacts_create", owner_id, args, account_id=account_id
        )

    async def conversations_list(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: MissiveConversationsListRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Retrieves a paginated list of conversations from a Missive shared inbox. Supports filtering by assignment status, labels, inbox/all/trashed/snoozed/flagged state, and email address. Use this to browse or search conversations before taking action (e.g., replying, assigning, or archiving). No conversations are modified.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "missive.conversations_list", owner_id, args, account_id=account_id
        )

    async def task_create(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: MissiveTaskCreateRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Creates a new standalone task or a subtask linked to a specific conversation. Assigns ownership to team members, sets a due date and description, and makes the task visible in the shared task list. Use this to create actionable follow-ups from email conversations or to build team to-do items.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "missive.task_create", owner_id, args, account_id=account_id
        )

    async def task_update(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: MissiveTaskUpdateRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Modifies an existing task's title, description, state (e.g., mark completed or in_progress), assignees, or due date. Changes are immediately reflected for all team members. Use this to progress a task through its workflow, reassign ownership, or adjust deadlines based on conversation outcomes.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "missive.task_update", owner_id, args, account_id=account_id
        )
