# @generated by scripts/gen_sdk.py — DO NOT EDIT.

"""Typed SDK namespace for the `one_signal` app (generated)."""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

from pydantic import BaseModel, ConfigDict, Field

from keyhaven.sdk._constants import DEFAULT_ACCOUNT_ID

if TYPE_CHECKING:
    from keyhaven.sdk.client import Keyhaven


class OneSignalAddDeviceHeader(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    Content_Type: str = Field(default="application/json", alias="Content-Type")


class OneSignalAddDeviceBody(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    app_id: str
    device_type: int
    identifier: str | None = None
    language: str | None = None
    timezone: int | None = None
    game_version: str | None = None
    device_model: str | None = None
    device_os: str | None = None
    ad_id: str | None = None
    sdk: str | None = None
    session_count: int | None = None
    tags: dict[str, Any] | None = None
    external_user_id: str | None = None


class OneSignalAddDeviceRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    header: OneSignalAddDeviceHeader | None = None
    body: OneSignalAddDeviceBody


class OneSignalCreatePushNotificationBody(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    app_id: str
    contents: dict[str, Any]
    headings: dict[str, Any] | None = None
    included_segments: list[Any]
    excluded_segments: list[Any] | None = None
    include_player_ids: list[Any] | None = None
    filters: list[Any] | None = None
    send_after: str | None = None
    data: dict[str, Any] | None = None
    url: str | None = None


class OneSignalCreatePushNotificationRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    body: OneSignalCreatePushNotificationBody


class OneSignalCreateSubscriptionByAliasPath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    app_id: str
    alias_id: str


class OneSignalCreateSubscriptionByAliasBody(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    subscription: dict[str, Any]


class OneSignalCreateSubscriptionByAliasRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: OneSignalCreateSubscriptionByAliasPath
    body: OneSignalCreateSubscriptionByAliasBody


class OneSignalEditDevicePath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    player_id: str


class OneSignalEditDeviceBody(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    app_id: str
    language: str | None = None
    timezone: int | None = None
    game_version: str | None = None
    device_os: str | None = None
    device_type: int | None = None
    device_model: str | None = None
    tags: dict[str, Any] | None = None


class OneSignalEditDeviceRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: OneSignalEditDevicePath
    body: OneSignalEditDeviceBody


class OneSignalViewMessagesQuery(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    app_id: str
    limit: int = 50
    offset: int | None = None
    kind: int | None = None
    template_id: str | None = None
    time_offset: int | None = None


class OneSignalViewMessagesRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    query: OneSignalViewMessagesQuery


class OneSignalNamespace:
    """Typed accessor for the `one_signal` app. Reach it via `client.apps.one_signal`."""

    def __init__(self, client: Keyhaven) -> None:
        self._client = client

    async def add_device(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: OneSignalAddDeviceRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Registers a new device (player) with OneSignal for push notification delivery. If a device with the same identifier already exists, it updates the existing record instead of creating a duplicate. This creates the association between a device token and your app, enabling future push notifications. Use this when onboarding new app installations or migrating device registrations from another system. Note: Using this endpoint directly without the OneSignal SDK may limit certain features such as conversion tracking, timezone detection, and rich push notifications.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "one_signal.add_device", owner_id, args, account_id=account_id
        )

    async def create_push_notification(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: OneSignalCreatePushNotificationRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Sends a push notification to users via the OneSignal API. Supports targeting by segments, filters, or specific device identifiers, with customizable message content, headings, scheduling, and platform-specific options. Once sent, the notification is delivered to all targeted devices immediately or at the scheduled time. Use this to broadcast announcements, send targeted campaigns, or trigger transactional alerts to your user base.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "one_signal.create_push_notification", owner_id, args, account_id=account_id
        )

    async def create_subscription_by_alias(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: OneSignalCreateSubscriptionByAliasRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Adds a new subscription (push, email, or SMS) to an existing user identified by their external alias. Subscriptions represent a user's delivery channel for receiving messages. If a subscription with the same type and token already exists, it is transferred to the specified user instead of creating a duplicate. Use this to register a new communication channel for a known user, such as adding email or SMS delivery after user creation.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "one_signal.create_subscription_by_alias", owner_id, args, account_id=account_id
        )

    async def edit_device(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: OneSignalEditDeviceRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Updates an existing device (player) record in a OneSignal app, allowing modification of attributes such as language, timezone, app version, device model, operating system, and custom tags. Changes take effect for future push notifications sent to this device. Use this to correct device metadata, update user preferences stored in tags, or maintain device records as app versions change. Note: This is a legacy endpoint; consider using the Update User or Update Subscription endpoints for new integrations.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "one_signal.edit_device", owner_id, args, account_id=account_id
        )

    async def view_messages(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: OneSignalViewMessagesRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Retrieves a list of up to 50 messages (push, email, or SMS) sent via OneSignal, with optional filtering by message type, template ID, and time offset. Pagination is handled via limit and offset parameters. Use this to review sent notification history, check delivery status, audit communication campaigns, or retrieve message IDs for further analysis. Note: Messages sent through the API are accessible for 30 days; dashboard messages are available for the app's lifetime.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "one_signal.view_messages", owner_id, args, account_id=account_id
        )
