# @generated by scripts/gen_sdk.py — DO NOT EDIT.

"""Typed SDK namespace for the `pandadoc` app (generated)."""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

from pydantic import BaseModel, ConfigDict, Field

from keyhaven.sdk._constants import DEFAULT_ACCOUNT_ID

if TYPE_CHECKING:
    from keyhaven.sdk.client import Keyhaven


class PandadocContactsListQuery(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    email: str | None = None


class PandadocContactsListRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    query: PandadocContactsListQuery | None = None


class PandadocDocumentCreateBody(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    name: str | None = None
    template_uuid: str | None = None
    folder_uuid: str | None = None
    url: str | None = None
    recipients: list[Any] | None = None
    fields: dict[str, Any] | None = None
    tokens: dict[str, Any] | None = None
    metadata: dict[str, Any] | None = None
    tags: list[Any] | None = None


class PandadocDocumentCreateRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    body: PandadocDocumentCreateBody = Field(default_factory=PandadocDocumentCreateBody)


class PandadocDocumentGetPath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    id: str


class PandadocDocumentGetRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: PandadocDocumentGetPath


class PandadocDocumentSendPath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    id: str


class PandadocDocumentSendBody(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    message: str | None = None
    subject: str | None = None
    silent: bool | None = None
    sender: dict[str, Any] | None = None
    forwarding_settings: dict[str, Any] | None = None
    reply_to: str | None = None


class PandadocDocumentSendRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: PandadocDocumentSendPath
    body: PandadocDocumentSendBody = Field(default_factory=PandadocDocumentSendBody)


class PandadocDocumentsListQuery(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    q: str | None = None
    template_id: str | None = None
    form_id: str | None = None
    folder_uuid: str | None = None
    contact_id: str | None = None
    status: int | None = None
    tag: str | None = None
    membership_id: str | None = None
    deleted: bool | None = None
    id: str | None = None
    created_from: str | None = None
    created_to: str | None = None
    completed_from: str | None = None
    completed_to: str | None = None
    order_by: str | None = None
    count: int | None = None
    page: int | None = None


class PandadocDocumentsListRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    query: PandadocDocumentsListQuery | None = None


class PandadocNamespace:
    """Typed accessor for the `pandadoc` app. Reach it via `client.apps.pandadoc`."""

    def __init__(self, client: Keyhaven) -> None:
        self._client = client

    async def contacts_list(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: PandadocContactsListRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Retrieve a list of contacts stored in the PandaDoc workspace, with an optional exact-match filter by email address. Each contact includes name, email, and company info. This is a read-only lookup. Use this when the agent needs to find a contact ID to assign as a document recipient or to verify a contact already exists before creating one.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "pandadoc.contacts_list", owner_id, args, account_id=account_id
        )

    async def document_create(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: PandadocDocumentCreateRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Create a new document in PandaDoc from a template, a file upload (PDF/DocX/RTF), or a public file URL. The creation is asynchronous: the response returns immediately with an uploaded status, which transitions to draft after a few seconds of server-side processing. The document is not yet sent to any recipient. Use this when the agent needs to generate a contract, proposal, or agreement and optionally prepare it for sending.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "pandadoc.document_create", owner_id, args, account_id=account_id
        )

    async def document_get(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: PandadocDocumentGetRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Retrieve the full details of a single PandaDoc document by its ID, including all recipients, fields, tokens, pricing tables, content blocks, metadata, tags, and linked objects. This is read-only and reveals everything configured on the document. Use this when the agent needs to inspect a document's current state before sending it, updating it, or extracting its data.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "pandadoc.document_get", owner_id, args, account_id=account_id
        )

    async def document_send(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: PandadocDocumentSendRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Send a PandaDoc document that is currently in draft status to its designated recipients, dispatching notification emails and optionally SMS messages. Once sent, the document status moves to sent and recipients receive a link to view and sign it. This action cannot be undone — a sent document cannot be recalled. Use this only when the agent has fully prepared the document and confirmed that the recipients and content are correct.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "pandadoc.document_send", owner_id, args, account_id=account_id
        )

    async def documents_list(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: PandadocDocumentsListRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Search and paginate through all PandaDoc documents in the workspace using filters by status, template, folder, owner, contact, tag, free-text query, or creation/modification/completion date ranges. This does not alter any document; it only retrieves matching results. Use this when the agent needs to find a specific document to inspect, send, or reference later.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "pandadoc.documents_list", owner_id, args, account_id=account_id
        )
