# @generated by scripts/gen_sdk.py — DO NOT EDIT.

"""Typed SDK namespace for the `paypal` app (generated)."""

from __future__ import annotations

from typing import TYPE_CHECKING, Any, Literal

from pydantic import BaseModel, ConfigDict, Field

from keyhaven.sdk._constants import DEFAULT_ACCOUNT_ID

if TYPE_CHECKING:
    from keyhaven.sdk.client import Keyhaven


class PaypalInvoiceCreateBody(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    detail: dict[str, Any]
    invoicer: dict[str, Any] | None = None
    primary_recipients: list[Any] | None = None
    items: list[Any] | None = None
    configuration: dict[str, Any] | None = None


class PaypalInvoiceCreateRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    body: PaypalInvoiceCreateBody


class PaypalInvoiceGetPath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    invoice_id: str


class PaypalInvoiceGetRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: PaypalInvoiceGetPath


class PaypalInvoicesListQuery(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    page: int = 1
    page_size: int = 20
    total_required: bool | None = None


class PaypalInvoicesListRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    query: PaypalInvoicesListQuery | None = None


class PaypalOrderCapturePath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    id: str


class PaypalOrderCaptureHeader(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    PayPal_Request_Id: str | None = Field(default=None, alias="PayPal-Request-Id")


class PaypalOrderCaptureBody(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    payment_source: dict[str, Any] | None = None


class PaypalOrderCaptureRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: PaypalOrderCapturePath
    header: PaypalOrderCaptureHeader | None = None
    body: PaypalOrderCaptureBody | None = None


class PaypalOrderCreateHeader(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    PayPal_Request_Id: str | None = Field(default=None, alias="PayPal-Request-Id")
    Prefer: str = "return=representation"


class PaypalOrderCreateBody(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    intent: Literal["CAPTURE", "AUTHORIZE"]
    purchase_units: list[Any]
    payment_source: dict[str, Any] | None = None
    application_context: dict[str, Any] | None = None


class PaypalOrderCreateRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    header: PaypalOrderCreateHeader | None = None
    body: PaypalOrderCreateBody


class PaypalOrderGetPath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    id: str


class PaypalOrderGetRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: PaypalOrderGetPath


class PaypalNamespace:
    """Typed accessor for the `paypal` app. Reach it via `client.apps.paypal`."""

    def __init__(self, client: Keyhaven) -> None:
        self._client = client

    async def invoice_create(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: PaypalInvoiceCreateRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Create a draft PayPal invoice with line items, recipient details, merchant info, and optional tax/shipping configuration. The invoice is created in draft status and is NOT sent to the recipient until the send endpoint is called explicitly. Use this when an agent needs to generate an invoice that will later be reviewed and sent. This action is reversible by deleting the draft invoice.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "paypal.invoice_create", owner_id, args, account_id=account_id
        )

    async def invoice_get(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: PaypalInvoiceGetRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Retrieve full details of a PayPal invoice by its ID, including status, line items, amounts, recipient info, and payment history. Use this to inspect an invoice before sending it, check payment status, or audit billing records. This is a read-only operation with no side effects.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "paypal.invoice_get", owner_id, args, account_id=account_id
        )

    async def invoices_list(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: PaypalInvoicesListRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Fetch a paginated list of invoices owned by the merchant, with page number and page size controls. Use this to discover recent invoices, find a specific invoice ID for follow-up operations, or audit billing activity. This is a read-only operation with no side effects.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "paypal.invoices_list", owner_id, args, account_id=account_id
        )

    async def order_capture(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: PaypalOrderCaptureRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Capture payment for a PayPal order that the buyer has already approved. Completes the transaction and transfers funds from the buyer to the merchant. For AUTHORIZE-intent orders, this captures the authorized amount; for CAPTURE-intent orders already approved, this finalizes the capture. Use this only after the buyer has been redirected back from the approval flow. This action moves real money and is irreversible.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "paypal.order_capture", owner_id, args, account_id=account_id
        )

    async def order_create(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: PaypalOrderCreateRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Create a PayPal Checkout order with intent to capture funds immediately (CAPTURE) or authorize for later capture (AUTHORIZE). Each order requires at least one purchase unit with an amount (currency + value). The response contains an approval URL that must be shown to the buyer for consent. Use this when an agent needs to initiate a payment flow. No money moves until the buyer approves and the order is captured.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "paypal.order_create", owner_id, args, account_id=account_id
        )

    async def order_get(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: PaypalOrderGetRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Retrieve full details of a PayPal order by its ID, including status, purchase units, payer info, and timestamps. Use this to check whether an order has been approved by the buyer, verify amounts before capturing, or inspect order history. This is a read-only operation with no side effects.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute("paypal.order_get", owner_id, args, account_id=account_id)
