# @generated by scripts/gen_sdk.py — DO NOT EDIT.

"""Typed SDK namespace for the `razorpay` app (generated)."""

from __future__ import annotations

from typing import TYPE_CHECKING, Any, Literal

from pydantic import BaseModel, ConfigDict, Field

from keyhaven.sdk._constants import DEFAULT_ACCOUNT_ID

if TYPE_CHECKING:
    from keyhaven.sdk.client import Keyhaven


class RazorpayOrderCreateHeader(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    Content_Type: str = Field(default="application/json", alias="Content-Type")


class RazorpayOrderCreateBody(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    amount: int
    currency: str
    receipt: str | None = None
    notes: dict[str, Any] | None = None
    partial_payment: bool | None = None


class RazorpayOrderCreateRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    header: RazorpayOrderCreateHeader | None = None
    body: RazorpayOrderCreateBody


class RazorpayOrderGetPath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    id: str


class RazorpayOrderGetRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: RazorpayOrderGetPath


class RazorpayOrdersListQuery(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    from_: int | None = Field(default=None, alias="from")
    to: int | None = None
    count: int = 10
    skip: int = 0
    authorized: int | None = None
    receipt: str | None = None


class RazorpayOrdersListRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    query: RazorpayOrdersListQuery | None = None


class RazorpayPaymentCapturePath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    id: str


class RazorpayPaymentCaptureHeader(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    Content_Type: str = Field(default="application/json", alias="Content-Type")


class RazorpayPaymentCaptureBody(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    amount: int
    currency: str


class RazorpayPaymentCaptureRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: RazorpayPaymentCapturePath
    header: RazorpayPaymentCaptureHeader | None = None
    body: RazorpayPaymentCaptureBody


class RazorpayPaymentGetPath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    id: str


class RazorpayPaymentGetRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: RazorpayPaymentGetPath


class RazorpayPaymentRefundCreatePath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    id: str


class RazorpayPaymentRefundCreateHeader(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    Content_Type: str = Field(default="application/json", alias="Content-Type")


class RazorpayPaymentRefundCreateBody(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    amount: int | None = None
    speed: Literal["normal", "optimum"] | None = None
    notes: dict[str, Any] | None = None
    receipt: str | None = None


class RazorpayPaymentRefundCreateRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: RazorpayPaymentRefundCreatePath
    header: RazorpayPaymentRefundCreateHeader | None = None
    body: RazorpayPaymentRefundCreateBody | None = None


class RazorpayNamespace:
    """Typed accessor for the `razorpay` app. Reach it via `client.apps.razorpay`."""

    def __init__(self, client: Keyhaven) -> None:
        self._client = client

    async def order_create(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: RazorpayOrderCreateRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Creates a new payment order on the merchant account with a specified amount and currency. The returned order_id must be passed to the Razorpay checkout for the customer to complete payment — no money moves at this stage. Use this when you need to initiate a transaction for a customer, for example after they submit a purchase in your application.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "razorpay.order_create", owner_id, args, account_id=account_id
        )

    async def order_get(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: RazorpayOrderGetRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Fetches a single payment order by its unique identifier, returning details such as amount, currency, status, and creation time. No data is modified — this is a read-only lookup. Use this when you need to check the status of an order, verify its amount before payment capture, or retrieve the order for reconciliation purposes.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "razorpay.order_get", owner_id, args, account_id=account_id
        )

    async def orders_list(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: RazorpayOrdersListRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Returns a paginated list of payment orders created on the merchant account, with optional filtering by creation time range, authorization status, and receipt identifier. Supports pagination via count and skip parameters. Use this when you need to browse recent orders, reconcile payments, or find a specific order by its receipt number.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "razorpay.orders_list", owner_id, args, account_id=account_id
        )

    async def payment_capture(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: RazorpayPaymentCaptureRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Captures an authorized but uncaptured payment, settling the funds from the customer's hold to the merchant account. This is an irreversible financial action that moves money. Use this when a payment has been authorized (e.g., via card block) and you are ready to complete the transaction, such as after an order has shipped or a service has been delivered.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "razorpay.payment_capture", owner_id, args, account_id=account_id
        )

    async def payment_get(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: RazorpayPaymentGetRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Fetches a single payment record by its unique identifier, returning details such as amount, status, method, bank, and linked order. No data is modified — this is a read-only lookup. Use this when you need to verify whether a payment succeeded, inspect payment method details, or retrieve information for customer support and reconciliation.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "razorpay.payment_get", owner_id, args, account_id=account_id
        )

    async def payment_refund_create(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: RazorpayPaymentRefundCreateRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Issues a refund against a captured payment, returning funds to the customer. Defaults to a full refund when the amount is omitted; partial refunds are supported by specifying an amount. This is a direct financial action that moves money out of the merchant account. Use this when you need to process a customer return, cancel an order after payment, or issue a partial refund for a service adjustment.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "razorpay.payment_refund_create", owner_id, args, account_id=account_id
        )
