# @generated by scripts/gen_sdk.py — DO NOT EDIT.

"""Typed SDK namespace for the `replicate` app (generated)."""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

from pydantic import BaseModel, ConfigDict, Field

from keyhaven.sdk._constants import DEFAULT_ACCOUNT_ID

if TYPE_CHECKING:
    from keyhaven.sdk.client import Keyhaven


class ReplicateModelFlux11ProHeader(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    Content_Type: str = Field(default="application/json", alias="Content-Type")
    Prefer: str = "wait"


class ReplicateModelFlux11ProBody(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    input: dict[str, Any]


class ReplicateModelFlux11ProRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    header: ReplicateModelFlux11ProHeader = Field(default_factory=ReplicateModelFlux11ProHeader)
    body: ReplicateModelFlux11ProBody


class ReplicateModelGroundingDinoHeader(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    Content_Type: str = Field(default="application/json", alias="Content-Type")
    Prefer: str = "wait"


class ReplicateModelGroundingDinoBody(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    version: str = "efd10a8ddc57ea28773327e881ce95e20cc1d734c589f7dd01d2036921ed78aa"
    input: dict[str, Any]


class ReplicateModelGroundingDinoRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    header: ReplicateModelGroundingDinoHeader = Field(
        default_factory=ReplicateModelGroundingDinoHeader
    )
    body: ReplicateModelGroundingDinoBody


class ReplicateNamespace:
    """Typed accessor for the `replicate` app. Reach it via `client.apps.replicate`."""

    def __init__(self, client: Keyhaven) -> None:
        self._client = client

    async def model_flux_1_1_pro(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: ReplicateModelFlux11ProRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Generates a photorealistic or artistic image from a text prompt using Black Forest Labs' FLUX 1.1 Pro model. The call creates a prediction on Replicate that returns an image URL, consuming API credits per generation. Supports control over aspect ratio, dimensions, output format, quality, and optional image-to-image guidance via Flux Redux. Use when an agent needs to produce a high-quality visual asset from a textual description.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "replicate.model_flux_1_1_pro", owner_id, args, account_id=account_id
        )

    async def model_grounding_dino(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: ReplicateModelGroundingDinoRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Runs zero-shot object detection on an image using the Grounding DINO model. Given a comma-separated list of object names and an image URL, the model returns bounding box coordinates and confidence scores for every detected match — no per-object training required. It can optionally return a visualised copy of the image with bounding boxes drawn on it. Use when an agent needs to locate, count, or extract spatial information about specific objects in a picture.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "replicate.model_grounding_dino", owner_id, args, account_id=account_id
        )
