# @generated by scripts/gen_sdk.py — DO NOT EDIT.

"""Typed SDK namespace for the `ring_central` app (generated)."""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

from pydantic import BaseModel, ConfigDict, Field

from keyhaven.sdk._constants import DEFAULT_ACCOUNT_ID

if TYPE_CHECKING:
    from keyhaven.sdk.client import Keyhaven


class RingCentralCallLogListPath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    accountId: str = "~"
    extensionId: str = "~"


class RingCentralCallLogListQuery(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    dateFrom: str | None = None
    dateTo: str | None = None
    type_: str | None = Field(default=None, alias="type")
    direction: str | None = None
    view: str | None = None
    page: int = 1
    perPage: int = 100


class RingCentralCallLogListRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: RingCentralCallLogListPath = Field(default_factory=RingCentralCallLogListPath)
    query: RingCentralCallLogListQuery | None = None


class RingCentralContactsListPath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    accountId: str = "~"
    extensionId: str = "~"


class RingCentralContactsListQuery(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    startsWith: str | None = None
    sortBy: str | None = None
    page: int = 1
    perPage: int = 100


class RingCentralContactsListRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: RingCentralContactsListPath = Field(default_factory=RingCentralContactsListPath)
    query: RingCentralContactsListQuery | None = None


class RingCentralExtensionGetPath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    accountId: str = "~"
    extensionId: str = "~"


class RingCentralExtensionGetRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: RingCentralExtensionGetPath = Field(default_factory=RingCentralExtensionGetPath)


class RingCentralExtensionsListPath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    accountId: str = "~"


class RingCentralExtensionsListQuery(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    type_: str | None = Field(default=None, alias="type")
    status: str | None = None
    page: int = 1
    perPage: int = 100


class RingCentralExtensionsListRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: RingCentralExtensionsListPath = Field(default_factory=RingCentralExtensionsListPath)
    query: RingCentralExtensionsListQuery | None = None


class RingCentralMessagesListPath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    accountId: str = "~"
    extensionId: str = "~"


class RingCentralMessagesListQuery(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    dateFrom: str | None = None
    dateTo: str | None = None
    direction: str | None = None
    messageType: str | None = None
    phoneNumber: str | None = None
    readStatus: str | None = None
    page: int = 1
    perPage: int = 100


class RingCentralMessagesListRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: RingCentralMessagesListPath = Field(default_factory=RingCentralMessagesListPath)
    query: RingCentralMessagesListQuery | None = None


class RingCentralSmsSendPath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    accountId: str = "~"
    extensionId: str = "~"


class RingCentralSmsSendBody(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    from_: dict[str, Any] = Field(alias="from")
    to: list[Any]
    text: str


class RingCentralSmsSendRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: RingCentralSmsSendPath = Field(default_factory=RingCentralSmsSendPath)
    body: RingCentralSmsSendBody


class RingCentralNamespace:
    """Typed accessor for the `ring_central` app. Reach it via `client.apps.ring_central`."""

    def __init__(self, client: Keyhaven) -> None:
        self._client = client

    async def call_log_list(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: RingCentralCallLogListRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Retrieves call history records for an account or a specific extension, with optional date range, direction, and type filters. Results include voice calls and faxes with timestamps, duration, and disposition. Agents should use this for auditing call activity, checking missed calls, or generating reports. No system state is changed.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "ring_central.call_log_list", owner_id, args, account_id=account_id
        )

    async def contacts_list(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: RingCentralContactsListRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Lists personal address-book contacts for a specific extension with optional name-based search filtering and sorting. Agents should use this to find contact information (names and phone numbers) for dialing or reference, or to verify a contact exists before messaging them. No system state is changed.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "ring_central.contacts_list", owner_id, args, account_id=account_id
        )

    async def extension_get(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: RingCentralExtensionGetRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Fetches detailed configuration and status of a single phone extension, including user info, device assignments, and service features. Agents should use this when they need extension-specific details like name, phone number, department, or enabled features before performing operations like messaging. No system state is changed.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "ring_central.extension_get", owner_id, args, account_id=account_id
        )

    async def extensions_list(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: RingCentralExtensionsListRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Lists all phone extensions (users, departments, IVR menus, voicemail, etc.) provisioned on the RingCentral account. Supports filtering by extension type and status, with pagination. Agents should use this to discover available extensions before performing extension-specific operations like sending SMS or viewing call logs. No system state is changed.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "ring_central.extensions_list", owner_id, args, account_id=account_id
        )

    async def messages_list(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: RingCentralMessagesListRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Retrieves messages (SMS, MMS, voicemail, fax) from an extension's message store with optional filters by date, direction, type, read status, and phone number. Agents should use this to check for incoming messages, review sent messages, or find messages exchanged with a specific contact. No system state is changed.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "ring_central.messages_list", owner_id, args, account_id=account_id
        )

    async def sms_send(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: RingCentralSmsSendRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Sends an outbound SMS or MMS message from a specified extension to one or more phone numbers. The message is delivered to external recipients via the phone network and appears in the sender's sent messages folder. Agents should use this to send text notifications, alerts, or time-sensitive information to customers or team members. This action is irreversible once sent and reaches real people on their mobile devices.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "ring_central.sms_send", owner_id, args, account_id=account_id
        )
