# @generated by scripts/gen_sdk.py — DO NOT EDIT.

"""Typed SDK namespace for the `salesloft` app (generated)."""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

from pydantic import BaseModel, ConfigDict, Field

from keyhaven.sdk._constants import DEFAULT_ACCOUNT_ID

if TYPE_CHECKING:
    from keyhaven.sdk.client import Keyhaven


class SalesloftAccountCreateBody(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    name: str
    domain: str | None = None
    industry: str | None = None
    number_of_employees: int | None = None
    annual_revenue: float | None = None
    phone: str | None = None
    website: str | None = None
    city: str | None = None
    state: str | None = None
    country: str | None = None
    owner_id: int | None = None
    account_tier_id: int | None = None
    account_stage_id: int | None = None


class SalesloftAccountCreateRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    body: SalesloftAccountCreateBody


class SalesloftAccountsListQuery(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    page: int | None = None
    per_page: int | None = None
    sort_by: str | None = None
    sort_direction: str | None = None
    ids: list[Any] | None = None
    owner_id: int | None = None


class SalesloftAccountsListRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    query: SalesloftAccountsListQuery | None = None


class SalesloftCadencesListQuery(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    page: int | None = None
    per_page: int | None = None
    sort_by: str | None = None
    sort_direction: str | None = None
    ids: list[Any] | None = None
    owner_id: int | None = None
    team_id: int | None = None


class SalesloftCadencesListRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    query: SalesloftCadencesListQuery | None = None


class SalesloftPeopleListQuery(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    page: int | None = None
    per_page: int | None = None
    sort_by: str | None = None
    sort_direction: str | None = None
    ids: list[Any] | None = None
    email_addresses: list[Any] | None = None
    owner_id: int | None = None


class SalesloftPeopleListRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    query: SalesloftPeopleListQuery | None = None


class SalesloftPersonCreateBody(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    email_address: str | None = None
    first_name: str | None = None
    last_name: str | None = None
    phone: str | None = None
    title: str | None = None
    company: str | None = None
    city: str | None = None
    state: str | None = None
    country: str | None = None
    owner_id: int | None = None
    cadence_id: int | None = None
    person_stage_id: int | None = None


class SalesloftPersonCreateRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    body: SalesloftPersonCreateBody = Field(default_factory=SalesloftPersonCreateBody)


class SalesloftNamespace:
    """Typed accessor for the `salesloft` app. Reach it via `client.apps.salesloft`."""

    def __init__(self, client: Keyhaven) -> None:
        self._client = client

    async def account_create(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: SalesloftAccountCreateRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Create a new account (company or organization) record in the Salesloft CRM with a required name and optional fields like domain, industry, revenue, and owner assignment. The new account becomes available across the platform for associating people, reporting, and account-based selling workflows, and can be later updated or deleted. Use this function when you need to add a new company to your CRM before associating contacts with it.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "salesloft.account_create", owner_id, args, account_id=account_id
        )

    async def accounts_list(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: SalesloftAccountsListRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Retrieve a paginated list of account records (companies or organizations) from the Salesloft CRM, with optional filtering by IDs, owner, and sorting by fields like name or date. This is a read-only operation that returns account details including industry, revenue, and contact information without modifying any data. Use this function to browse your account portfolio, find a specific company, or prepare data for account-based sales campaigns.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "salesloft.accounts_list", owner_id, args, account_id=account_id
        )

    async def cadences_list(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: SalesloftCadencesListRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Retrieve a paginated list of cadences (automated multi-step outreach sequences) from Salesloft, optionally filtered by owner, team, or specific IDs. This is a read-only operation that returns cadence metadata, step counts, and sharing settings without modifying any data. Use this function to discover available cadences when you need to enroll a person into an outreach sequence or audit existing automation workflows.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "salesloft.cadences_list", owner_id, args, account_id=account_id
        )

    async def people_list(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: SalesloftPeopleListRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Retrieve a paginated list of people (contacts) from the Salesloft CRM, with optional filtering by IDs, email addresses, owner, and sorting by fields like name or date. This is a read-only operation that returns person records including contact details and associated metadata. Use this function when you need to search for existing contacts, verify a person exists, or populate a contact list for downstream sales workflows.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "salesloft.people_list", owner_id, args, account_id=account_id
        )

    async def person_create(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: SalesloftPersonCreateRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Create a new person (contact) record in the Salesloft CRM with optional fields like name, company, phone, title, and assignment to a cadence or stage. The new person becomes available across the Salesloft platform for cadence enrollment, reporting, and team collaboration, and can later be updated or deleted. Use this function to add leads or contacts to your CRM when you have their information ready and want to initiate outreach sequences.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "salesloft.person_create", owner_id, args, account_id=account_id
        )
