# @generated by scripts/gen_sdk.py — DO NOT EDIT.

"""Typed SDK namespace for the `spotify` app (generated)."""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

from pydantic import BaseModel, ConfigDict

from keyhaven.sdk._constants import DEFAULT_ACCOUNT_ID

if TYPE_CHECKING:
    from keyhaven.sdk.client import Keyhaven


class SpotifyArtistsGetPath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    id: str


class SpotifyArtistsGetRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: SpotifyArtistsGetPath


class SpotifyArtistsListQuery(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    ids: str


class SpotifyArtistsListRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    query: SpotifyArtistsListQuery


class SpotifyBrowseCategoriesGetPath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    category_id: str


class SpotifyBrowseCategoriesGetQuery(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    country: str | None = None
    locale: str | None = None


class SpotifyBrowseCategoriesGetRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: SpotifyBrowseCategoriesGetPath
    query: SpotifyBrowseCategoriesGetQuery | None = None


class SpotifyBrowseCategoriesListQuery(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    country: str | None = None
    locale: str | None = None


class SpotifyBrowseCategoriesListRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    query: SpotifyBrowseCategoriesListQuery | None = None


class SpotifyMeListRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)
    pass


class SpotifyNamespace:
    """Typed accessor for the `spotify` app. Reach it via `client.apps.spotify`."""

    def __init__(self, client: Keyhaven) -> None:
        self._client = client

    async def artists_get(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: SpotifyArtistsGetRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Retrieve the full profile of a single Spotify artist by ID, including their genres, follower count, popularity score, and available images. This is a read-only operation that returns public data without any side effects. Use this function when you need detailed information about a specific artist for context such as bio lookup, music discovery, or playlist creation.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "spotify.artists_get", owner_id, args, account_id=account_id
        )

    async def artists_list(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: SpotifyArtistsListRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Fetch detailed profiles for one or more Spotify artists by their unique IDs, returning genres, followers, popularity score, and images. This is a read-only operation that retrieves public artist metadata without modifying anything. Use this function to get rich artist data for music recommendations, playlist curation, or display purposes.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "spotify.artists_list", owner_id, args, account_id=account_id
        )

    async def browse_categories_get(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: SpotifyBrowseCategoriesGetRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Retrieve details of a specific Spotify browse category by its ID, optionally localized by country and locale. This is a read-only operation that returns category metadata including its name and associated playlist links. Use this function when you already know the category ID and need to inspect its details before fetching category-specific playlists or content.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "spotify.browse_categories_get", owner_id, args, account_id=account_id
        )

    async def browse_categories_list(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: SpotifyBrowseCategoriesListRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Retrieve a list of Spotify browse categories (such as Party, Mood, Workout) optionally localized by country and locale. This is a read-only operation that returns the category catalog available for browsing playlists and content. Use this function to discover available content categories that you can later use to fetch curated playlists or explore Spotify's content taxonomy.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "spotify.browse_categories_list", owner_id, args, account_id=account_id
        )

    async def me_list(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: SpotifyMeListRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Retrieve the Spotify profile of the currently authenticated user, including display name, email, country, follower count, and subscription tier. This is a read-only operation that returns personal account details without making any changes. Use this function when an agent needs to verify the user's identity, check subscription status, or access profile information before performing user-specific actions.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute("spotify.me_list", owner_id, args, account_id=account_id)
