# @generated by scripts/gen_sdk.py — DO NOT EDIT.

"""Typed SDK namespace for the `typeform` app (generated)."""

from __future__ import annotations

from typing import TYPE_CHECKING, Any, Literal

from pydantic import BaseModel, ConfigDict, Field

from keyhaven.sdk._constants import DEFAULT_ACCOUNT_ID

if TYPE_CHECKING:
    from keyhaven.sdk.client import Keyhaven


class TypeformFormCreateBody(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    title: str
    type_: Literal["form", "quiz"] | None = Field(default=None, alias="type")
    workspace: dict[str, Any] | None = None
    theme: dict[str, Any] | None = None
    settings: dict[str, Any] | None = None
    welcome_screens: list[Any] | None = None
    thankyou_screens: list[Any] | None = None
    fields: list[Any] | None = None


class TypeformFormCreateRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    body: TypeformFormCreateBody


class TypeformFormGetPath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    form_id: str


class TypeformFormGetRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: TypeformFormGetPath


class TypeformFormUpdatePath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    form_id: str


class TypeformFormUpdateBody(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    title: str
    type_: str | None = Field(default=None, alias="type")
    workspace: dict[str, Any] | None = None
    theme: dict[str, Any] | None = None
    settings: dict[str, Any] | None = None
    welcome_screens: list[Any] | None = None
    thankyou_screens: list[Any] | None = None
    fields: list[Any] | None = None


class TypeformFormUpdateRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: TypeformFormUpdatePath
    body: TypeformFormUpdateBody


class TypeformFormsListQuery(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    search: str | None = None
    page: int = 1
    page_size: int = 10
    workspace_id: str | None = None
    sort_by: Literal["created_at", "last_updated_at"] | None = None
    order_by: Literal["asc", "desc"] | None = None


class TypeformFormsListRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    query: TypeformFormsListQuery | None = None


class TypeformResponsesListPath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    form_id: str


class TypeformResponsesListQuery(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    page_size: int = 25
    since: str | None = None
    until: str | None = None
    after: str | None = None
    before: str | None = None
    completed: bool | None = None
    sort: str | None = None
    query: str | None = None


class TypeformResponsesListRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: TypeformResponsesListPath
    query: TypeformResponsesListQuery | None = None


class TypeformWorkspacesListQuery(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    search: str | None = None
    page: int = 1
    page_size: int = 10


class TypeformWorkspacesListRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    query: TypeformWorkspacesListQuery | None = None


class TypeformNamespace:
    """Typed accessor for the `typeform` app. Reach it via `client.apps.typeform`."""

    def __init__(self, client: Keyhaven) -> None:
        self._client = client

    async def form_create(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: TypeformFormCreateRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Creates a new Typeform with the given title, type (form or quiz), fields, settings, welcome/thankyou screens, and theme. The form becomes immediately available at its Typeform URL and can start collecting responses as soon as it is published. Use this function when an agent needs to generate a dynamic survey, quiz, or feedback form programmatically — be aware that the created form is accessible to anyone with the link.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "typeform.form_create", owner_id, args, account_id=account_id
        )

    async def form_get(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: TypeformFormGetRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Fetches the complete JSON definition of a single form including its fields, settings, welcome screens, thankyou screens, and theme reference. This returns the form's structure without modifying any data on the server. Use this function when an agent needs to inspect a form's questions, choices, or configuration before responding to form-related queries or preparing an update.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "typeform.form_get", owner_id, args, account_id=account_id
        )

    async def form_update(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: TypeformFormUpdateRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Replaces the entire definition of an existing form — including its title, type, fields, settings, screens, and theme — with the provided payload. This is a full overwrite, so any fields omitted from the payload are removed from the form. Changes are visible to respondents immediately. Use this function when an agent needs to restructure or correct a published form, but always verify the payload since the operation is destructive to omitted content.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "typeform.form_update", owner_id, args, account_id=account_id
        )

    async def forms_list(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: TypeformFormsListRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Retrieves a paginated list of all forms in the authenticated Typeform account, filterable by title search, workspace, and sortable by creation or last-updated date. This is a read-only discovery operation that returns form metadata including IDs and titles. Use this function to find existing forms and obtain their identifiers before reading or modifying a specific form.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "typeform.forms_list", owner_id, args, account_id=account_id
        )

    async def responses_list(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: TypeformResponsesListRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Returns the form responses submitted by users, with optional filtering by date range, completion status, and full-text search across answers. This exposes the personal data that respondents have entered, which may include sensitive or personally identifiable information. Use this function when an agent needs to analyze survey results, export submissions, or verify data collection — but be aware that the returned data may have privacy implications.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "typeform.responses_list", owner_id, args, account_id=account_id
        )

    async def workspaces_list(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: TypeformWorkspacesListRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Lists the workspaces accessible to the authenticated Typeform account with optional search filtering and pagination. Workspaces are organizational containers for grouping forms. This read-only operation helps agents discover which workspace IDs to use when creating new forms or filtering existing ones. No data is created, modified, or deleted.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "typeform.workspaces_list", owner_id, args, account_id=account_id
        )
