# @generated by scripts/gen_sdk.py — DO NOT EDIT.

"""Typed SDK namespace for the `wrike` app (generated)."""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

from pydantic import BaseModel, ConfigDict, Field

from keyhaven.sdk._constants import DEFAULT_ACCOUNT_ID

if TYPE_CHECKING:
    from keyhaven.sdk.client import Keyhaven


class WrikeCreateFolderPath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    folderId: str


class WrikeCreateFolderBody(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    title: str
    description: str | None = None
    customFields: list[Any] | None = None


class WrikeCreateFolderRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: WrikeCreateFolderPath
    body: WrikeCreateFolderBody


class WrikeCreateTaskPath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    folderId: str


class WrikeCreateTaskBody(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    title: str
    description: str | None = None
    status: str | None = None
    importance: str | None = None
    responsibles: list[Any] | None = None
    dates: dict[str, Any] | None = None
    customFields: list[Any] | None = None


class WrikeCreateTaskRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: WrikeCreateTaskPath
    body: WrikeCreateTaskBody


class WrikeGetFolderTreePath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    folderId: str | None = None
    spaceId: str | None = None


class WrikeGetFolderTreeQuery(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    fields: list[Any] | None = None


class WrikeGetFolderTreeRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: WrikeGetFolderTreePath | None = None
    query: WrikeGetFolderTreeQuery | None = None


class WrikeModifyTasksPath(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    taskId: str


class WrikeModifyTasksBody(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    title: str | None = None
    description: str | None = None
    status: str | None = None
    importance: str | None = None
    dates: dict[str, Any] | None = None
    customFields: list[Any] | None = None


class WrikeModifyTasksRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    path: WrikeModifyTasksPath
    body: WrikeModifyTasksBody = Field(default_factory=WrikeModifyTasksBody)


class WrikeQueryTasksQuery(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    folderId: str | None = None
    spaceId: str | None = None
    taskIds: list[Any] | None = None
    status: str | None = None
    importance: str | None = None
    customFields: list[Any] | None = None
    pageSize: int | None = None
    nextPageToken: str | None = None


class WrikeQueryTasksRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", validate_by_name=True)

    query: WrikeQueryTasksQuery | None = None


class WrikeNamespace:
    """Typed accessor for the `wrike` app. Reach it via `client.apps.wrike`."""

    def __init__(self, client: Keyhaven) -> None:
        self._client = client

    async def create_folder(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: WrikeCreateFolderRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Creates a new subfolder within a specified parent folder in Wrike with a required title, optional description, and custom fields. The folder is immediately added to the workspace hierarchy and visible to all members with access to the parent. Use when an agent needs to organize work by creating new folders for projects, sprints, teams, or content categories.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "wrike.create_folder", owner_id, args, account_id=account_id
        )

    async def create_task(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: WrikeCreateTaskRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Creates a new task inside a specified Wrike folder or project with a required title and optional description, status, importance, assignees (responsibles), scheduling dates (start, due), and custom fields. The task appears immediately in the folder's task list and is visible to all workspace members with access. Use when an agent needs to add work items, delegate tasks to team members, or populate a project plan.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "wrike.create_task", owner_id, args, account_id=account_id
        )

    async def get_folder_tree(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: WrikeGetFolderTreeRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Retrieves the folder and project hierarchy from Wrike, optionally scoped to a specific parent folder or space, with configurable response fields. This provides an agent with the organizational structure of the workspace for navigation and reference. Use when you need to discover workspace layout, find the correct parent folder for task creation, or map the project hierarchy.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "wrike.get_folder_tree", owner_id, args, account_id=account_id
        )

    async def modify_tasks(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: WrikeModifyTasksRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Updates one or more attributes of an existing Wrike task identified by its ID, including title, description, status (Active, Completed, Deferred, Cancelled), importance, scheduling dates, and custom fields. Changes are applied immediately and visible to all workspace members. Use when an agent needs to progress task status, adjust deadlines, change assignees, or correct task metadata.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "wrike.modify_tasks", owner_id, args, account_id=account_id
        )

    async def query_tasks(
        self,
        *,
        owner_id: str,
        account_id: str = DEFAULT_ACCOUNT_ID,
        request: WrikeQueryTasksRequest | None = None,
        **fields: Any,
    ) -> Any:
        """
        Queries Wrike tasks with flexible filtering by folder, space, specific task IDs, status, importance, and custom field values. Returns paginated results with a next-page token for navigating large result sets. Use when an agent needs to find tasks matching criteria, check task statuses, or compile reports on project work across the workspace.
        """
        args = (
            request.model_dump(mode="json", by_alias=True, exclude_none=True)
            if request is not None
            else dict(fields)
        )
        return await self._client.execute(
            "wrike.query_tasks", owner_id, args, account_id=account_id
        )
